In [1]:
import joblib

MODEL = "../models/ahc_landslide_susceptibility_model.pkl"

obj = joblib.load(MODEL)

print("=" * 60)
print("AHC MODEL TYPE")
print("=" * 60)

print(type(obj))

print("\n" + "=" * 60)
print("AHC MODEL CONTENT")
print("=" * 60)

print(obj)

print("\n" + "=" * 60)
print("AHC ATTRIBUTES")
print("=" * 60)

if hasattr(obj, "__dict__"):
    for key, value in obj.__dict__.items():
        print(f"\n{key}:")
        print(type(value))
        print(value)
else:
    print("No __dict__ available.")

if isinstance(obj, dict):
    print("\n" + "=" * 60)
    print("DICTIONARY KEYS")
    print("=" * 60)

    for key in obj.keys():
        print(key)

FileNotFoundError: [Errno 2] No such file or directory: '../models/ahc_landslide_susceptibility_model.pkl'

In [2]:
import os

print("Current working directory:")
print(os.getcwd())

print("\nFiles/folders here:")
print(os.listdir())

Current working directory:
C:\Users\bubub\Downloads\MLLAYER

Files/folders here:
['.ipynb_checkpoints', 'data', 'models', 'Untitled.ipynb']

In [3]:
import os

for root, dirs, files in os.walk(os.getcwd()):
    for file in files:
        if file.lower().endswith((".pkl", ".pickle", ".joblib", ".json")):
            print(os.path.join(root, file))

C:\Users\bubub\Downloads\MLLAYER\models\ahc_landslide_susceptibility_model.pkl
C:\Users\bubub\Downloads\MLLAYER\models\STEP73_FROZEN_XGBOOST.json

In [4]:
import joblib
import os

MODEL = os.path.join(
    "models",
    "ahc_landslide_susceptibility_model.pkl"
)

print("Loading:")
print(os.path.abspath(MODEL))
print()

ahc = joblib.load(MODEL)

print("=" * 70)
print("AHC MODEL TYPE")
print("=" * 70)
print(type(ahc))

print("\n" + "=" * 70)
print("AHC MODEL DETAILS")
print("=" * 70)

if isinstance(ahc, dict):
    print("Dictionary keys:")
    for key in ahc.keys():
        print(f"  - {key}")

elif hasattr(ahc, "__dict__"):
    for key, value in ahc.__dict__.items():
        print(f"\n--- {key} ---")
        print("Type:", type(value))

        # Avoid dumping enormous arrays
        if hasattr(value, "shape"):
            print("Shape:", value.shape)
        else:
            print(value)

else:
    print(ahc)

Loading:
C:\Users\bubub\Downloads\MLLAYER\models\ahc_landslide_susceptibility_model.pkl

======================================================================
AHC MODEL TYPE
======================================================================
<class 'dict'>

======================================================================
AHC MODEL DETAILS
======================================================================
Dictionary keys:
  - scaler
  - soil_encoder
  - cluster_centroids
  - cluster_susceptibility
  - cluster_categories
  - feature_columns
  - numerical_features
  - categorical_features
  - n_clusters
  - clustering_method
  - linkage
  - distance_metric
  - development_period
  - test_period
  - road_features_used
  - susceptibility_thresholds

In [6]:
import os

data_folder = "data"

print("CSV files available:")
for f in os.listdir(data_folder):
    if f.lower().endswith(".csv"):
        print(" -", f)%%

SyntaxError: invalid syntax (1534100352.py, line 8)

In [7]:
import os

data_folder = "data"

print("CSV files available:")
for f in os.listdir(data_folder):
    if f.lower().endswith(".csv"):
        print(" -", f)

CSV files available:
 - Landslide_NER_MASTER_2016_ROWS_RAW.csv
 - Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv
 - Landslide_NER_XGBOOST_TRAIN_1278.csv

In [8]:
import pandas as pd
import os

CSV_PATH = os.path.join(
    "data",
    "Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv"
)

df = pd.read_csv(CSV_PATH)

print("Shape:", df.shape)

print("\nColumns:")
for i, col in enumerate(df.columns, 1):
    print(f"{i:3}. {col}")

print("\nFirst 5 rows:")
display(df.head())

Shape: (2016, 28)

Columns:
  1. master_row_id
  2. event_date
  3. state
  4. district
  5. latitude
  6. longitude
  7. rzsm_1
  8. rzsm_2
  9. rzsm_3
 10. landslide_occurred
 11. cumulative_rainfall_3d_mm
 12. elevation_m
 13. slope_deg
 14. soil_type_wrb
 15. road_mdr_pct
 16. road_odr_pct
 17. road_pmgsY_border_pct
 18. road_rural_pct
 19. month
 20. season
 21. _rzsm_mean_
 22. _rzsm_range_
 23. _rzsm_surface_deep_diff_
 24. _rain_rzsm_interaction_
 25. _previous_rzsm_
 26. _previous_rzsm_2_
 27. _previous_rzsm_3_
 28. _previous_rainfall_

First 5 rows:

,master_row_id,event_date,state,district,latitude,longitude,rzsm_1,rzsm_2,rzsm_3,landslide_occurred,...,month,season,_rzsm_mean_,_rzsm_range_,_rzsm_surface_deep_diff_,_rain_rzsm_interaction_,_previous_rzsm_,_previous_rzsm_2_,_previous_rzsm_3_,_previous_rainfall_
0,1,2023-01-12,Mizoram,Champhai,23.491709,93.20454,0.251417,0.279000,0.344042,0,...,1,Winter,0.291486,0.092625,-0.092625,0.000000,NaN,NaN,NaN,NaN
1,2,2023-01-26,Mizoram,Champhai,23.491709,93.20454,0.217375,0.250083,0.311583,1,...,1,Winter,0.259681,0.094208,-0.094208,0.000000,0.251417,0.2790,0.344042,0.0
2,3,2023-02-10,Arunachal Pradesh,Lower Dibang Valley,28.233286,95.77758,0.485458,0.467500,0.353208,0,...,2,Winter,0.435389,0.132250,0.132250,18.808800,NaN,NaN,NaN,NaN
3,4,2023-02-24,Arunachal Pradesh,Lower Dibang Valley,28.233286,95.77758,0.505083,0.512500,0.476333,1,...,2,Winter,0.497972,0.036167,0.028750,58.312547,0.485458,0.4675,0.353208,43.2
4,5,2023-03-10,Arunachal Pradesh,Upper Siang,28.782139,94.86048,0.326375,0.331708,0.338292,0,...,3,Pre-Monsoon,0.332125,0.011917,-0.011917,1.594200,NaN,NaN,NaN,NaN

In [9]:
# ============================================================
# STEP 9 — CHECK ALL REQUIRED MODEL FEATURES
# ============================================================

import pandas as pd
import os

CSV_PATH = os.path.join(
    "data",
    "Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv"
)

df = pd.read_csv(CSV_PATH)

# ------------------------------------------------------------
# XGBOOST: EXACT 12 FEATURES
# ------------------------------------------------------------

XGB_FEATURES = [
    "rzsm_1",
    "rzsm_2",
    "rzsm_3",
    "cumulative_rainfall_3d_mm",
    "_rzsm_mean_",
    "_rzsm_range_",
    "_rzsm_surface_deep_diff_",
    "_rain_rzsm_interaction_",
    "_previous_rzsm_",
    "_previous_rzsm_2_",
    "_previous_rzsm_3_",
    "_previous_rainfall_"
]

# ------------------------------------------------------------
# AHC: REQUIRED FEATURES
# ------------------------------------------------------------

AHC_FEATURES = [
    "cumulative_rainfall_3d_mm",
    "rzsm_1",
    "elevation_m",
    "slope_deg",
    "soil_type_wrb"
]

TARGET = "landslide_occurred"

# ------------------------------------------------------------
# CHECK MISSING COLUMNS
# ------------------------------------------------------------

missing_xgb = [
    c for c in XGB_FEATURES
    if c not in df.columns
]

missing_ahc = [
    c for c in AHC_FEATURES
    if c not in df.columns
]

missing_target = TARGET not in df.columns

print("=" * 70)
print("XGBOOST FEATURE CHECK")
print("=" * 70)

if missing_xgb:
    print("❌ Missing XGBoost columns:")
    print(missing_xgb)
else:
    print("✅ All 12 XGBoost features are present.")

print("\n" + "=" * 70)
print("AHC FEATURE CHECK")
print("=" * 70)

if missing_ahc:
    print("❌ Missing AHC columns:")
    print(missing_ahc)
else:
    print("✅ All AHC features are present.")

print("\n" + "=" * 70)
print("TARGET CHECK")
print("=" * 70)

if missing_target:
    print("❌ Target column missing.")
else:
    print("✅ Target column present:", TARGET)

# ------------------------------------------------------------
# MISSING VALUES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MISSING VALUES")
print("=" * 70)

check_columns = list(dict.fromkeys(
    XGB_FEATURES + AHC_FEATURES + [TARGET]
))

missing_table = df[check_columns].isna().sum()

print(missing_table[missing_table > 0])

# ------------------------------------------------------------
# TARGET DISTRIBUTION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)

print(df[TARGET].value_counts(dropna=False))

print("\nTarget percentages:")
print(
    df[TARGET]
    .value_counts(normalize=True, dropna=False)
    .mul(100)
    .round(2)
)

# ------------------------------------------------------------
# SOIL VALUES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("SOIL TYPES")
print("=" * 70)

print(
    df["soil_type_wrb"]
    .value_counts(dropna=False)
)

# ------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATASET SUMMARY")
print("=" * 70)

print("Rows:", len(df))
print("Columns:", len(df.columns))
print("XGBoost features:", len(XGB_FEATURES))
print("AHC features:", len(AHC_FEATURES))

======================================================================
XGBOOST FEATURE CHECK
======================================================================
✅ All 12 XGBoost features are present.

======================================================================
AHC FEATURE CHECK
======================================================================
✅ All AHC features are present.

======================================================================
TARGET CHECK
======================================================================
✅ Target column present: landslide_occurred

======================================================================
MISSING VALUES
======================================================================
_previous_rzsm_        656
_previous_rzsm_2_      656
_previous_rzsm_3_      656
_previous_rainfall_    656
dtype: int64

======================================================================
TARGET DISTRIBUTION
======================================================================
landslide_occurred
0    1344
1     672
Name: count, dtype: int64

Target percentages:
landslide_occurred
0    66.67
1    33.33
Name: proportion, dtype: float64

======================================================================
SOIL TYPES
======================================================================
soil_type_wrb
Cambisols    837
Luvisols     609
Acrisols     453
Leptosols    108
Fluvisols      6
Vertisols      3
Name: count, dtype: int64

======================================================================
DATASET SUMMARY
======================================================================
Rows: 2016
Columns: 28
XGBoost features: 12
AHC features: 5

In [10]:
# ============================================================
# STEP 10 — INSPECT FROZEN XGBOOST + AHC INFERENCE CONTRACT
# ============================================================

import os
import joblib
import xgboost as xgb

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

XGB_PATH = os.path.join(
    "models",
    "STEP73_FROZEN_XGBOOST.json"
)

AHC_PATH = os.path.join(
    "models",
    "ahc_landslide_susceptibility_model.pkl"
)

# ------------------------------------------------------------
# LOAD XGBOOST
# ------------------------------------------------------------

xgb_model = xgb.XGBClassifier()
xgb_model.load_model(XGB_PATH)

print("=" * 70)
print("XGBOOST MODEL")
print("=" * 70)

print("Loaded successfully.")
print("Number of estimators:", xgb_model.n_estimators)

print("\nXGBoost feature names:")
print(xgb_model.get_booster().feature_names)

# ------------------------------------------------------------
# LOAD AHC
# ------------------------------------------------------------

ahc = joblib.load(AHC_PATH)

print("\n" + "=" * 70)
print("AHC MODEL")
print("=" * 70)

print("Loaded successfully.")
print("Type:", type(ahc))

# ------------------------------------------------------------
# AHC METADATA
# ------------------------------------------------------------

print("\nAHC feature_columns:")
print(ahc["feature_columns"])

print("\nAHC numerical_features:")
print(ahc["numerical_features"])

print("\nAHC categorical_features:")
print(ahc["categorical_features"])

print("\nAHC number of clusters:")
print(ahc["n_clusters"])

print("\nAHC clustering method:")
print(ahc["clustering_method"])

print("\nAHC linkage:")
print(ahc["linkage"])

print("\nAHC distance metric:")
print(ahc["distance_metric"])

print("\nAHC susceptibility mapping:")
print(ahc["cluster_susceptibility"])

print("\nAHC category mapping:")
print(ahc["cluster_categories"])

print("\nAHC susceptibility thresholds:")
print(ahc["susceptibility_thresholds"])

======================================================================
XGBOOST MODEL
======================================================================
Loaded successfully.
Number of estimators: None

XGBoost feature names:
['rzsm_1', 'rzsm_2', 'rzsm_3', 'cumulative_rainfall_3d_mm', '_rzsm_mean_', '_rzsm_range_', '_rzsm_surface_deep_diff_', '_rain_rzsm_interaction_', '_previous_rzsm_', '_previous_rzsm_2_', '_previous_rzsm_3_', '_previous_rainfall_']

======================================================================
AHC MODEL
======================================================================
Loaded successfully.
Type: <class 'dict'>

AHC feature_columns:
['cumulative_rainfall_3d_mm', 'rzsm_0_100', 'elevation_m', 'slope_deg', 'soil_type_wrb_Acrisols', 'soil_type_wrb_Cambisols', 'soil_type_wrb_Fluvisols', 'soil_type_wrb_Leptosols', 'soil_type_wrb_Luvisols', 'soil_type_wrb_Vertisols']

AHC numerical_features:
['cumulative_rainfall_3d_mm', 'rzsm_0_100', 'elevation_m', 'slope_deg']

AHC categorical_features:
['soil_type_wrb']

AHC number of clusters:
7

AHC clustering method:
Agglomerative Hierarchical Clustering

AHC linkage:
Ward

AHC distance metric:
Euclidean

AHC susceptibility mapping:
{2: 0.0, 6: 5.0, 4: 9.813084112149532, 3: 32.63888888888889, 5: 38.46153846153847, 1: 89.8876404494382, 0: 92.20779220779221}

AHC category mapping:
{2: 'LOW', 6: 'LOW', 4: 'LOW', 3: 'HIGH', 5: 'HIGH', 1: 'VERY HIGH', 0: 'VERY HIGH'}

AHC susceptibility thresholds:
{'LOW': '<10%', 'HIGH': '30–70%', 'VERY HIGH': '>=70%'}

In [11]:
# ============================================================
# STEP 11 — FIND HOW AHC RZSM_0_100 RELATES TO THE DATA
# ============================================================

import pandas as pd
import numpy as np

# Load master dataset
df = pd.read_csv(
    "data/Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv"
)

print("=" * 70)
print("RZSM COLUMNS")
print("=" * 70)

rzsm_cols = [
    c for c in df.columns
    if "rzsm" in c.lower()
]

print(rzsm_cols)

print("\n" + "=" * 70)
print("RZSM STATISTICS")
print("=" * 70)

print(
    df[["rzsm_1", "rzsm_2", "rzsm_3"]]
    .describe()
)

print("\n" + "=" * 70)
print("FIRST 10 RZSM ROWS")
print("=" * 70)

print(
    df[
        [
            "rzsm_1",
            "rzsm_2",
            "rzsm_3"
        ]
    ].head(10)
)

# ------------------------------------------------------------
# Check possible conversions to percentage
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("POSSIBLE RZSM CONVERSIONS")
print("=" * 70)

for col in ["rzsm_1", "rzsm_2", "rzsm_3"]:

    print(f"\n{col}")

    print("0–1 range:")
    print(
        df[col].min(),
        "to",
        df[col].max()
    )

    print("×100 range:")
    print(
        (df[col] * 100).min(),
        "to",
        (df[col] * 100).max()
    )

# ------------------------------------------------------------
# Inspect AHC scaler
# ------------------------------------------------------------

import joblib

ahc = joblib.load(
    "models/ahc_landslide_susceptibility_model.pkl"
)

scaler = ahc["scaler"]

print("\n" + "=" * 70)
print("AHC SCALER")
print("=" * 70)

print("Scaler type:")
print(type(scaler))

print("\nScaler feature names:")
if hasattr(scaler, "feature_names_in_"):
    print(scaler.feature_names_in_)

print("\nScaler mean:")
print(scaler.mean_)

print("\nScaler scale:")
print(scaler.scale_)

======================================================================
RZSM COLUMNS
======================================================================
['rzsm_1', 'rzsm_2', 'rzsm_3', '_rzsm_mean_', '_rzsm_range_', '_rzsm_surface_deep_diff_', '_rain_rzsm_interaction_', '_previous_rzsm_', '_previous_rzsm_2_', '_previous_rzsm_3_']

======================================================================
RZSM STATISTICS
======================================================================
            rzsm_1       rzsm_2       rzsm_3
count  2016.000000  2016.000000  2016.000000
mean      0.412389     0.415264     0.401878
std       0.087865     0.082775     0.084071
min       0.073083     0.126000     0.124000
25%       0.360167     0.367448     0.352354
50%       0.423292     0.422042     0.411833
75%       0.492125     0.492333     0.475792
max       0.515958     0.517542     0.518917

======================================================================
FIRST 10 RZSM ROWS
======================================================================
     rzsm_1    rzsm_2    rzsm_3
0  0.251417  0.279000  0.344042
1  0.217375  0.250083  0.311583
2  0.485458  0.467500  0.353208
3  0.505083  0.512500  0.476333
4  0.326375  0.331708  0.338292
5  0.369292  0.377792  0.432458
6  0.293500  0.159625  0.220625
7  0.246250  0.236875  0.267708
8  0.501625  0.494792  0.314750
9  0.421750  0.419042  0.372708

======================================================================
POSSIBLE RZSM CONVERSIONS
======================================================================

rzsm_1
0–1 range:
0.0730833333333333 to 0.5159583333333334
×100 range:
7.308333333333331 to 51.59583333333334

rzsm_2
0–1 range:
0.126 to 0.5175416666666667
×100 range:
12.6 to 51.75416666666667

rzsm_3
0–1 range:
0.124 to 0.5189166666666667
×100 range:
12.4 to 51.891666666666666

======================================================================
AHC SCALER
======================================================================
Scaler type:
<class 'sklearn.preprocessing._data.StandardScaler'>

Scaler feature names:
['cumulative_rainfall_3d_mm' 'rzsm_0_100' 'elevation_m' 'slope_deg']

Scaler mean:
[6.52847843e+01 3.78369066e-01 8.03433763e+02 1.93914420e+01]

Scaler scale:
[6.82713633e+01 7.07844678e-02 6.94453708e+02 1.11825930e+01]

In [12]:
# ============================================================
# STEP 12 — IDENTIFY AHC RZSM_0_100 REPRESENTATION
# ============================================================

import joblib
import numpy as np
import pandas as pd

# Load AHC artifact
ahc = joblib.load(
    "models/ahc_landslide_susceptibility_model.pkl"
)

scaler = ahc["scaler"]
centroids = np.asarray(ahc["cluster_centroids"])

print("=" * 70)
print("AHC CENTROIDS")
print("=" * 70)

print("Shape:", centroids.shape)
print(centroids)

print("\n" + "=" * 70)
print("AHC FEATURE ORDER")
print("=" * 70)

print(ahc["feature_columns"])

# ------------------------------------------------------------
# Convert standardized centroid values back to original units
# ------------------------------------------------------------

centroids_original = scaler.inverse_transform(
    centroids[:, :4]
)

centroid_df = pd.DataFrame(
    centroids_original,
    columns=[
        "cumulative_rainfall_3d_mm",
        "rzsm_0_100",
        "elevation_m",
        "slope_deg"
    ]
)

centroid_df["cluster"] = range(
    len(centroid_df)
)

print("\n" + "=" * 70)
print("CENTROIDS IN ORIGINAL UNITS")
print("=" * 70)

display(
    centroid_df[
        [
            "cluster",
            "cumulative_rainfall_3d_mm",
            "rzsm_0_100",
            "elevation_m",
            "slope_deg"
        ]
    ]
)

# ------------------------------------------------------------
# Compare centroid RZSM range with candidate transformations
# ------------------------------------------------------------

df = pd.read_csv(
    "data/Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv"
)

candidate_rzsm = pd.DataFrame({
    "rzsm_1": df["rzsm_1"],
    "rzsm_2": df["rzsm_2"],
    "rzsm_3": df["rzsm_3"],
    "rzsm_mean": df[
        ["rzsm_1", "rzsm_2", "rzsm_3"]
    ].mean(axis=1)
})

print("\n" + "=" * 70)
print("CANDIDATE RZSM DISTRIBUTIONS")
print("=" * 70)

print(
    candidate_rzsm.describe()
)

print("\nAHC training RZSM:")
print(
    "mean =", scaler.mean_[1]
)

print(
    "std  =", scaler.scale_[1]
)

print(
    "min/max of candidates:"
)

for col in candidate_rzsm.columns:
    print(
        f"{col:12s}: "
        f"{candidate_rzsm[col].min():.6f} "
        f"to "
        f"{candidate_rzsm[col].max():.6f}"
    )

======================================================================
AHC CENTROIDS
======================================================================
Shape: (7, 10)
[[ 1.2077138  -0.46036939  0.87022715 -0.02182315  0.02597403  0.01298701
   0.          0.          0.96103896  0.        ]
 [ 1.08312365 -0.38967483 -0.41474852 -0.26802123  0.44382022  0.55617978
   0.          0.          0.          0.        ]
 [-0.26997737  1.5682575  -0.34720938 -0.42619809  0.36734694  0.43537415
   0.          0.03401361  0.15646259  0.00680272]
 [-0.07253325 -0.08899291  0.05050471  1.42330731  0.02777778  0.38194444
   0.          0.15277778  0.4375      0.        ]
 [-0.799391   -0.48355448 -0.37643268 -0.28240595  0.45794393  0.45327103
   0.02336449  0.05607477  0.          0.00934579]
 [-0.22438758 -0.55004093  4.41347035  0.32998576  0.          0.
   0.          0.46153846  0.53846154  0.        ]
 [-0.77089748 -0.028464    0.92207908 -0.45964894  0.          0.
   0.          0.          1.          0.        ]]

======================================================================
AHC FEATURE ORDER
======================================================================
['cumulative_rainfall_3d_mm', 'rzsm_0_100', 'elevation_m', 'slope_deg', 'soil_type_wrb_Acrisols', 'soil_type_wrb_Cambisols', 'soil_type_wrb_Fluvisols', 'soil_type_wrb_Leptosols', 'soil_type_wrb_Luvisols', 'soil_type_wrb_Vertisols']

======================================================================
CENTROIDS IN ORIGINAL UNITS
======================================================================

   cluster  cumulative_rainfall_3d_mm  rzsm_0_100  elevation_m  slope_deg
0        0                 147.737052    0.345782  1407.766234  19.147403
1        1                 139.231112    0.350786   515.410112  16.394270
2        2                  46.853061    0.489377   562.312925  14.625442
3        3                  60.332840    0.372070   838.506944  35.307708
4        4                  10.709271    0.344141   542.018692  16.233411
5        5                  49.965538    0.339435  3868.384615  23.081538
6        6                  12.654562    0.376354  1443.775000  14.251375

======================================================================
CANDIDATE RZSM DISTRIBUTIONS
======================================================================
            rzsm_1       rzsm_2       rzsm_3    rzsm_mean
count  2016.000000  2016.000000  2016.000000  2016.000000
mean      0.412389     0.415264     0.401878     0.409844
std       0.087865     0.082775     0.084071     0.079824
min       0.073083     0.126000     0.124000     0.119250
25%       0.360167     0.367448     0.352354     0.364323
50%       0.423292     0.422042     0.411833     0.417611
75%       0.492125     0.492333     0.475792     0.483958
max       0.515958     0.517542     0.518917     0.515014

AHC training RZSM:
mean = 0.3783690661391168
std  = 0.07078446777317013
min/max of candidates:
rzsm_1      : 0.073083 to 0.515958
rzsm_2      : 0.126000 to 0.517542
rzsm_3      : 0.124000 to 0.518917
rzsm_mean   : 0.119250 to 0.515014

In [13]:
import os
import pandas as pd

data_folder = "data"

for filename in os.listdir(data_folder):

    if not filename.lower().endswith(".csv"):
        continue

    path = os.path.join(data_folder, filename)

    try:
        temp = pd.read_csv(path)

        print("\n" + "=" * 70)
        print(filename)
        print("=" * 70)

        print("Shape:", temp.shape)

        rzsm_columns = [
            c for c in temp.columns
            if "rzsm" in c.lower()
        ]

        print("RZSM columns:", rzsm_columns)

        if "rzsm_0_100" in temp.columns:
            print(">>> FOUND rzsm_0_100 <<<")
            print(
                temp["rzsm_0_100"].describe()
            )

    except Exception as e:
        print(filename, "-> could not read:", e)

======================================================================
Landslide_NER_MASTER_2016_ROWS_RAW.csv
======================================================================
Shape: (2016, 19)
RZSM columns: ['rzsm_1', 'rzsm_2', 'rzsm_3']

======================================================================
Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv
======================================================================
Shape: (2016, 28)
RZSM columns: ['rzsm_1', 'rzsm_2', 'rzsm_3', '_rzsm_mean_', '_rzsm_range_', '_rzsm_surface_deep_diff_', '_rain_rzsm_interaction_', '_previous_rzsm_', '_previous_rzsm_2_', '_previous_rzsm_3_']

======================================================================
Landslide_NER_XGBOOST_TRAIN_1278.csv
======================================================================
Shape: (1278, 28)
RZSM columns: ['rzsm_1', 'rzsm_2', 'rzsm_3', '_rzsm_mean_', '_rzsm_range_', '_rzsm_surface_deep_diff_', '_rain_rzsm_interaction_', '_previous_rzsm_', '_previous_rzsm_2_', '_previous_rzsm_3_']

In [14]:
import os
import pandas as pd

data_folder = "data"

print("ALL CSV FILES:\n")

for filename in os.listdir(data_folder):

    if filename.lower().endswith(".csv"):

        path = os.path.join(data_folder, filename)

        try:
            temp = pd.read_csv(path)

            print("=" * 80)
            print(filename)
            print("Shape:", temp.shape)
            print("Columns:")
            print(list(temp.columns))

            if "rzsm_0_100" in temp.columns:
                print("\n>>> THIS IS AN AHC-READY DATASET <<<")
                print("\nRZSM statistics:")
                print(temp["rzsm_0_100"].describe())

        except Exception as e:
            print(filename, "ERROR:", e)

ALL CSV FILES:

================================================================================
Landslide_NER_AHC_Preprocessed_Final.csv
Shape: (2016, 18)
Columns:
['event_date', 'state', 'district', 'latitude', 'longitude', 'rzsm_1', 'rzsm_2', 'rzsm_3', 'rzsm_0_100', 'landslide_occurred', 'cumulative_rainfall_3d_mm', 'elevation_m', 'slope_deg', 'soil_type_wrb', 'road_mdr_pct', 'road_odr_pct', 'road_pmgsY_border_pct', 'road_rural_pct']

>>> THIS IS AN AHC-READY DATASET <<<

RZSM statistics:
count    2016.000000
mean        0.370597
std         0.069455
min         0.126920
25%         0.329815
50%         0.362009
75%         0.413136
max         0.515042
Name: rzsm_0_100, dtype: float64
================================================================================
Landslide_NER_MASTER_2016_ROWS_RAW.csv
Shape: (2016, 19)
Columns:
['event_date', 'state', 'district', 'latitude', 'longitude', 'rzsm_1', 'rzsm_2', 'rzsm_3', 'landslide_occurred', 'cumulative_rainfall_3d_mm', 'elevation_m', 'slope_deg', 'soil_type_wrb', 'road_mdr_pct', 'road_odr_pct', 'road_pmgsY_border_pct', 'road_rural_pct', 'month', 'season']
================================================================================
Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv
Shape: (2016, 28)
Columns:
['master_row_id', 'event_date', 'state', 'district', 'latitude', 'longitude', 'rzsm_1', 'rzsm_2', 'rzsm_3', 'landslide_occurred', 'cumulative_rainfall_3d_mm', 'elevation_m', 'slope_deg', 'soil_type_wrb', 'road_mdr_pct', 'road_odr_pct', 'road_pmgsY_border_pct', 'road_rural_pct', 'month', 'season', '_rzsm_mean_', '_rzsm_range_', '_rzsm_surface_deep_diff_', '_rain_rzsm_interaction_', '_previous_rzsm_', '_previous_rzsm_2_', '_previous_rzsm_3_', '_previous_rainfall_']
================================================================================
Landslide_NER_XGBOOST_TRAIN_1278.csv
Shape: (1278, 28)
Columns:
['master_row_id', 'event_date', 'state', 'district', 'latitude', 'longitude', 'rzsm_1', 'rzsm_2', 'rzsm_3', 'landslide_occurred', 'cumulative_rainfall_3d_mm', 'elevation_m', 'slope_deg', 'soil_type_wrb', 'road_mdr_pct', 'road_odr_pct', 'road_pmgsY_border_pct', 'road_rural_pct', 'month', 'season', '_rzsm_mean_', '_rzsm_range_', '_rzsm_surface_deep_diff_', '_rain_rzsm_interaction_', '_previous_rzsm_', '_previous_rzsm_2_', '_previous_rzsm_3_', '_previous_rainfall_']

In [15]:
# ============================================================
# STEP 13 — VERIFY XGBOOST AND AHC DATASET ALIGNMENT
# ============================================================

import pandas as pd
import os

xgb_path = os.path.join(
    "data",
    "Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv"
)

ahc_path = os.path.join(
    "data",
    "Landslide_NER_AHC_Preprocessed_Final.csv"
)

xgb_df = pd.read_csv(xgb_path)
ahc_df = pd.read_csv(ahc_path)

print("=" * 70)
print("DATASET SIZES")
print("=" * 70)

print("XGBoost dataset:", xgb_df.shape)
print("AHC dataset:", ahc_df.shape)

# ------------------------------------------------------------
# Compare identifying columns
# ------------------------------------------------------------

KEY_COLUMNS = [
    "event_date",
    "state",
    "district",
    "latitude",
    "longitude",
    "landslide_occurred"
]

print("\n" + "=" * 70)
print("KEY COLUMN CHECK")
print("=" * 70)

for col in KEY_COLUMNS:

    xgb_values = xgb_df[col].astype(str).reset_index(drop=True)
    ahc_values = ahc_df[col].astype(str).reset_index(drop=True)

    matches = (xgb_values == ahc_values).sum()

    print(
        f"{col:25s}: "
        f"{matches}/{len(xgb_df)} "
        f"matching "
        f"({matches / len(xgb_df) * 100:.2f}%)"
    )

# ------------------------------------------------------------
# Full row identity check
# ------------------------------------------------------------

same_rows = True

for col in KEY_COLUMNS:

    if not (
        xgb_df[col]
        .astype(str)
        .reset_index(drop=True)
        .equals(
            ahc_df[col]
            .astype(str)
            .reset_index(drop=True)
        )
    ):
        same_rows = False

print("\n" + "=" * 70)
print("FINAL ALIGNMENT RESULT")
print("=" * 70)

if same_rows:
    print("✅ DATASETS ARE ROW-ALIGNED.")
    print("We can safely combine model outputs by row index.")
else:
    print("❌ DATASETS ARE NOT IDENTICAL ROW-BY-ROW.")
    print("We must merge them using stable geographic/date keys.")

======================================================================
DATASET SIZES
======================================================================
XGBoost dataset: (2016, 28)
AHC dataset: (2016, 18)

======================================================================
KEY COLUMN CHECK
======================================================================
event_date               : 2016/2016 matching (100.00%)
state                    : 2016/2016 matching (100.00%)
district                 : 2016/2016 matching (100.00%)
latitude                 : 2016/2016 matching (100.00%)
longitude                : 2016/2016 matching (100.00%)
landslide_occurred       : 2016/2016 matching (100.00%)

======================================================================
FINAL ALIGNMENT RESULT
======================================================================
✅ DATASETS ARE ROW-ALIGNED.
We can safely combine model outputs by row index.

In [16]:
# ============================================================
# STEP 14 — GENERATE XGBOOST + AHC LAYER OUTPUTS
# ============================================================

import pandas as pd
import numpy as np
import joblib
import xgboost as xgb
import os

# ============================================================
# 1. LOAD DATA
# ============================================================

XGB_CSV = os.path.join(
    "data",
    "Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv"
)

AHC_CSV = os.path.join(
    "data",
    "Landslide_NER_AHC_Preprocessed_Final.csv"
)

xgb_df = pd.read_csv(XGB_CSV)
ahc_df = pd.read_csv(AHC_CSV)

print("XGBoost rows:", len(xgb_df))
print("AHC rows:", len(ahc_df))


# ============================================================
# 2. LOAD FROZEN XGBOOST
# ============================================================

XGB_MODEL = os.path.join(
    "models",
    "STEP73_FROZEN_XGBOOST.json"
)

xgb_model = xgb.XGBClassifier()
xgb_model.load_model(XGB_MODEL)

print("\nXGBoost model loaded.")


# ============================================================
# 3. XGBOOST EXACT 12 FEATURES
# ============================================================

XGB_FEATURES = [
    "rzsm_1",
    "rzsm_2",
    "rzsm_3",
    "cumulative_rainfall_3d_mm",
    "_rzsm_mean_",
    "_rzsm_range_",
    "_rzsm_surface_deep_diff_",
    "_rain_rzsm_interaction_",
    "_previous_rzsm_",
    "_previous_rzsm_2_",
    "_previous_rzsm_3_",
    "_previous_rainfall_"
]

X_xgb = xgb_df[XGB_FEATURES].copy()

print("\nXGBoost input shape:", X_xgb.shape)


# ============================================================
# 4. HANDLE XGBOOST MISSING VALUES
# ============================================================

# XGBoost itself can handle NaN values.
# We therefore DO NOT impute or delete the 656 rows here.

X_xgb = X_xgb.apply(
    pd.to_numeric,
    errors="coerce"
)

print(
    "Rows containing NaN in temporal features:",
    X_xgb.isna().any(axis=1).sum()
)


# ============================================================
# 5. RUN XGBOOST
# ============================================================

xgb_probability = xgb_model.predict_proba(
    X_xgb
)[:, 1]

xgb_prediction = (
    xgb_probability >= 0.50
).astype(int)

xgb_df["xgb_probability"] = xgb_probability
xgb_df["xgb_prediction"] = xgb_prediction

print("\nXGBoost predictions generated.")


# ============================================================
# 6. LOAD FROZEN AHC
# ============================================================

AHC_MODEL = os.path.join(
    "models",
    "ahc_landslide_susceptibility_model.pkl"
)

ahc = joblib.load(AHC_MODEL)

print("\nAHC model loaded.")


# ============================================================
# 7. PREPARE AHC NUMERICAL FEATURES
# ============================================================

AHC_NUMERICAL = [
    "cumulative_rainfall_3d_mm",
    "rzsm_0_100",
    "elevation_m",
    "slope_deg"
]

X_num = ahc_df[AHC_NUMERICAL].copy()

X_num = X_num.apply(
    pd.to_numeric,
    errors="coerce"
)


# ============================================================
# 8. PREPARE AHC SOIL ENCODING
# ============================================================

soil_encoder = ahc["soil_encoder"]

X_soil = ahc_df[["soil_type_wrb"]].copy()

soil_encoded = soil_encoder.transform(
    X_soil
)

# Convert sparse matrix if necessary
if hasattr(soil_encoded, "toarray"):
    soil_encoded = soil_encoded.toarray()

soil_columns = [
    "soil_type_wrb_Acrisols",
    "soil_type_wrb_Cambisols",
    "soil_type_wrb_Fluvisols",
    "soil_type_wrb_Leptosols",
    "soil_type_wrb_Luvisols",
    "soil_type_wrb_Vertisols"
]

X_soil_encoded = pd.DataFrame(
    soil_encoded,
    columns=soil_columns,
    index=ahc_df.index
)


# ============================================================
# 9. COMBINE AHC FEATURES
# ============================================================

X_ahc_raw = pd.concat(
    [
        X_num,
        X_soil_encoded
    ],
    axis=1
)

# Force exact artifact feature order
X_ahc_raw = X_ahc_raw[
    ahc["feature_columns"]
]

print(
    "\nAHC feature matrix:",
    X_ahc_raw.shape
)


# ============================================================
# 10. STANDARDIZE AHC NUMERICAL FEATURES
# ============================================================

# IMPORTANT:
# The scaler was trained only on the four numerical features.

X_ahc_scaled_num = ahc["scaler"].transform(
    X_num
)

X_ahc_scaled = np.column_stack(
    [
        X_ahc_scaled_num,
        X_soil_encoded.values
    ]
)

X_ahc_scaled = pd.DataFrame(
    X_ahc_scaled,
    columns=ahc["feature_columns"],
    index=ahc_df.index
)


# ============================================================
# 11. CALCULATE AHC CLUSTER
# ============================================================

from scipy.spatial.distance import cdist

centroids = np.asarray(
    ahc["cluster_centroids"]
)

distances = cdist(
    X_ahc_scaled.values,
    centroids,
    metric="euclidean"
)

ahc_cluster = np.argmin(
    distances,
    axis=1
)


# ============================================================
# 12. AHC SUSCEPTIBILITY
# ============================================================

susceptibility_mapping = (
    ahc["cluster_susceptibility"]
)

category_mapping = (
    ahc["cluster_categories"]
)

ahc_susceptibility = np.array([
    susceptibility_mapping[int(cluster)]
    for cluster in ahc_cluster
])

ahc_category = np.array([
    category_mapping[int(cluster)]
    for cluster in ahc_cluster
])


# ============================================================
# 13. ADD AHC OUTPUTS
# ============================================================

xgb_df["ahc_cluster"] = ahc_cluster
xgb_df["ahc_susceptibility"] = ahc_susceptibility
xgb_df["ahc_category"] = ahc_category


# ============================================================
# 14. CREATE LAYERING DATASET
# ============================================================

layer_columns = [
    "master_row_id",
    "event_date",
    "state",
    "district",
    "latitude",
    "longitude",
    "landslide_occurred",

    # XGBoost layer
    "xgb_probability",
    "xgb_prediction",

    # AHC layer
    "ahc_cluster",
    "ahc_susceptibility",
    "ahc_category"
]

layering_df = xgb_df[layer_columns].copy()


# ============================================================
# 15. SAVE
# ============================================================

OUTPUT = os.path.join(
    "data",
    "layering_dataset.csv"
)

layering_df.to_csv(
    OUTPUT,
    index=False
)


# ============================================================
# 16. DISPLAY RESULTS
# ============================================================

print("\n" + "=" * 70)
print("LAYERING DATASET CREATED")
print("=" * 70)

print("Rows:", len(layering_df))
print("Columns:", len(layering_df.columns))
print("Saved:", OUTPUT)

print("\nFirst 10 rows:")

display(
    layering_df.head(10)
)

print("\n" + "=" * 70)
print("XGBOOST OUTPUT DISTRIBUTION")
print("=" * 70)

print(
    layering_df["xgb_prediction"]
    .value_counts()
)

print("\n" + "=" * 70)
print("AHC CLUSTER DISTRIBUTION")
print("=" * 70)

print(
    layering_df["ahc_cluster"]
    .value_counts()
    .sort_index()
)

print("\n" + "=" * 70)
print("AHC CATEGORY DISTRIBUTION")
print("=" * 70)

print(
    layering_df["ahc_category"]
    .value_counts()
)

print("\n" + "=" * 70)
print("SAMPLE MODEL OUTPUTS")
print("=" * 70)

display(
    layering_df[
        [
            "landslide_occurred",
            "xgb_probability",
            "xgb_prediction",
            "ahc_cluster",
            "ahc_susceptibility",
            "ahc_category"
        ]
    ].head(20)
)

XGBoost rows: 2016
AHC rows: 2016

XGBoost model loaded.

XGBoost input shape: (2016, 12)
Rows containing NaN in temporal features: 656

XGBoost predictions generated.

AHC model loaded.

AHC feature matrix: (2016, 10)

======================================================================
LAYERING DATASET CREATED
======================================================================
Rows: 2016
Columns: 12
Saved: data\layering_dataset.csv

First 10 rows:

,master_row_id,event_date,state,district,latitude,longitude,landslide_occurred,xgb_probability,xgb_prediction,ahc_cluster,ahc_susceptibility,ahc_category
0,1,2023-01-12,Mizoram,Champhai,23.491709,93.204540,0,0.000875,0,4,9.813084,LOW
1,2,2023-01-26,Mizoram,Champhai,23.491709,93.204540,1,0.171223,0,4,9.813084,LOW
2,3,2023-02-10,Arunachal Pradesh,Lower Dibang Valley,28.233286,95.777580,0,0.001368,0,4,9.813084,LOW
3,4,2023-02-24,Arunachal Pradesh,Lower Dibang Valley,28.233286,95.777580,1,0.982948,1,4,9.813084,LOW
4,5,2023-03-10,Arunachal Pradesh,Upper Siang,28.782139,94.860480,0,0.001286,0,3,32.638889,HIGH
5,6,2023-03-12,Sikkim,Gangtok,27.392355,88.523200,0,0.003202,0,3,32.638889,HIGH
6,7,2023-03-17,Tripura,Khowai,23.837263,91.628720,0,0.001235,0,4,9.813084,LOW
7,8,2023-03-20,Assam,Dhemaji,27.554682,94.259926,0,0.001171,0,3,32.638889,HIGH
8,9,2023-03-22,Meghalaya,East Jaintia Hills,25.105930,92.360245,0,0.002322,0,4,9.813084,LOW
9,10,2023-03-24,Arunachal Pradesh,Upper Siang,28.782139,94.860480,1,0.972743,1,3,32.638889,HIGH

======================================================================
XGBOOST OUTPUT DISTRIBUTION
======================================================================
xgb_prediction
0    1319
1     697
Name: count, dtype: int64

======================================================================
AHC CLUSTER DISTRIBUTION
======================================================================
ahc_cluster
0    209
1    337
2    306
3    350
4    507
5     16
6    291
Name: count, dtype: int64

======================================================================
AHC CATEGORY DISTRIBUTION
======================================================================
ahc_category
LOW          1104
VERY HIGH     546
HIGH          366
Name: count, dtype: int64

======================================================================
SAMPLE MODEL OUTPUTS
======================================================================

,landslide_occurred,xgb_probability,xgb_prediction,ahc_cluster,ahc_susceptibility,ahc_category
0,0,0.000875,0,4,9.813084,LOW
1,1,0.171223,0,4,9.813084,LOW
2,0,0.001368,0,4,9.813084,LOW
3,1,0.982948,1,4,9.813084,LOW
4,0,0.001286,0,3,32.638889,HIGH
5,0,0.003202,0,3,32.638889,HIGH
6,0,0.001235,0,4,9.813084,LOW
7,0,0.001171,0,3,32.638889,HIGH
8,0,0.002322,0,4,9.813084,LOW
9,1,0.972743,1,3,32.638889,HIGH
10,1,0.985968,1,3,32.638889,HIGH
11,1,0.708711,1,4,9.813084,LOW
12,0,0.000731,0,3,32.638889,HIGH
13,1,0.938479,1,3,32.638889,HIGH
14,1,0.798814,1,1,89.887640,VERY HIGH
15,1,0.186487,0,3,32.638889,HIGH
16,0,0.002709,0,3,32.638889,HIGH
17,0,0.002091,0,3,32.638889,HIGH
18,0,0.002091,0,3,32.638889,HIGH
19,0,0.000790,0,4,9.813084,LOW

In [17]:
# ============================================================
# STEP 15 — VERIFY LAYERING DATASET
# ============================================================

import pandas as pd
import os
import numpy as np

PATH = os.path.join(
    "data",
    "layering_dataset.csv"
)

layer_df = pd.read_csv(PATH)

print("=" * 70)
print("LAYERING DATASET")
print("=" * 70)

print("Shape:", layer_df.shape)

print("\nColumns:")
print(list(layer_df.columns))

# ------------------------------------------------------------
# Required columns
# ------------------------------------------------------------

required = [
    "master_row_id",
    "event_date",
    "state",
    "district",
    "latitude",
    "longitude",
    "landslide_occurred",
    "xgb_probability",
    "xgb_prediction",
    "ahc_cluster",
    "ahc_susceptibility",
    "ahc_category"
]

missing = [
    c for c in required
    if c not in layer_df.columns
]

print("\n" + "=" * 70)
print("COLUMN CHECK")
print("=" * 70)

if missing:
    print("❌ Missing:", missing)
else:
    print("✅ All required layering columns present.")

# ------------------------------------------------------------
# Missing model outputs
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MODEL OUTPUT CHECK")
print("=" * 70)

for col in [
    "xgb_probability",
    "xgb_prediction",
    "ahc_cluster",
    "ahc_susceptibility",
    "ahc_category"
]:

    n_missing = layer_df[col].isna().sum()

    print(
        f"{col:25s}: "
        f"{n_missing} missing"
    )

# ------------------------------------------------------------
# Probability ranges
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("XGBOOST PROBABILITY RANGE")
print("=" * 70)

print(
    "Minimum:",
    layer_df["xgb_probability"].min()
)

print(
    "Maximum:",
    layer_df["xgb_probability"].max()
)

# ------------------------------------------------------------
# AHC susceptibility range
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("AHC SUSCEPTIBILITY RANGE")
print("=" * 70)

print(
    "Minimum:",
    layer_df["ahc_susceptibility"].min()
)

print(
    "Maximum:",
    layer_df["ahc_susceptibility"].max()
)

# ------------------------------------------------------------
# Check probability validity
# ------------------------------------------------------------

invalid_xgb = (
    (layer_df["xgb_probability"] < 0)
    |
    (layer_df["xgb_probability"] > 1)
).sum()

invalid_ahc = (
    (layer_df["ahc_susceptibility"] < 0)
    |
    (layer_df["ahc_susceptibility"] > 100)
).sum()

print("\n" + "=" * 70)
print("VALIDITY CHECK")
print("=" * 70)

print(
    "Invalid XGBoost probabilities:",
    invalid_xgb
)

print(
    "Invalid AHC susceptibilities:",
    invalid_ahc
)

# ------------------------------------------------------------
# Target check
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TARGET")
print("=" * 70)

print(
    layer_df["landslide_occurred"]
    .value_counts()
)

# ------------------------------------------------------------
# Duplicate ID check
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("ROW ID CHECK")
print("=" * 70)

duplicates = layer_df["master_row_id"].duplicated().sum()

print(
    "Duplicate master_row_id:",
    duplicates
)

# ------------------------------------------------------------
# Final result
# ------------------------------------------------------------

if (
    not missing
    and layer_df[
        [
            "xgb_probability",
            "xgb_prediction",
            "ahc_cluster",
            "ahc_susceptibility",
            "ahc_category"
        ]
    ].notna().all().all()
    and invalid_xgb == 0
    and invalid_ahc == 0
    and duplicates == 0
):

    print("\n✅ LAYERING DATASET PASSED BASIC VALIDATION.")

else:

    print("\n❌ LAYERING DATASET NEEDS ATTENTION.")

======================================================================
LAYERING DATASET
======================================================================
Shape: (2016, 12)

Columns:
['master_row_id', 'event_date', 'state', 'district', 'latitude', 'longitude', 'landslide_occurred', 'xgb_probability', 'xgb_prediction', 'ahc_cluster', 'ahc_susceptibility', 'ahc_category']

======================================================================
COLUMN CHECK
======================================================================
✅ All required layering columns present.

======================================================================
MODEL OUTPUT CHECK
======================================================================
xgb_probability          : 0 missing
xgb_prediction           : 0 missing
ahc_cluster              : 0 missing
ahc_susceptibility       : 0 missing
ahc_category             : 0 missing

======================================================================
XGBOOST PROBABILITY RANGE
======================================================================
Minimum: 0.0006848736
Maximum: 0.99256563

======================================================================
AHC SUSCEPTIBILITY RANGE
======================================================================
Minimum: 0.0
Maximum: 92.2077922077922

======================================================================
VALIDITY CHECK
======================================================================
Invalid XGBoost probabilities: 0
Invalid AHC susceptibilities: 0

======================================================================
TARGET
======================================================================
landslide_occurred
0    1344
1     672
Name: count, dtype: int64

======================================================================
ROW ID CHECK
======================================================================
Duplicate master_row_id: 0

✅ LAYERING DATASET PASSED BASIC VALIDATION.

In [18]:
# ============================================================
# STEP 16 — CREATE LEAKAGE-SAFE PRELIMINARY META DATASET
# ============================================================

import pandas as pd
import os

# ------------------------------------------------------------
# Load layering dataset
# ------------------------------------------------------------

layer_df = pd.read_csv(
    "data/layering_dataset.csv"
)

# ------------------------------------------------------------
# Load the ORIGINAL XGBoost training subset
# ------------------------------------------------------------

xgb_train_df = pd.read_csv(
    "data/Landslide_NER_XGBOOST_TRAIN_1278.csv"
)

# ------------------------------------------------------------
# Identify rows used to train XGBoost
# ------------------------------------------------------------

train_ids = set(
    xgb_train_df["master_row_id"]
)

print("=" * 70)
print("XGBOOST TRAINING ROWS")
print("=" * 70)

print(
    "Rows used for XGBoost training:",
    len(train_ids)
)

# ------------------------------------------------------------
# Remove those rows from meta-model training
# ------------------------------------------------------------

meta_df = layer_df[
    ~layer_df["master_row_id"].isin(train_ids)
].copy()

meta_df = meta_df.reset_index(drop=True)

# ------------------------------------------------------------
# Check
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PRELIMINARY META DATASET")
print("=" * 70)

print(
    "Original layering rows:",
    len(layer_df)
)

print(
    "Removed XGBoost training rows:",
    len(train_ids)
)

print(
    "Remaining rows:",
    len(meta_df)
)

print("\nTarget distribution:")
print(
    meta_df["landslide_occurred"]
    .value_counts()
)

print("\nTarget percentage:")
print(
    meta_df["landslide_occurred"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

# ------------------------------------------------------------
# Verify no training-row leakage
# ------------------------------------------------------------

remaining_training_ids = (
    set(meta_df["master_row_id"])
    & train_ids
)

print("\n" + "=" * 70)
print("LEAKAGE CHECK")
print("=" * 70)

print(
    "XGBoost training IDs remaining:",
    len(remaining_training_ids)
)

if len(remaining_training_ids) == 0:
    print("✅ No XGBoost training rows remain.")
else:
    print("❌ Leakage detected.")

# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

OUTPUT = os.path.join(
    "data",
    "decision_model_preliminary_dataset.csv"
)

meta_df.to_csv(
    OUTPUT,
    index=False
)

print("\nSaved:")
print(OUTPUT)

======================================================================
XGBOOST TRAINING ROWS
======================================================================
Rows used for XGBoost training: 1278

======================================================================
PRELIMINARY META DATASET
======================================================================
Original layering rows: 2016
Removed XGBoost training rows: 1278
Remaining rows: 738

Target distribution:
landslide_occurred
0    519
1    219
Name: count, dtype: int64

Target percentage:
landslide_occurred
0    70.33
1    29.67
Name: proportion, dtype: float64

======================================================================
LEAKAGE CHECK
======================================================================
XGBoost training IDs remaining: 0
✅ No XGBoost training rows remain.

Saved:
data\decision_model_preliminary_dataset.csv

In [19]:
import pandas as pd

df = pd.read_csv(
    "data/Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv"
)

df["event_date"] = pd.to_datetime(df["event_date"])

print("=" * 70)
print("YEAR DISTRIBUTION")
print("=" * 70)

print(df["event_date"].dt.year.value_counts().sort_index())

print("\n" + "=" * 70)
print("DATE RANGE")
print("=" * 70)

print("Minimum:", df["event_date"].min())
print("Maximum:", df["event_date"].max())

print("\n" + "=" * 70)
print("ROWS PER YEAR + TARGET")
print("=" * 70)

print(
    pd.crosstab(
        df["event_date"].dt.year,
        df["landslide_occurred"]
    )
)

print("\n" + "=" * 70)
print("XGBOOST TRAINING ROW DATE RANGE")
print("=" * 70)

train = pd.read_csv(
    "data/Landslide_NER_XGBOOST_TRAIN_1278.csv"
)

train["event_date"] = pd.to_datetime(train["event_date"])

print("Minimum:", train["event_date"].min())
print("Maximum:", train["event_date"].max())

print("\nRows per year:")
print(
    train["event_date"].dt.year.value_counts().sort_index()
)

======================================================================
YEAR DISTRIBUTION
======================================================================
event_date
2023     211
2024     642
2025    1026
2026     137
Name: count, dtype: int64

======================================================================
DATE RANGE
======================================================================
Minimum: 2023-01-12 00:00:00
Maximum: 2026-04-10 00:00:00

======================================================================
ROWS PER YEAR + TARGET
======================================================================
landslide_occurred    0    1
event_date
2023                126   85
2024                419  223
2025                662  364
2026                137    0

======================================================================
XGBOOST TRAINING ROW DATE RANGE
======================================================================
Minimum: 2023-01-12 00:00:00
Maximum: 2025-05-31 00:00:00

Rows per year:
event_date
2023    211
2024    642
2025    425
Name: count, dtype: int64

In [20]:
# ============================================================
# STEP 17 — CREATE TEMPORAL + LEAKAGE-SAFE
#            DECISION MODEL TRAINING DATA
# ============================================================

import pandas as pd
import os

# ------------------------------------------------------------
# LOAD LAYERING DATASET
# ------------------------------------------------------------

layer_df = pd.read_csv(
    "data/layering_dataset.csv"
)

layer_df["event_date"] = pd.to_datetime(
    layer_df["event_date"]
)

# ------------------------------------------------------------
# LOAD ORIGINAL XGBOOST TRAINING ROW IDs
# ------------------------------------------------------------

xgb_train = pd.read_csv(
    "data/Landslide_NER_XGBOOST_TRAIN_1278.csv"
)

xgb_train_ids = set(
    xgb_train["master_row_id"]
)

# ------------------------------------------------------------
# CREATE YEAR
# ------------------------------------------------------------

layer_df["year"] = (
    layer_df["event_date"].dt.year
)

# ------------------------------------------------------------
# DECISION MODEL TRAINING DATA
#
# Conditions:
#
# 1. 2023–2024 only
# 2. Must NOT have been used to train XGBoost
# ------------------------------------------------------------

decision_train = layer_df[
    layer_df["year"].isin([2023, 2024])
    &
    ~layer_df["master_row_id"].isin(xgb_train_ids)
].copy()

decision_train = decision_train.reset_index(
    drop=True
)

# ------------------------------------------------------------
# INDEPENDENT 2025 TEST
# ------------------------------------------------------------

decision_test_2025 = layer_df[
    layer_df["year"] == 2025
].copy()

decision_test_2025 = decision_test_2025.reset_index(
    drop=True
)

# ------------------------------------------------------------
# 2026 — COMPLETELY EXCLUDED
# ------------------------------------------------------------

future_2026 = layer_df[
    layer_df["year"] == 2026
].copy()

# ------------------------------------------------------------
# REPORT
# ------------------------------------------------------------

print("=" * 70)
print("DECISION MODEL TRAINING SET")
print("=" * 70)

print(
    "Rows:",
    len(decision_train)
)

print("\nYears:")
print(
    decision_train["year"]
    .value_counts()
    .sort_index()
)

print("\nTarget:")
print(
    decision_train["landslide_occurred"]
    .value_counts()
)

print("\nTarget percentage:")
print(
    decision_train["landslide_occurred"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

# ------------------------------------------------------------

print("\n" + "=" * 70)
print("INDEPENDENT 2025 TEST")
print("=" * 70)

print(
    "Rows:",
    len(decision_test_2025)
)

print("\nTarget:")
print(
    decision_test_2025["landslide_occurred"]
    .value_counts()
)

# ------------------------------------------------------------

print("\n" + "=" * 70)
print("2026 EXCLUDED")
print("=" * 70)

print(
    "Rows:",
    len(future_2026)
)

# ------------------------------------------------------------
# LEAKAGE CHECK
# ------------------------------------------------------------

training_ids = set(
    decision_train["master_row_id"]
)

test_ids = set(
    decision_test_2025["master_row_id"]
)

xgb_overlap = (
    training_ids
    &
    xgb_train_ids
)

train_test_overlap = (
    training_ids
    &
    test_ids
)

print("\n" + "=" * 70)
print("LEAKAGE CHECK")
print("=" * 70)

print(
    "Decision-training rows used in XGBoost training:",
    len(xgb_overlap)
)

print(
    "Decision-training rows also in 2025 test:",
    len(train_test_overlap)
)

if len(xgb_overlap) == 0:
    print("✅ No XGBoost-training leakage.")

if len(train_test_overlap) == 0:
    print("✅ No train/test overlap.")

# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

train_output = (
    "data/decision_model_training.csv"
)

test_output = (
    "data/decision_model_test_2025.csv"
)

decision_train.to_csv(
    train_output,
    index=False
)

decision_test_2025.to_csv(
    test_output,
    index=False
)

print("\n" + "=" * 70)
print("FILES SAVED")
print("=" * 70)

print(train_output)
print(test_output)

======================================================================
DECISION MODEL TRAINING SET
======================================================================
Rows: 0

Years:
Series([], Name: count, dtype: int64)

Target:
Series([], Name: count, dtype: int64)

Target percentage:
Series([], Name: proportion, dtype: float64)

======================================================================
INDEPENDENT 2025 TEST
======================================================================
Rows: 1026

Target:
landslide_occurred
0    662
1    364
Name: count, dtype: int64

======================================================================
2026 EXCLUDED
======================================================================
Rows: 137

======================================================================
LEAKAGE CHECK
======================================================================
Decision-training rows used in XGBoost training: 0
Decision-training rows also in 2025 test: 0
✅ No XGBoost-training leakage.
✅ No train/test overlap.

======================================================================
FILES SAVED
======================================================================
data/decision_model_training.csv
data/decision_model_test_2025.csv

In [21]:
# ============================================================
# STEP 18 — INSPECT FROZEN XGBOOST CONFIGURATION
# ============================================================

import xgboost as xgb
import json

MODEL_PATH = "models/STEP73_FROZEN_XGBOOST.json"

model = xgb.XGBClassifier()
model.load_model(MODEL_PATH)

booster = model.get_booster()

print("=" * 70)
print("XGBOOST CONFIGURATION")
print("=" * 70)

config = json.loads(
    booster.save_config()
)

print(json.dumps(config, indent=2))

print("\n" + "=" * 70)
print("MODEL PARAMETERS")
print("=" * 70)

params = model.get_params()

for key, value in params.items():
    print(f"{key}: {value}")

print("\n" + "=" * 70)
print("NUMBER OF TREES")
print("=" * 70)

print(
    "Booster trees:",
    booster.num_boosted_rounds()
)

======================================================================
XGBOOST CONFIGURATION
======================================================================
{
  "learner": {
    "generic_param": {
      "device": "cpu",
      "fail_on_invalid_gpu_id": "0",
      "n_jobs": "0",
      "nthread": "0",
      "random_state": "0",
      "rng_state": "0 1 6c078967 714acb41 48077044 93e7383e f0f54bb2 141f95dc c0acdbd4 3cb9cadc bee0c4d6 69cf1baf be4809b2 236b027d af7e05f 31775c8a 24635c82 e743115b bb25efca 11c1a1fb f2f13b1b af74288d d2718781 54dd0861 7f4fadf8 ac58e456 3f8f093e 812d391 379d1151 a4732e12 8787bc6e d35722bb 95fd2ab8 4bd56583 bd119e6c c2be5f89 8b028b96 75bf4589 176436ce 437fdd6d ace527c4 771ba747 e55774c8 1e8eb742 492e9f36 611a3fe0 6b19cf3 7fb5f70e d96a801b 663961a9 957e6f7a 50d1328b 705acaa6 e8d65318 38c53cdd d96e4868 ec30d56f b76effd5 7895ff0d e1ff0bf7 eab14b80 cdf0e5ec 48a09e89 51ed53e7 a7d22ffe 517ecaad 1c30021e 86e4e419 571d71eb f5fa2b97 8e1165aa 3dc038f b09deeb3 65e2e51e f6fafc85 31d35729 70255479 28368ba5 7bc36567 3324978d 63653ff1 65b9aa01 243a1252 76f51cad 73c05c30 cd9198aa 7dc2ac03 57e8ef21 60be77f8 6d289696 9bbb38ed 4de5da6 8362c8da 515cd595 ef877c2 fe6c11e9 6b9f4bb2 4b40a900 55fb36c7 63d69281 398e4ce4 26865a59 1dca4683 321eed16 16ae5016 b43b5f17 56e1c0b3 740e48a5 9afe6d20 a2b640d7 5c6c9177 52e789fd b4154cdc 349c2207 32002c35 632cce5c fba83025 a4295573 e51f2f0b beb0d69f f8e9b169 d60ab94b a05aa1e2 b182bddb bd1d0819 c287a624 56806ce1 550ed4df f8d6ca16 8175f7ca 5b9cca6a ba1c1fba f819fc1c c3060fc0 e2289375 c1265415 4bb8f336 b4a1643c 8803bb00 9d9ada55 b951b3df fd883bbe 4ce2b71f 53434d65 2bb40d04 a41c4725 474cf1f5 dc8309d7 d4c15538 9f8033dc 9c68452c ce6ae9bd 3376e68e 252cf49f 7dfe9a55 9e55d7bf a7d432d fe99965e fc9b184f 6345429b 52db162 b0a26e4b 6d19946f 32886e09 c0f53b31 13cc1d5f ecd86e21 9f41a611 854bb127 8cacb142 c3bd2eea c1d3398 f149b3a4 c94090 86e3897e ebc9a9b 5d62f2d7 b7d8551f ddb11a23 74ba6f53 765ece0e 661653a0 6ef7283b 9d9fe999 8b581ddf 2eca0dea b08fb80c 82951c41 5ac9022b 2a9c554f 227defe9 dc7258ac 6b5ba4cb 1fde1e73 ca128f21 e9d9ab2d d5be27ea 7ac070b2 3214265 756a3fa0 d85f444d 1f45b18f d16d9535 218fc519 1de224a9 1c75e87a 274402f0 37f7997f 5c4d86eb 502f7523 9456693c cd1bb449 e56fbc06 90d6dbce 32f8e452 249ff731 7cbcc02d a835e35 62b188c3 8788c765 937dcb7f cef22e2e 7f7d4d9f 224b2e35 62d698c9 63e54fc9 afa282ca 3692a1cb 10fc78fb 3370eec b4293002 6eeff0e7 cadf21a6 fa8c9402 8cb1ee4f bad53a4c 5275bfb2 4df06d8c e556ae8f b46fca2b d669b41d bdea1ec7 2b3891ab 72f2fc6a 6ddfda2b d4378d87 3427a0a 6acf80e9 96320480 fdb35a43 8acedc3a 1cfedb13 d54e9a7b 11f52a55 4db43187 f94240dd 39ec6696 7344c02f ee3a7128 7fcba9fa f32e640b e10dc02d cf87712c 484acf92 3f9e9107 e05cf7cc 5ff48cb5 83b3d80f 98ee332d 9a75998 f120b206 9b4dea08 9642b102 d008d611 408a182c 2a69fd4 61183b8 fe6e70ad f8a193bc 2e098272 e9ad7a12 8a3b42ce 23b48796 afe2c549 c919fab3 5938188d f4189c5a 4bd0513c 5954b331 b89f6311 dc6c42a1 10ccfd0d bba6cc45 d6119828 2c8d0d1d a775b298 e839e1ea 121ad316 8d260ed8 6dec872d 34dbe188 1129c3d5 561a4137 95bba17d 7aecaf4b 2c35c363 527b1241 e7127473 79a7e164 9c9dfb0e 430178f2 bf3c416 cfb623e6 354b792 43a78fd4 27e7bd44 9f931110 b8a65f57 59fb1ac7 24cf875d 84dc2df1 51a2d20 c159eee2 dd78a908 365e959b 8c9dfa6c 465aacac fce9b688 7cb2691f 3476881f ee754c85 79e4e829 d0a50114 5a4fbe60 6eff0693 b1fbae9 c6ea703d 2a4177c7 ef5ec1d5 baf800c1 c595a943 ac5f0795 c5aecee9 eb18dda9 d7156f6a abf326c6 b60930ae a1604137 52521845 c33bf831 ffd9af18 9d548a06 c65298f4 d53389d4 2afa7235 77606d4c 2ca455c5 31f451e 8325543c 2d816bdd 65d3d499 79803961 9feb044a 5afb39d3 83cd3346 e7409f41 4872878 d94330c7 b1f722c4 f386af8f 4e92fae 7045ef19 62332dec 5f3ff4f6 b514d5e9 95202a2e c37630d4 67a5554c 2ffbdddb 2d15bbe2 e64d13a6 416f0e96 59c09211 359431cf 22c86f2b 2abee078 c6b6c8da 41886020 63269789 4a09922d e43438e2 7531db4c 6622bbe9 e59b4c11 5e78a6a4 14b0da4 3c652740 8a9bdcd ee25986f ce5af02b 857e2958 485d7c13 90c596ac 62599239 5c1ea9ac 60a187d6 fc4da869 6caa2d69 f4893a0 6802dfb9 50e3bd32 7a7ef1ba c38f7363 93f6e67d 633be8b9 33354a37 f43eb853 b7918931 933c6dc1 b1e9aa92 a7675c74 ab7ca233 764f37fb 120be149 6f3ef475 33d4876d df4dc4ab f8847ff3 b44deb5c ed452bc3 d2f4046e eb9f15b0 34455c4f 97ecb3dc 2fb6c648 6f30c41b 4be549f6 dfcc5f28 68bc90ad c0852193 de6c4f88 8819c690 836d7b54 188cb0a9 1aab2569 6e69f52a 1c2ebeb5 b5731c28 ada29852 6ed8e951 f19fde52 224310b8 7d70125c 33960576 91564f54 fadc54b5 fb3cd396 514d3892 f6c2fec9 e4cea17d 6c642682 adb44e7c 53966784 68600648 893e8d9d 92d0f88c 75580fd8 67286370 b43db669 43e53d0c 9e780cf7 7aff3b80 2a1184bd 561d856a 8ff8e811 5deabc5a 36e604c3 26a13dcc 48438f5a f9dc43c6 6a8e2b99 70938cd9 5a7e2b1a ca95768a f32616f1 8ec915f 2cba3361 9e9c302c e2a9a20e 1f00e60a 38bc1ddc af3685b7 52039f55 16fdd211 d205fba3 7164e80f fd610d76 a1b0ee1a 1ce0c96a ea5f32c5 55250012 69283474 cc22511f eeb5fe03 84bb37f8 8ea7e19b d725e457 d7700b1f 12ea6008 e4142d25 c2927fc 3a86a46b c8092337 b5ddb985 6f747345 217cdfd7 dcef60d7 5b0ea9a9 492bd94e 9ac10532 be3dbdf8 c2dcbfab 21408752 f21e4765 b5f1c34a e0db9575 17d81f9c be72f69b f3822d6d 62adcc77 5036d2a0 aac04498 1ac77cd6 45cc883 1f7e38c5 a290d4d0 ec65af2 8f8b6593 2e50ad4f 83bca946 40e02df0 7e9f1b32 5cb9083d 240c5dcb b9fa637 c57104d4 370ef9f5 ee5fbccc c57946cf cf501ca1 ca5c0010 16db34a6 cc329da6 91d88142 f056406a 95e9c98 bc492224 632ad12b 79fa01c0 62d9fc54 6a5d0cb9 bb8c7ec9 49d5ab49 88ee1d9b cef79091 b0082dcf 9057c917 48d19480 5eafa21d 97cff345 c92cfc3d 7f6eb4b1 b62f7bac 13adebe3 e0f8dcd 3ba0a920 a0c4dbe0 2284b46b b5d57379 46064ca 497ddff6 af458db8 b75f76a8 65d0cd59 a6ad1e00 1169eb13 ff1bebc9 41b922fd 46a7abb8 591bc34a fe8431e5 8e25c80d 1960f73b 8e2d1f98 12ece414 ea10b237 176024d8 ce8e238d 6ffd075c 74faf08 b0535880 6ecd7fa3 85cf0f44 8cc77ef9 aa866e63 28c277a2 c42ce748 648b65f6 42516bd3 4790ee3b c7410944 9f90aa66 37febfd8 cb144a9d ad4200bc daa1fb5d 78ff7c7e 71e51784 499b76e3 d522db95 75dea9a 8ccffb2f b5b4302f 6b1a1930",
      "seed": "0",
      "seed_per_iteration": "0",
      "validate_parameters": "1"
    },
    "gradient_booster": {
      "dart_train_param": {
        "normalize_type": "tree",
        "one_drop": "0",
        "rate_drop": "0",
        "sample_type": "uniform",
        "skip_drop": "0"
      },
      "gbtree_model_param": {
        "num_parallel_tree": "1",
        "num_trees": "300"
      },
      "gbtree_train_param": {
        "process_type": "default",
        "tree_method": "auto",
        "updater": "grow_quantile_histmaker",
        "updater_seq": "grow_quantile_histmaker"
      },
      "name": "gbtree",
      "specified_updater": false,
      "tree_train_param": {
        "alpha": "0",
        "colsample_bylevel": "1",
        "colsample_bynode": "1",
        "colsample_bytree": "1",
        "eta": "0.300000012",
        "gamma": "0",
        "grow_policy": "depthwise",
        "interaction_constraints": "",
        "lambda": "1",
        "learning_rate": "0.300000012",
        "max_bin": "256",
        "max_cat_threshold": "64",
        "max_cat_to_onehot": "4",
        "max_delta_step": "0",
        "max_depth": "6",
        "max_leaves": "0",
        "min_child_weight": "1",
        "min_split_loss": "0",
        "monotone_constraints": "()",
        "refresh_leaf": "1",
        "reg_alpha": "0",
        "reg_lambda": "1",
        "sampling_method": "uniform",
        "sparse_threshold": "0.20000000000000001",
        "subsample": "1"
      },
      "updater": [
        {
          "hist_train_param": {
            "debug_synchronize": "0",
            "max_cached_hist_node": "18446744073709551615"
          },
          "name": "grow_quantile_histmaker"
        }
      ]
    },
    "learner_model_param": {
      "base_score": "[3.87985E-1]",
      "boost_from_average": "1",
      "num_class": "0",
      "num_feature": "12",
      "num_target": "1"
    },
    "learner_train_param": {
      "booster": "gbtree",
      "disable_default_eval_metric": "0",
      "multi_strategy": "one_output_per_tree",
      "objective": "binary:logistic"
    },
    "metrics": [],
    "objective": {
      "name": "binary:logistic",
      "reg_loss_param": {
        "scale_pos_weight": "1"
      }
    }
  },
  "version": [
    3,
    4,
    1
  ]
}

======================================================================
MODEL PARAMETERS
======================================================================
objective: binary:logistic
base_score: [0.387985]
booster: gbtree
callbacks: None
colsample_bylevel: None
colsample_bynode: None
colsample_bytree: None
device: None
early_stopping_rounds: None
enable_categorical: False
eval_metric: None
feature_types: ['float', 'float', 'float', 'float', 'float', 'float', 'float', 'float', 'float', 'float', 'float', 'float']
feature_weights: None
gamma: None
grow_policy: None
importance_type: None
interaction_constraints: None
learning_rate: None
max_bin: None
max_cat_threshold: None
max_cat_to_onehot: None
max_delta_step: None
max_depth: None
max_leaves: None
min_child_weight: None
missing: nan
monotone_constraints: None
multi_strategy: None
n_estimators: None
n_jobs: None
num_parallel_tree: None
random_state: None
reg_alpha: None
reg_lambda: None
sampling_method: None
scale_pos_weight: None
subsample: None
tree_method: None
validate_parameters: None
verbosity: None

======================================================================
NUMBER OF TREES
======================================================================
Booster trees: 300

In [22]:
# ============================================================
# STEP 18 — GENERATE OOF XGBOOST PREDICTIONS
#              FOR META-MODEL TRAINING
# ============================================================

import pandas as pd
import numpy as np
import xgboost as xgb
import os

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score


# ============================================================
# 1. LOAD MASTER DATA
# ============================================================

DATA_PATH = (
    "data/"
    "Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv"
)

df = pd.read_csv(DATA_PATH)

df["event_date"] = pd.to_datetime(
    df["event_date"]
)


# ============================================================
# 2. SELECT ONLY 2023–2024
# ============================================================

dev = df[
    df["event_date"].dt.year.isin([2023, 2024])
].copy()

dev = dev.reset_index(drop=True)

print("=" * 70)
print("OOF DEVELOPMENT DATA")
print("=" * 70)

print("Rows:", len(dev))

print("\nYears:")
print(
    dev["event_date"]
    .dt.year
    .value_counts()
    .sort_index()
)

print("\nTarget:")
print(
    dev["landslide_occurred"]
    .value_counts()
)


# ============================================================
# 3. XGBOOST FEATURES
# ============================================================

FEATURES = [
    "rzsm_1",
    "rzsm_2",
    "rzsm_3",
    "cumulative_rainfall_3d_mm",
    "_rzsm_mean_",
    "_rzsm_range_",
    "_rzsm_surface_deep_diff_",
    "_rain_rzsm_interaction_",
    "_previous_rzsm_",
    "_previous_rzsm_2_",
    "_previous_rzsm_3_",
    "_previous_rainfall_"
]

X = dev[FEATURES].copy()

y = dev["landslide_occurred"].astype(int)

X = X.apply(
    pd.to_numeric,
    errors="coerce"
)


# ============================================================
# 4. OOF ARRAY
# ============================================================

oof_probability = np.full(
    len(dev),
    np.nan
)


# ============================================================
# 5. STRATIFIED K-FOLD
# ============================================================

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=0
)


# ============================================================
# 6. GENERATE OOF PREDICTIONS
# ============================================================

for fold, (train_idx, valid_idx) in enumerate(
    skf.split(X, y),
    start=1
):

    print(
        f"\nTraining OOF fold {fold}/5..."
    )

    X_train = X.iloc[train_idx]
    y_train = y.iloc[train_idx]

    X_valid = X.iloc[valid_idx]

    # --------------------------------------------------------
    # Temporary XGBoost model
    # Matches frozen model configuration
    # --------------------------------------------------------

    model = xgb.XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.3,
        subsample=1.0,
        colsample_bytree=1.0,
        objective="binary:logistic",
        random_state=0,
        n_jobs=1,
        eval_metric="logloss"
    )

    model.fit(
        X_train,
        y_train
    )

    # --------------------------------------------------------
    # Predict ONLY on the held-out fold
    # --------------------------------------------------------

    oof_probability[valid_idx] = (
        model.predict_proba(X_valid)[:, 1]
    )


# ============================================================
# 7. VERIFY OOF COMPLETENESS
# ============================================================

missing_oof = np.isnan(
    oof_probability
).sum()

print("\n" + "=" * 70)
print("OOF COMPLETENESS")
print("=" * 70)

print(
    "Missing OOF predictions:",
    missing_oof
)

if missing_oof != 0:
    raise RuntimeError(
        "OOF predictions are incomplete."
    )


# ============================================================
# 8. OOF PERFORMANCE
# ============================================================

oof_auc = roc_auc_score(
    y,
    oof_probability
)

print("\n" + "=" * 70)
print("OOF XGBOOST PERFORMANCE")
print("=" * 70)

print(
    "OOF ROC-AUC:",
    round(oof_auc, 6)
)


# ============================================================
# 9. CREATE OOF DATASET
# ============================================================

oof_df = dev[
    [
        "master_row_id",
        "event_date",
        "state",
        "district",
        "latitude",
        "longitude",
        "landslide_occurred"
    ]
].copy()

oof_df["xgb_oof_probability"] = (
    oof_probability
)

oof_df["xgb_oof_prediction"] = (
    oof_probability >= 0.50
).astype(int)


# ============================================================
# 10. LOAD AHC OUTPUTS FROM EXISTING LAYERING DATASET
# ============================================================

layering_df = pd.read_csv(
    "data/layering_dataset.csv"
)

ahc_columns = [
    "master_row_id",
    "ahc_cluster",
    "ahc_susceptibility",
    "ahc_category"
]

ahc_part = layering_df[
    ahc_columns
].copy()


# ============================================================
# 11. MERGE AHC WITH OOF XGBOOST
# ============================================================

meta_train = oof_df.merge(
    ahc_part,
    on="master_row_id",
    how="left",
    validate="one_to_one"
)


# ============================================================
# 12. VERIFY
# ============================================================

print("\n" + "=" * 70)
print("META TRAINING DATA")
print("=" * 70)

print(
    "Rows:",
    len(meta_train)
)

print(
    "Missing AHC outputs:",
    meta_train[
        [
            "ahc_cluster",
            "ahc_susceptibility",
            "ahc_category"
        ]
    ].isna().sum().sum()
)

print("\nPreview:")

display(
    meta_train[
        [
            "master_row_id",
            "landslide_occurred",
            "xgb_oof_probability",
            "xgb_oof_prediction",
            "ahc_cluster",
            "ahc_susceptibility",
            "ahc_category"
        ]
    ].head(20)
)


# ============================================================
# 13. SAVE
# ============================================================

OUTPUT = (
    "data/decision_model_training_oof.csv"
)

meta_train.to_csv(
    OUTPUT,
    index=False
)

print("\n" + "=" * 70)
print("SAVED")
print("=" * 70)

print(OUTPUT)

======================================================================
OOF DEVELOPMENT DATA
======================================================================
Rows: 853

Years:
event_date
2023    211
2024    642
Name: count, dtype: int64

Target:
landslide_occurred
0    545
1    308
Name: count, dtype: int64

Training OOF fold 1/5...

Training OOF fold 2/5...

Training OOF fold 3/5...

Training OOF fold 4/5...

Training OOF fold 5/5...

======================================================================
OOF COMPLETENESS
======================================================================
Missing OOF predictions: 0

======================================================================
OOF XGBOOST PERFORMANCE
======================================================================
OOF ROC-AUC: 0.984332

======================================================================
META TRAINING DATA
======================================================================
Rows: 853
Missing AHC outputs: 0

Preview:

,master_row_id,landslide_occurred,xgb_oof_probability,xgb_oof_prediction,ahc_cluster,ahc_susceptibility,ahc_category
0,1,0,0.000004,0,4,9.813084,LOW
1,2,1,0.013949,0,4,9.813084,LOW
2,3,0,0.000065,0,4,9.813084,LOW
3,4,1,0.999218,1,4,9.813084,LOW
4,5,0,0.000005,0,3,32.638889,HIGH
5,6,0,0.000006,0,3,32.638889,HIGH
6,7,0,0.000016,0,4,9.813084,LOW
7,8,0,0.000005,0,3,32.638889,HIGH
8,9,0,0.000131,0,4,9.813084,LOW
9,10,1,0.998493,1,3,32.638889,HIGH
10,11,1,0.999931,1,3,32.638889,HIGH
11,12,1,0.805382,1,4,9.813084,LOW
12,13,0,0.000014,0,3,32.638889,HIGH
13,14,1,0.996260,1,3,32.638889,HIGH
14,15,1,0.984985,1,1,89.887640,VERY HIGH
15,16,1,0.306364,0,3,32.638889,HIGH
16,17,0,0.000018,0,3,32.638889,HIGH
17,18,0,0.000041,0,3,32.638889,HIGH
18,19,0,0.000041,0,3,32.638889,HIGH
19,20,0,0.000003,0,4,9.813084,LOW

======================================================================
SAVED
======================================================================
data/decision_model_training_oof.csv

In [23]:
# ============================================================
# STEP 20 — FINAL 2025 INDEPENDENT EVALUATION
# ============================================================

import pandas as pd
import numpy as np
import joblib
import os

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# ============================================================
# 1. LOAD 2025 TEST DATA
# ============================================================

TEST_PATH = "data/decision_model_test_2025.csv"

test_df = pd.read_csv(TEST_PATH)

print("=" * 70)
print("2025 INDEPENDENT TEST SET")
print("=" * 70)

print("Rows:", len(test_df))

y_test = test_df["landslide_occurred"].astype(int)

print("\nTarget distribution:")
print(y_test.value_counts())


# ============================================================
# 2. LOAD FINAL DECISION MODEL
# ============================================================

MODEL_PATH = "models/layered_decision_model.pkl"

decision_model = joblib.load(MODEL_PATH)

print("\nDecision Model loaded.")


# ============================================================
# 3. DECISION MODEL FEATURES
# ============================================================

DECISION_FEATURES = [
    "xgb_probability",
    "ahc_susceptibility",
    "ahc_cluster",
    "ahc_category"
]

X_decision = test_df[
    DECISION_FEATURES
].copy()

decision_probability = (
    decision_model
    .predict_proba(X_decision)[:, 1]
)

decision_prediction = (
    decision_probability >= 0.50
).astype(int)


# ============================================================
# 4. XGBOOST BASELINE
# ============================================================

xgb_probability = (
    test_df["xgb_probability"]
    .values
)

xgb_prediction = (
    xgb_probability >= 0.50
).astype(int)


# ============================================================
# 5. AHC BASELINE
#
# Use >=70% susceptibility as VERY HIGH.
# This is the operating point established in the AHC model.
# ============================================================

ahc_probability = (
    test_df["ahc_susceptibility"]
    .values / 100.0
)

ahc_prediction = (
    test_df["ahc_susceptibility"]
    >= 70.0
).astype(int)


# ============================================================
# 6. METRIC FUNCTION
# ============================================================

def calculate_metrics(
    y_true,
    probability,
    prediction
):

    return {
        "ROC-AUC":
            roc_auc_score(
                y_true,
                probability
            ),

        "PR-AUC":
            average_precision_score(
                y_true,
                probability
            ),

        "Accuracy":
            accuracy_score(
                y_true,
                prediction
            ),

        "Precision":
            precision_score(
                y_true,
                prediction,
                zero_division=0
            ),

        "Recall":
            recall_score(
                y_true,
                prediction,
                zero_division=0
            ),

        "F1":
            f1_score(
                y_true,
                prediction,
                zero_division=0
            )
    }


# ============================================================
# 7. CALCULATE RESULTS
# ============================================================

xgb_metrics = calculate_metrics(
    y_test,
    xgb_probability,
    xgb_prediction
)

ahc_metrics = calculate_metrics(
    y_test,
    ahc_probability,
    ahc_prediction
)

decision_metrics = calculate_metrics(
    y_test,
    decision_probability,
    decision_prediction
)


# ============================================================
# 8. COMPARISON TABLE
# ============================================================

comparison = pd.DataFrame(
    [
        xgb_metrics,
        ahc_metrics,
        decision_metrics
    ],
    index=[
        "XGBoost",
        "AHC",
        "Layered Decision Model"
    ]
)

print("\n" + "=" * 70)
print("2025 MODEL COMPARISON")
print("=" * 70)

display(
    comparison.round(4)
)


# ============================================================
# 9. CONFUSION MATRICES
# ============================================================

print("\n" + "=" * 70)
print("XGBOOST CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y_test,
        xgb_prediction
    )
)

print("\n" + "=" * 70)
print("AHC CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y_test,
        ahc_prediction
    )
)

print("\n" + "=" * 70)
print("LAYERED DECISION MODEL CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y_test,
        decision_prediction
    )
)


# ============================================================
# 10. DETAILED DECISION MODEL REPORT
# ============================================================

print("\n" + "=" * 70)
print("LAYERED MODEL CLASSIFICATION REPORT")
print("=" * 70)

print(
    classification_report(
        y_test,
        decision_prediction,
        zero_division=0
    )
)


# ============================================================
# 11. ADD FINAL PREDICTIONS TO TEST DATA
# ============================================================

test_results = test_df.copy()

test_results[
    "layered_probability"
] = decision_probability

test_results[
    "layered_prediction"
] = decision_prediction


# ============================================================
# 12. SAVE RESULTS
# ============================================================

OUTPUT = (
    "data/"
    "layered_model_2025_test_results.csv"
)

test_results.to_csv(
    OUTPUT,
    index=False
)

print("\n" + "=" * 70)
print("RESULTS SAVED")
print("=" * 70)

print(OUTPUT)


# ============================================================
# 13. IMPROVEMENT OVER XGBOOST
# ============================================================

print("\n" + "=" * 70)
print("LAYERING IMPROVEMENT")
print("=" * 70)

for metric in [
    "ROC-AUC",
    "PR-AUC",
    "Accuracy",
    "Precision",
    "Recall",
    "F1"
]:

    improvement = (
        decision_metrics[metric]
        -
        xgb_metrics[metric]
    )

    print(
        f"{metric:10s}: "
        f"{improvement:+.4f}"
    )

======================================================================
2025 INDEPENDENT TEST SET
======================================================================
Rows: 1026

Target distribution:
landslide_occurred
0    662
1    364
Name: count, dtype: int64

FileNotFoundError: [Errno 2] No such file or directory: 'models/layered_decision_model.pkl'

In [24]:
import os

print("Current directory:")
print(os.getcwd())

print("\nModels folder:")
print(os.listdir("models"))

print("\nDecision model exists:")
print(
    os.path.exists(
        "models/layered_decision_model.pkl"
    )
)

Current directory:
C:\Users\bubub\Downloads\MLLAYER

Models folder:
['AHC_Landslide_Model_README.md', 'ahc_landslide_susceptibility_model.pkl', 'STEP73_FROZEN_XGBOOST.json']

Decision model exists:
False

In [25]:
import os

os.makedirs("models", exist_ok=True)
os.makedirs("results", exist_ok=True)

print("✅ Output folders ready.")

✅ Output folders ready.

In [27]:
import pandas as pd
import numpy as np
import joblib
import os

In [28]:
# ============================================================
# STEP 19 — TRAIN FINAL LAYERED DECISION MODEL
# ============================================================

import pandas as pd
import numpy as np
import joblib

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# ============================================================
# 1. LOAD OOF META DATA
# ============================================================

DATA_PATH = "data/decision_model_training_oof.csv"

df = pd.read_csv(DATA_PATH)

print("=" * 70)
print("META-MODEL TRAINING DATA")
print("=" * 70)

print("Rows:", len(df))

# ============================================================
# 2. DEFINE META FEATURES
# ============================================================

NUMERIC_FEATURES = [
    "xgb_oof_probability",
    "ahc_susceptibility",
    "ahc_cluster"
]

CATEGORICAL_FEATURES = [
    "ahc_category"
]

FEATURES = (
    NUMERIC_FEATURES +
    CATEGORICAL_FEATURES
)

TARGET = "landslide_occurred"

X = df[FEATURES].copy()
y = df[TARGET].astype(int)

# ============================================================
# 3. VALIDATE DATA
# ============================================================

print("\n" + "=" * 70)
print("META FEATURE CHECK")
print("=" * 70)

print(X.isna().sum())

if X.isna().any().any():
    raise ValueError(
        "❌ Missing values found in Decision Model features."
    )

print("\nTarget distribution:")
print(y.value_counts())

# ============================================================
# 4. PREPROCESSOR
# ============================================================

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numeric",
            StandardScaler(),
            NUMERIC_FEATURES
        ),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            CATEGORICAL_FEATURES
        )
    ]
)

# ============================================================
# 5. DECISION MODEL
# ============================================================

decision_model = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),
        (
            "classifier",
            LogisticRegression(
                max_iter=2000,
                class_weight="balanced",
                random_state=0
            )
        )
    ]
)

# ============================================================
# 6. 5-FOLD VALIDATION OF META MODEL
# ============================================================

print("\n" + "=" * 70)
print("DECISION MODEL 5-FOLD VALIDATION")
print("=" * 70)

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=0
)

meta_oof_probability = np.zeros(
    len(df)
)

for fold, (train_idx, valid_idx) in enumerate(
    skf.split(X, y),
    start=1
):

    print(
        f"Training Decision Model fold "
        f"{fold}/5..."
    )

    fold_model = Pipeline(
        steps=[
            (
                "preprocessor",
                ColumnTransformer(
                    transformers=[
                        (
                            "numeric",
                            StandardScaler(),
                            NUMERIC_FEATURES
                        ),
                        (
                            "categorical",
                            OneHotEncoder(
                                handle_unknown="ignore"
                            ),
                            CATEGORICAL_FEATURES
                        )
                    ]
                )
            ),
            (
                "classifier",
                LogisticRegression(
                    max_iter=2000,
                    class_weight="balanced",
                    random_state=0
                )
            )
        ]
    )

    fold_model.fit(
        X.iloc[train_idx],
        y.iloc[train_idx]
    )

    meta_oof_probability[valid_idx] = (
        fold_model.predict_proba(
            X.iloc[valid_idx]
        )[:, 1]
    )

# ============================================================
# 7. META OOF PREDICTIONS
# ============================================================

meta_oof_prediction = (
    meta_oof_probability >= 0.50
).astype(int)

# ============================================================
# 8. METRICS
# ============================================================

roc_auc = roc_auc_score(
    y,
    meta_oof_probability
)

pr_auc = average_precision_score(
    y,
    meta_oof_probability
)

precision = precision_score(
    y,
    meta_oof_prediction,
    zero_division=0
)

recall = recall_score(
    y,
    meta_oof_prediction,
    zero_division=0
)

f1 = f1_score(
    y,
    meta_oof_prediction,
    zero_division=0
)

print("\n" + "=" * 70)
print("DECISION MODEL OOF PERFORMANCE")
print("=" * 70)

print(f"ROC-AUC   : {roc_auc:.6f}")
print(f"PR-AUC    : {pr_auc:.6f}")
print(f"Precision : {precision:.6f}")
print(f"Recall    : {recall:.6f}")
print(f"F1        : {f1:.6f}")

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y,
        meta_oof_prediction
    )
)

print("\nClassification Report:")
print(
    classification_report(
        y,
        meta_oof_prediction,
        zero_division=0
    )
)

# ============================================================
# 9. FIT FINAL META MODEL ON ALL 853 OOF ROWS
# ============================================================

print("\n" + "=" * 70)
print("TRAINING FINAL DECISION MODEL")
print("=" * 70)

decision_model.fit(
    X,
    y
)

print("✅ Final Decision Model trained.")

# ============================================================
# 10. SAVE DECISION MODEL
# ============================================================

MODEL_OUTPUT = (
    "models/layered_decision_model.pkl"
)

joblib.dump(
    decision_model,
    MODEL_OUTPUT
)

print("\n✅ Decision Model saved:")
print(MODEL_OUTPUT)

# ============================================================
# 11. SAVE META TRAINING RESULTS
# ============================================================

df["decision_oof_probability"] = (
    meta_oof_probability
)

df["decision_oof_prediction"] = (
    meta_oof_prediction
)

RESULT_OUTPUT = (
    "results/decision_model_oof_results.csv"
)

df.to_csv(
    RESULT_OUTPUT,
    index=False
)

print("\n✅ OOF results saved:")
print(RESULT_OUTPUT)

# ============================================================
# 12. EXTRACT LEARNED COEFFICIENTS
# ============================================================

final_preprocessor = (
    decision_model
    .named_steps["preprocessor"]
)

final_classifier = (
    decision_model
    .named_steps["classifier"]
)

feature_names = (
    final_preprocessor
    .get_feature_names_out()
)

coefficients = (
    final_classifier.coef_[0]
)

coef_df = pd.DataFrame({
    "feature": feature_names,
    "coefficient": coefficients
})

coef_df["absolute_effect"] = (
    coef_df["coefficient"].abs()
)

coef_df = coef_df.sort_values(
    "absolute_effect",
    ascending=False
)

print("\n" + "=" * 70)
print("DECISION MODEL LEARNED RELATIONSHIP")
print("=" * 70)

display(coef_df)

# ============================================================
# 13. FINAL FILE CHECK
# ============================================================

print("\n" + "=" * 70)
print("FILE VERIFICATION")
print("=" * 70)

print(
    "Decision model exists:",
    os.path.exists(MODEL_OUTPUT)
)

print(
    "OOF results exist:",
    os.path.exists(RESULT_OUTPUT)
)

print("\n" + "=" * 70)
print("STEP 19 COMPLETE")
print("=" * 70)

======================================================================
META-MODEL TRAINING DATA
======================================================================
Rows: 853

======================================================================
META FEATURE CHECK
======================================================================
xgb_oof_probability    0
ahc_susceptibility     0
ahc_cluster            0
ahc_category           0
dtype: int64

Target distribution:
landslide_occurred
0    545
1    308
Name: count, dtype: int64

======================================================================
DECISION MODEL 5-FOLD VALIDATION
======================================================================
Training Decision Model fold 1/5...
Training Decision Model fold 2/5...
Training Decision Model fold 3/5...
Training Decision Model fold 4/5...
Training Decision Model fold 5/5...

======================================================================
DECISION MODEL OOF PERFORMANCE
======================================================================
ROC-AUC   : 0.991803
PR-AUC    : 0.987829
Precision : 0.904321
Recall    : 0.951299
F1        : 0.927215

Confusion Matrix:
[[514  31]
 [ 15 293]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.94      0.96       545
           1       0.90      0.95      0.93       308

    accuracy                           0.95       853
   macro avg       0.94      0.95      0.94       853
weighted avg       0.95      0.95      0.95       853


======================================================================
TRAINING FINAL DECISION MODEL
======================================================================
✅ Final Decision Model trained.

✅ Decision Model saved:
models/layered_decision_model.pkl

✅ OOF results saved:
results/decision_model_oof_results.csv

======================================================================
DECISION MODEL LEARNED RELATIONSHIP
======================================================================

                               feature  coefficient  absolute_effect
0         numeric__xgb_oof_probability     2.752474         2.752474
1          numeric__ahc_susceptibility     2.083646         2.083646
4        categorical__ahc_category_LOW    -0.718082         0.718082
2                 numeric__ahc_cluster     0.543682         0.543682
3       categorical__ahc_category_HIGH     0.376215         0.376215
5  categorical__ahc_category_VERY HIGH     0.264566         0.264566

======================================================================
FILE VERIFICATION
======================================================================
Decision model exists: True
OOF results exist: True

======================================================================
STEP 19 COMPLETE
======================================================================

In [29]:
# ============================================================
# STEP 20 — FINAL INDEPENDENT 2025 EVALUATION
# ============================================================

import pandas as pd
import numpy as np
import joblib
import os

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# ============================================================
# 1. LOAD 2025 TEST
# ============================================================

TEST_PATH = (
    "data/decision_model_test_2025.csv"
)

test_df = pd.read_csv(TEST_PATH)

y_test = (
    test_df["landslide_occurred"]
    .astype(int)
)

print("=" * 70)
print("2025 INDEPENDENT TEST")
print("=" * 70)

print("Rows:", len(test_df))

print("\nTarget distribution:")
print(y_test.value_counts())


# ============================================================
# 2. LOAD TRAINED DECISION MODEL
# ============================================================

MODEL_PATH = (
    "models/layered_decision_model.pkl"
)

decision_model = joblib.load(
    MODEL_PATH
)

print("\n✅ Decision Model loaded.")


# ============================================================
# 3. DECISION MODEL PREDICTION
# ============================================================

DECISION_FEATURES = [
    "xgb_probability",
    "ahc_susceptibility",
    "ahc_cluster",
    "ahc_category"
]

X_decision = test_df[
    DECISION_FEATURES
].copy()

layered_probability = (
    decision_model
    .predict_proba(X_decision)[:, 1]
)

layered_prediction = (
    layered_probability >= 0.50
).astype(int)


# ============================================================
# 4. XGBOOST BASELINE
# ============================================================

xgb_probability = (
    test_df["xgb_probability"]
    .values
)

xgb_prediction = (
    xgb_probability >= 0.50
).astype(int)


# ============================================================
# 5. AHC BASELINE
# ============================================================

ahc_probability = (
    test_df["ahc_susceptibility"]
    .values / 100.0
)

ahc_prediction = (
    test_df["ahc_susceptibility"]
    >= 70.0
).astype(int)


# ============================================================
# 6. METRIC FUNCTION
# ============================================================

def evaluate_model(
    name,
    y_true,
    probability,
    prediction
):

    metrics = {
        "Model": name,

        "ROC-AUC":
            roc_auc_score(
                y_true,
                probability
            ),

        "PR-AUC":
            average_precision_score(
                y_true,
                probability
            ),

        "Accuracy":
            accuracy_score(
                y_true,
                prediction
            ),

        "Precision":
            precision_score(
                y_true,
                prediction,
                zero_division=0
            ),

        "Recall":
            recall_score(
                y_true,
                prediction,
                zero_division=0
            ),

        "F1":
            f1_score(
                y_true,
                prediction,
                zero_division=0
            )
    }

    return metrics


# ============================================================
# 7. EVALUATE ALL THREE
# ============================================================

xgb_result = evaluate_model(
    "XGBoost",
    y_test,
    xgb_probability,
    xgb_prediction
)

ahc_result = evaluate_model(
    "AHC",
    y_test,
    ahc_probability,
    ahc_prediction
)

layered_result = evaluate_model(
    "Layered Decision Model",
    y_test,
    layered_probability,
    layered_prediction
)


# ============================================================
# 8. COMPARISON TABLE
# ============================================================

comparison = pd.DataFrame([
    xgb_result,
    ahc_result,
    layered_result
])

print("\n" + "=" * 70)
print("FINAL 2025 MODEL COMPARISON")
print("=" * 70)

display(
    comparison.set_index("Model").round(4)
)


# ============================================================
# 9. CONFUSION MATRICES
# ============================================================

print("\n" + "=" * 70)
print("XGBOOST CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y_test,
        xgb_prediction
    )
)

print("\n" + "=" * 70)
print("AHC CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y_test,
        ahc_prediction
    )
)

print("\n" + "=" * 70)
print("LAYERED DECISION MODEL CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y_test,
        layered_prediction
    )
)


# ============================================================
# 10. LAYERED CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 70)
print("LAYERED MODEL CLASSIFICATION REPORT")
print("=" * 70)

print(
    classification_report(
        y_test,
        layered_prediction,
        zero_division=0
    )
)


# ============================================================
# 11. ADD PREDICTIONS TO 2025 DATA
# ============================================================

test_results = test_df.copy()

test_results[
    "layered_probability"
] = layered_probability

test_results[
    "layered_prediction"
] = layered_prediction


# ============================================================
# 12. SAVE FINAL RESULTS
# ============================================================

OUTPUT = (
    "results/layered_model_2025_test_results.csv"
)

test_results.to_csv(
    OUTPUT,
    index=False
)

print("\n" + "=" * 70)
print("FINAL RESULTS SAVED")
print("=" * 70)

print(OUTPUT)


# ============================================================
# 13. CALCULATE IMPROVEMENT OVER XGBOOST
# ============================================================

print("\n" + "=" * 70)
print("LAYERED MODEL - XGBOOST DIFFERENCE")
print("=" * 70)

for metric in [
    "ROC-AUC",
    "PR-AUC",
    "Accuracy",
    "Precision",
    "Recall",
    "F1"
]:

    difference = (
        layered_result[metric]
        -
        xgb_result[metric]
    )

    print(
        f"{metric:10s}: "
        f"{difference:+.6f}"
    )


# ============================================================
# 14. FINAL STATUS
# ============================================================

print("\n" + "=" * 70)
print("STEP 20 COMPLETE")
print("=" * 70)

print(
    "2025 rows evaluated:",
    len(test_df)
)

print(
    "2026 rows remain untouched:",
    137
)

======================================================================
2025 INDEPENDENT TEST
======================================================================
Rows: 1026

Target distribution:
landslide_occurred
0    662
1    364
Name: count, dtype: int64

✅ Decision Model loaded.

ValueError: columns are missing: {'xgb_oof_probability'}

In [30]:
# ============================================================
# STEP 20 — FINAL INDEPENDENT 2025 EVALUATION
# CORRECTED VERSION
# ============================================================

import pandas as pd
import numpy as np
import joblib
import os

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# ============================================================
# 1. LOAD 2025 TEST
# ============================================================

TEST_PATH = "data/decision_model_test_2025.csv"

test_df = pd.read_csv(TEST_PATH)

y_test = (
    test_df["landslide_occurred"]
    .astype(int)
)

print("=" * 70)
print("2025 INDEPENDENT TEST")
print("=" * 70)

print("Rows:", len(test_df))

print("\nTarget distribution:")
print(y_test.value_counts())


# ============================================================
# 2. LOAD TRAINED DECISION MODEL
# ============================================================

MODEL_PATH = "models/layered_decision_model.pkl"

decision_model = joblib.load(
    MODEL_PATH
)

print("\n✅ Decision Model loaded.")


# ============================================================
# 3. PREPARE 2025 FEATURES
#
# Decision Model was trained using:
#
# xgb_oof_probability
# ahc_susceptibility
# ahc_cluster
# ahc_category
#
# For the independent 2025 test, the corresponding
# XGBoost output is xgb_probability.
#
# We therefore rename ONLY the test feature in memory.
# The original CSV is not modified.
# ============================================================

X_decision = pd.DataFrame({
    "xgb_oof_probability":
        test_df["xgb_probability"],

    "ahc_susceptibility":
        test_df["ahc_susceptibility"],

    "ahc_cluster":
        test_df["ahc_cluster"],

    "ahc_category":
        test_df["ahc_category"]
})


# ============================================================
# 4. VERIFY EXACT FEATURE STRUCTURE
# ============================================================

print("\n" + "=" * 70)
print("DECISION MODEL INPUT")
print("=" * 70)

print(
    list(X_decision.columns)
)

print("\nMissing values:")

print(
    X_decision.isna().sum()
)

if X_decision.isna().any().any():

    raise ValueError(
        "❌ Missing values found in Decision Model input."
    )

# ============================================================
# 5. LAYERED MODEL PREDICTION
# ============================================================

layered_probability = (
    decision_model
    .predict_proba(X_decision)[:, 1]
)

layered_prediction = (
    layered_probability >= 0.50
).astype(int)

print(
    "\n✅ Layered predictions generated."
)


# ============================================================
# 6. XGBOOST BASELINE
# ============================================================

xgb_probability = (
    test_df["xgb_probability"]
    .values
)

xgb_prediction = (
    xgb_probability >= 0.50
).astype(int)


# ============================================================
# 7. AHC BASELINE
#
# AHC VERY HIGH threshold = >=70%
# ============================================================

ahc_probability = (
    test_df["ahc_susceptibility"]
    .values / 100.0
)

ahc_prediction = (
    test_df["ahc_susceptibility"]
    >= 70.0
).astype(int)


# ============================================================
# 8. METRIC FUNCTION
# ============================================================

def evaluate_model(
    name,
    y_true,
    probability,
    prediction
):

    return {
        "Model": name,

        "ROC-AUC":
            roc_auc_score(
                y_true,
                probability
            ),

        "PR-AUC":
            average_precision_score(
                y_true,
                probability
            ),

        "Accuracy":
            accuracy_score(
                y_true,
                prediction
            ),

        "Precision":
            precision_score(
                y_true,
                prediction,
                zero_division=0
            ),

        "Recall":
            recall_score(
                y_true,
                prediction,
                zero_division=0
            ),

        "F1":
            f1_score(
                y_true,
                prediction,
                zero_division=0
            )
    }


# ============================================================
# 9. EVALUATE XGBOOST
# ============================================================

xgb_result = evaluate_model(
    "XGBoost",
    y_test,
    xgb_probability,
    xgb_prediction
)


# ============================================================
# 10. EVALUATE AHC
# ============================================================

ahc_result = evaluate_model(
    "AHC",
    y_test,
    ahc_probability,
    ahc_prediction
)


# ============================================================
# 11. EVALUATE LAYERED MODEL
# ============================================================

layered_result = evaluate_model(
    "Layered Decision Model",
    y_test,
    layered_probability,
    layered_prediction
)


# ============================================================
# 12. FINAL COMPARISON
# ============================================================

comparison = pd.DataFrame([
    xgb_result,
    ahc_result,
    layered_result
])

print("\n" + "=" * 70)
print("FINAL 2025 MODEL COMPARISON")
print("=" * 70)

display(
    comparison
    .set_index("Model")
    .round(4)
)


# ============================================================
# 13. CONFUSION MATRICES
# ============================================================

print("\n" + "=" * 70)
print("XGBOOST CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y_test,
        xgb_prediction
    )
)

print("\n" + "=" * 70)
print("AHC CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y_test,
        ahc_prediction
    )
)

print("\n" + "=" * 70)
print("LAYERED DECISION MODEL CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y_test,
        layered_prediction
    )
)


# ============================================================
# 14. LAYERED CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 70)
print("LAYERED MODEL CLASSIFICATION REPORT")
print("=" * 70)

print(
    classification_report(
        y_test,
        layered_prediction,
        zero_division=0
    )
)


# ============================================================
# 15. SAVE INDIVIDUAL 2025 PREDICTIONS
# ============================================================

test_results = test_df.copy()

test_results[
    "layered_probability"
] = layered_probability

test_results[
    "layered_prediction"
] = layered_prediction


# ============================================================
# 16. SAVE FINAL RESULTS
# ============================================================

OUTPUT = (
    "results/layered_model_2025_test_results.csv"
)

test_results.to_csv(
    OUTPUT,
    index=False
)

print("\n" + "=" * 70)
print("FINAL RESULTS SAVED")
print("=" * 70)

print(OUTPUT)


# ============================================================
# 17. IMPROVEMENT OVER XGBOOST
# ============================================================

print("\n" + "=" * 70)
print("LAYERED MODEL − XGBOOST")
print("=" * 70)

for metric in [
    "ROC-AUC",
    "PR-AUC",
    "Accuracy",
    "Precision",
    "Recall",
    "F1"
]:

    difference = (
        layered_result[metric]
        -
        xgb_result[metric]
    )

    print(
        f"{metric:10s}: "
        f"{difference:+.6f}"
    )


# ============================================================
# 18. FINAL STATUS
# ============================================================

print("\n" + "=" * 70)
print("STEP 20 COMPLETE")
print("=" * 70)

print(
    "2025 rows evaluated:",
    len(test_df)
)

print(
    "2026 rows untouched:",
    137
)

======================================================================
2025 INDEPENDENT TEST
======================================================================
Rows: 1026

Target distribution:
landslide_occurred
0    662
1    364
Name: count, dtype: int64

✅ Decision Model loaded.

======================================================================
DECISION MODEL INPUT
======================================================================
['xgb_oof_probability', 'ahc_susceptibility', 'ahc_cluster', 'ahc_category']

Missing values:
xgb_oof_probability    0
ahc_susceptibility     0
ahc_cluster            0
ahc_category           0
dtype: int64

✅ Layered predictions generated.

======================================================================
FINAL 2025 MODEL COMPARISON
======================================================================

                        ROC-AUC  PR-AUC  Accuracy  Precision  Recall      F1
Model
XGBoost                  0.9939  0.9866    0.9669     0.9508  0.9560  0.9534
AHC                      0.9410  0.8756    0.9045     0.9524  0.7692  0.8511
Layered Decision Model   0.9980  0.9970    0.9795     0.9549  0.9890  0.9717

======================================================================
XGBOOST CONFUSION MATRIX
======================================================================
[[644  18]
 [ 16 348]]

======================================================================
AHC CONFUSION MATRIX
======================================================================
[[648  14]
 [ 84 280]]

======================================================================
LAYERED DECISION MODEL CONFUSION MATRIX
======================================================================
[[645  17]
 [  4 360]]

======================================================================
LAYERED MODEL CLASSIFICATION REPORT
======================================================================
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       662
           1       0.95      0.99      0.97       364

    accuracy                           0.98      1026
   macro avg       0.97      0.98      0.98      1026
weighted avg       0.98      0.98      0.98      1026


======================================================================
FINAL RESULTS SAVED
======================================================================
results/layered_model_2025_test_results.csv

======================================================================
LAYERED MODEL − XGBOOST
======================================================================
ROC-AUC   : +0.004075
PR-AUC    : +0.010377
Accuracy  : +0.012671
Precision : +0.004087
Recall    : +0.032967
F1        : +0.018235

======================================================================
STEP 20 COMPLETE
======================================================================
2025 rows evaluated: 1026
2026 rows untouched: 137

In [31]:
# ============================================================
# STEP 21 — ABLATION STUDY
# ============================================================

import pandas as pd
import numpy as np

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# ============================================================
# 1. LOAD OOF DEVELOPMENT DATA
# ============================================================

META_PATH = "data/decision_model_training_oof.csv"

meta_df = pd.read_csv(META_PATH)

print("=" * 70)
print("ABLATION DEVELOPMENT DATA")
print("=" * 70)

print("Rows:", len(meta_df))

y_meta = (
    meta_df["landslide_occurred"]
    .astype(int)
)


# ============================================================
# 2. LOAD 2025 INDEPENDENT TEST
# ============================================================

TEST_PATH = "data/decision_model_test_2025.csv"

test_df = pd.read_csv(TEST_PATH)

print("\n2025 test rows:", len(test_df))

y_test = (
    test_df["landslide_occurred"]
    .astype(int)
)


# ============================================================
# 3. HELPER FUNCTION
# ============================================================

def make_model(
    numeric_features,
    categorical_features=None
):

    if categorical_features is None:
        categorical_features = []

    transformers = []

    if len(numeric_features) > 0:

        transformers.append(
            (
                "numeric",
                StandardScaler(),
                numeric_features
            )
        )

    if len(categorical_features) > 0:

        transformers.append(
            (
                "categorical",
                OneHotEncoder(
                    handle_unknown="ignore"
                ),
                categorical_features
            )
        )

    preprocessor = ColumnTransformer(
        transformers=transformers
    )

    model = Pipeline(
        steps=[
            (
                "preprocessor",
                preprocessor
            ),
            (
                "classifier",
                LogisticRegression(
                    max_iter=2000,
                    class_weight="balanced",
                    random_state=0
                )
            )
        ]
    )

    return model


# ============================================================
# 4. DEFINE THE THREE ARCHITECTURES
# ============================================================

architectures = {

    "A_XGBoost_only": {
        "numeric": [
            "xgb_oof_probability"
        ],
        "categorical": []
    },

    "B_XGBoost_AHC_susceptibility": {
        "numeric": [
            "xgb_oof_probability",
            "ahc_susceptibility"
        ],
        "categorical": []
    },

    "C_Full_layering": {
        "numeric": [
            "xgb_oof_probability",
            "ahc_susceptibility",
            "ahc_cluster"
        ],
        "categorical": [
            "ahc_category"
        ]
    }
}


# ============================================================
# 5. TRAIN EACH META MODEL
# ============================================================

results = []

trained_models = {}

for name, config in architectures.items():

    print("\n" + "=" * 70)
    print("TRAINING:", name)
    print("=" * 70)

    numeric_features = config["numeric"]
    categorical_features = config["categorical"]

    features = (
        numeric_features +
        categorical_features
    )

    # --------------------------------------------------------
    # Development data
    # --------------------------------------------------------

    X_meta = meta_df[features].copy()

    # --------------------------------------------------------
    # Train model
    # --------------------------------------------------------

    model = make_model(
        numeric_features,
        categorical_features
    )

    model.fit(
        X_meta,
        y_meta
    )

    trained_models[name] = model

    # --------------------------------------------------------
    # Prepare 2025 test features
    #
    # Translate frozen XGBoost output into the
    # feature name expected by the meta model.
    # --------------------------------------------------------

    X_test = pd.DataFrame()

    if "xgb_oof_probability" in features:

        X_test[
            "xgb_oof_probability"
        ] = test_df[
            "xgb_probability"
        ]

    if "ahc_susceptibility" in features:

        X_test[
            "ahc_susceptibility"
        ] = test_df[
            "ahc_susceptibility"
        ]

    if "ahc_cluster" in features:

        X_test[
            "ahc_cluster"
        ] = test_df[
            "ahc_cluster"
        ]

    if "ahc_category" in features:

        X_test[
            "ahc_category"
        ] = test_df[
            "ahc_category"
        ]

    # --------------------------------------------------------
    # Predict
    # --------------------------------------------------------

    probability = (
        model.predict_proba(X_test)[:, 1]
    )

    prediction = (
        probability >= 0.50
    ).astype(int)

    # --------------------------------------------------------
    # Metrics
    # --------------------------------------------------------

    result = {

        "Model": name,

        "ROC-AUC":
            roc_auc_score(
                y_test,
                probability
            ),

        "PR-AUC":
            average_precision_score(
                y_test,
                probability
            ),

        "Accuracy":
            accuracy_score(
                y_test,
                prediction
            ),

        "Precision":
            precision_score(
                y_test,
                prediction,
                zero_division=0
            ),

        "Recall":
            recall_score(
                y_test,
                prediction,
                zero_division=0
            ),

        "F1":
            f1_score(
                y_test,
                prediction,
                zero_division=0
            )
    }

    results.append(result)

    print("\nResults:")

    for key, value in result.items():

        if key != "Model":

            print(
                f"{key:10s}: "
                f"{value:.6f}"
            )

    print("\nConfusion Matrix:")

    print(
        confusion_matrix(
            y_test,
            prediction
        )
    )


# ============================================================
# 6. COMPARISON TABLE
# ============================================================

comparison = pd.DataFrame(results)

print("\n" + "=" * 70)
print("ABLATION STUDY — 2025 INDEPENDENT TEST")
print("=" * 70)

display(
    comparison
    .set_index("Model")
    .round(6)
)


# ============================================================
# 7. IMPROVEMENT RELATIVE TO XGBOOST-ONLY META MODEL
# ============================================================

baseline = comparison[
    comparison["Model"] == "A_XGBoost_only"
].iloc[0]

print("\n" + "=" * 70)
print("INCREMENTAL CONTRIBUTION OF AHC")
print("=" * 70)

for _, row in comparison.iterrows():

    if row["Model"] == "A_XGBoost_only":
        continue

    print(
        "\n" + row["Model"]
    )

    for metric in [
        "ROC-AUC",
        "PR-AUC",
        "Accuracy",
        "Precision",
        "Recall",
        "F1"
    ]:

        difference = (
            row[metric]
            -
            baseline[metric]
        )

        print(
            f"{metric:10s}: "
            f"{difference:+.6f}"
        )


# ============================================================
# 8. SAVE ABLATION RESULTS
# ============================================================

ABLATION_OUTPUT = (
    "results/ablation_study_2025.csv"
)

comparison.to_csv(
    ABLATION_OUTPUT,
    index=False
)

print("\n" + "=" * 70)
print("ABLATION RESULTS SAVED")
print("=" * 70)

print(ABLATION_OUTPUT)


# ============================================================
# 9. DETERMINE BEST ARCHITECTURE
# ============================================================

best_index = comparison[
    "ROC-AUC"
].idxmax()

best_model = comparison.loc[
    best_index,
    "Model"
]

best_auc = comparison.loc[
    best_index,
    "ROC-AUC"
]

print("\n" + "=" * 70)
print("BEST ABLATION ARCHITECTURE")
print("=" * 70)

print(
    "Best model by ROC-AUC:",
    best_model
)

print(
    "ROC-AUC:",
    round(best_auc, 6)
)

print("\nSTEP 21 COMPLETE")

======================================================================
ABLATION DEVELOPMENT DATA
======================================================================
Rows: 853

2025 test rows: 1026

======================================================================
TRAINING: A_XGBoost_only
======================================================================

Results:
ROC-AUC   : 0.993937
PR-AUC    : 0.986574
Accuracy  : 0.970760
Precision : 0.948925
Recall    : 0.969780
F1        : 0.959239

Confusion Matrix:
[[643  19]
 [ 11 353]]

======================================================================
TRAINING: B_XGBoost_AHC_susceptibility
======================================================================

Results:
ROC-AUC   : 0.997618
PR-AUC    : 0.996274
Accuracy  : 0.961988
Precision : 0.922078
Recall    : 0.975275
F1        : 0.947931

Confusion Matrix:
[[632  30]
 [  9 355]]

======================================================================
TRAINING: C_Full_layering
======================================================================

Results:
ROC-AUC   : 0.998012
PR-AUC    : 0.996952
Accuracy  : 0.979532
Precision : 0.954907
Recall    : 0.989011
F1        : 0.971660

Confusion Matrix:
[[645  17]
 [  4 360]]

======================================================================
ABLATION STUDY — 2025 INDEPENDENT TEST
======================================================================

,ROC-AUC,PR-AUC,Accuracy,Precision,Recall,F1
Model,,,,,,
A_XGBoost_only,0.993937,0.986574,0.970760,0.948925,0.969780,0.959239
B_XGBoost_AHC_susceptibility,0.997618,0.996274,0.961988,0.922078,0.975275,0.947931
C_Full_layering,0.998012,0.996952,0.979532,0.954907,0.989011,0.971660

======================================================================
INCREMENTAL CONTRIBUTION OF AHC
======================================================================

B_XGBoost_AHC_susceptibility
ROC-AUC   : +0.003681
PR-AUC    : +0.009700
Accuracy  : -0.008772
Precision : -0.026847
Recall    : +0.005495
F1        : -0.011309

C_Full_layering
ROC-AUC   : +0.004075
PR-AUC    : +0.010377
Accuracy  : +0.008772
Precision : +0.005982
Recall    : +0.019231
F1        : +0.012421

======================================================================
ABLATION RESULTS SAVED
======================================================================
results/ablation_study_2025.csv

======================================================================
BEST ABLATION ARCHITECTURE
======================================================================
Best model by ROC-AUC: C_Full_layering
ROC-AUC: 0.998012

STEP 21 COMPLETE

In [32]:
# ============================================================
# STEP 22A — INSPECT SPATIAL REPETITION / GENERALIZATION
# ============================================================

import pandas as pd
import numpy as np

DATA_PATH = (
    "data/Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv"
)

df = pd.read_csv(DATA_PATH)

df["event_date"] = pd.to_datetime(
    df["event_date"]
)

print("=" * 70)
print("SPATIAL STRUCTURE OF DATASET")
print("=" * 70)

print("Total rows:", len(df))

# ============================================================
# 1. UNIQUE COORDINATE LOCATIONS
# ============================================================

df["location_key"] = (
    df["latitude"].round(6).astype(str)
    + "_"
    + df["longitude"].round(6).astype(str)
)

unique_locations = (
    df["location_key"].nunique()
)

print("\nUnique coordinate locations:")
print(unique_locations)

print(
    "Average observations per location:",
    round(
        len(df) / unique_locations,
        2
    )
)


# ============================================================
# 2. OBSERVATIONS PER LOCATION
# ============================================================

location_counts = (
    df["location_key"]
    .value_counts()
)

print("\n" + "=" * 70)
print("OBSERVATIONS PER LOCATION")
print("=" * 70)

print(
    location_counts.describe()
)


# ============================================================
# 3. LOCATIONS WITH MULTIPLE OBSERVATIONS
# ============================================================

multi_locations = (
    location_counts > 1
).sum()

single_locations = (
    location_counts == 1
).sum()

print("\nLocations with exactly 1 observation:")
print(single_locations)

print("\nLocations with >1 observation:")
print(multi_locations)


# ============================================================
# 4. DISTRICT STRUCTURE
# ============================================================

print("\n" + "=" * 70)
print("GEOGRAPHIC COVERAGE")
print("=" * 70)

print(
    "Unique states:",
    df["state"].nunique()
)

print(
    "Unique districts:",
    df["district"].nunique()
)

print(
    "Unique state-district combinations:",
    df[
        ["state", "district"]
    ].drop_duplicates().shape[0]
)


# ============================================================
# 5. YEAR × LOCATION OVERLAP
# ============================================================

df["year"] = (
    df["event_date"]
    .dt.year
)

location_year = (
    df.groupby("location_key")["year"]
    .nunique()
)

print("\n" + "=" * 70)
print("TEMPORAL LOCATION REPETITION")
print("=" * 70)

print(
    "Locations appearing in multiple years:",
    (location_year > 1).sum()
)

print(
    "Locations appearing in only one year:",
    (location_year == 1).sum()
)


# ============================================================
# 6. 2025 LOCATIONS SEEN BEFORE 2025
# ============================================================

locations_2025 = set(
    df.loc[
        df["year"] == 2025,
        "location_key"
    ]
)

locations_before_2025 = set(
    df.loc[
        df["year"] < 2025,
        "location_key"
    ]
)

seen_before = (
    locations_2025
    &
    locations_before_2025
)

new_in_2025 = (
    locations_2025
    -
    locations_before_2025
)

print("\n" + "=" * 70)
print("2025 LOCATION NOVELTY")
print("=" * 70)

print(
    "Unique locations in 2025:",
    len(locations_2025)
)

print(
    "2025 locations already seen before:",
    len(seen_before)
)

print(
    "2025 genuinely new locations:",
    len(new_in_2025)
)

if len(locations_2025) > 0:

    print(
        "\nPercentage of 2025 locations "
        "seen before:",
        round(
            100 *
            len(seen_before) /
            len(locations_2025),
            2
        ),
        "%"
    )


# ============================================================
# 7. 2025 ROW-LEVEL NOVELTY
# ============================================================

rows_2025 = df[
    df["year"] == 2025
].copy()

rows_2025["seen_before"] = (
    rows_2025["location_key"]
    .isin(locations_before_2025)
)

print("\n" + "=" * 70)
print("2025 ROW-LEVEL LOCATION NOVELTY")
print("=" * 70)

print(
    rows_2025["seen_before"]
    .value_counts()
)

print(
    "\nPercentage of 2025 rows from previously "
    "observed locations:"
)

print(
    round(
        100 *
        rows_2025["seen_before"].mean(),
        2
    ),
    "%"
)


# ============================================================
# 8. 2026 HOLDOUT
# ============================================================

rows_2026 = df[
    df["year"] == 2026
].copy()

print("\n" + "=" * 70)
print("2026 HOLDOUT")
print("=" * 70)

print(
    "2026 rows:",
    len(rows_2026)
)

print(
    "2026 unique locations:",
    rows_2026["location_key"].nunique()
)

locations_before_2026 = set(
    df.loc[
        df["year"] < 2026,
        "location_key"
    ]
)

locations_2026 = set(
    rows_2026["location_key"]
)

new_2026_locations = (
    locations_2026
    -
    locations_before_2026
)

print(
    "2026 locations not seen before:",
    len(new_2026_locations)
)

print("\n" + "=" * 70)
print("STEP 22A COMPLETE")
print("=" * 70)

======================================================================
SPATIAL STRUCTURE OF DATASET
======================================================================
Total rows: 2016

Unique coordinate locations:
656
Average observations per location: 3.07

======================================================================
OBSERVATIONS PER LOCATION
======================================================================
count    656.000000
mean       3.073171
std        0.519083
min        3.000000
25%        3.000000
50%        3.000000
75%        3.000000
max        9.000000
Name: count, dtype: float64

Locations with exactly 1 observation:
0

Locations with >1 observation:
656

======================================================================
GEOGRAPHIC COVERAGE
======================================================================
Unique states: 8
Unique districts: 99
Unique state-district combinations: 99

======================================================================
TEMPORAL LOCATION REPETITION
======================================================================
Locations appearing in multiple years: 252
Locations appearing in only one year: 404

======================================================================
2025 LOCATION NOVELTY
======================================================================
Unique locations in 2025: 424
2025 locations already seen before: 71
2025 genuinely new locations: 353

Percentage of 2025 locations seen before: 16.75 %

======================================================================
2025 ROW-LEVEL LOCATION NOVELTY
======================================================================
seen_before
False    955
True      71
Name: count, dtype: int64

Percentage of 2025 rows from previously observed locations:
6.92 %

======================================================================
2026 HOLDOUT
======================================================================
2026 rows: 137
2026 unique locations: 134
2026 locations not seen before: 0

======================================================================
STEP 22A COMPLETE
======================================================================

In [33]:
# ============================================================
# STEP 22B — STRICT UNSEEN-LOCATION 2025 ROBUSTNESS TEST
# ============================================================

import pandas as pd
import numpy as np
import joblib

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# ============================================================
# 1. LOAD FULL DATASET
# ============================================================

MASTER_PATH = (
    "data/Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv"
)

master = pd.read_csv(MASTER_PATH)

master["event_date"] = pd.to_datetime(
    master["event_date"]
)

master["year"] = master["event_date"].dt.year

# ============================================================
# 2. CREATE LOCATION KEY
# ============================================================

master["location_key"] = (
    master["latitude"].round(6).astype(str)
    + "_"
    + master["longitude"].round(6).astype(str)
)

# ============================================================
# 3. DEFINE DEVELOPMENT LOCATIONS
#
# These are locations represented during 2023–2024.
# ============================================================

development_locations = set(
    master.loc[
        master["year"].isin([2023, 2024]),
        "location_key"
    ]
)

# ============================================================
# 4. SELECT STRICTLY UNSEEN 2025 LOCATIONS
# ============================================================

test_2025 = master[
    master["year"] == 2025
].copy()

unseen_2025 = test_2025[
    ~test_2025["location_key"]
    .isin(development_locations)
].copy()

unseen_2025 = unseen_2025.reset_index(
    drop=True
)

print("=" * 70)
print("STRICT UNSEEN-LOCATION 2025 TEST")
print("=" * 70)

print(
    "Total 2025 rows:",
    len(test_2025)
)

print(
    "Strictly unseen-location rows:",
    len(unseen_2025)
)

print(
    "Unique unseen locations:",
    unseen_2025["location_key"].nunique()
)

print("\nTarget distribution:")

print(
    unseen_2025[
        "landslide_occurred"
    ].value_counts()
)


# ============================================================
# 5. LOAD EXISTING LAYERING RESULTS
# ============================================================

layering_path = (
    "data/layering_dataset.csv"
)

layering = pd.read_csv(
    layering_path
)

# ============================================================
# 6. MERGE MODEL OUTPUTS
# ============================================================

required_outputs = [
    "master_row_id",
    "xgb_probability",
    "xgb_prediction",
    "ahc_cluster",
    "ahc_susceptibility",
    "ahc_category"
]

layering_subset = layering[
    required_outputs
].copy()

# If master_row_id is absent in the raw master,
# use row matching through available IDs where applicable.
# First check:

if "master_row_id" in unseen_2025.columns:

    unseen_eval = unseen_2025.merge(
        layering_subset,
        on="master_row_id",
        how="left",
        validate="one_to_one"
    )

else:

    raise ValueError(
        "master_row_id is required for safe model-output alignment."
    )


# ============================================================
# 7. CHECK MODEL OUTPUTS
# ============================================================

model_columns = [
    "xgb_probability",
    "xgb_prediction",
    "ahc_cluster",
    "ahc_susceptibility",
    "ahc_category"
]

missing = (
    unseen_eval[model_columns]
    .isna()
    .sum()
)

print("\n" + "=" * 70)
print("MODEL OUTPUT CHECK")
print("=" * 70)

print(missing)

if missing.sum() != 0:

    raise ValueError(
        "Missing model outputs detected."
    )


# ============================================================
# 8. LOAD DECISION MODEL
# ============================================================

decision_model = joblib.load(
    "models/layered_decision_model.pkl"
)

print(
    "\n✅ Layered Decision Model loaded."
)


# ============================================================
# 9. PREPARE DECISION FEATURES
# ============================================================

X_decision = pd.DataFrame({

    "xgb_oof_probability":
        unseen_eval[
            "xgb_probability"
        ],

    "ahc_susceptibility":
        unseen_eval[
            "ahc_susceptibility"
        ],

    "ahc_cluster":
        unseen_eval[
            "ahc_cluster"
        ],

    "ahc_category":
        unseen_eval[
            "ahc_category"
        ]
})


# ============================================================
# 10. LAYERED PREDICTION
# ============================================================

layered_probability = (
    decision_model
    .predict_proba(
        X_decision
    )[:, 1]
)

layered_prediction = (
    layered_probability >= 0.50
).astype(int)


# ============================================================
# 11. XGBOOST
# ============================================================

xgb_probability = (
    unseen_eval[
        "xgb_probability"
    ].values
)

xgb_prediction = (
    xgb_probability >= 0.50
).astype(int)


# ============================================================
# 12. AHC
# ============================================================

ahc_probability = (
    unseen_eval[
        "ahc_susceptibility"
    ].values / 100.0
)

ahc_prediction = (
    unseen_eval[
        "ahc_susceptibility"
    ] >= 70.0
).astype(int)


# ============================================================
# 13. TARGET
# ============================================================

y = (
    unseen_eval[
        "landslide_occurred"
    ].astype(int)
)


# ============================================================
# 14. EVALUATION FUNCTION
# ============================================================

def evaluate(
    name,
    y_true,
    probability,
    prediction
):

    return {

        "Model": name,

        "ROC-AUC":
            roc_auc_score(
                y_true,
                probability
            ),

        "PR-AUC":
            average_precision_score(
                y_true,
                probability
            ),

        "Accuracy":
            accuracy_score(
                y_true,
                prediction
            ),

        "Precision":
            precision_score(
                y_true,
                prediction,
                zero_division=0
            ),

        "Recall":
            recall_score(
                y_true,
                prediction,
                zero_division=0
            ),

        "F1":
            f1_score(
                y_true,
                prediction,
                zero_division=0
            )
    }


# ============================================================
# 15. COMPARE MODELS
# ============================================================

results = pd.DataFrame([

    evaluate(
        "XGBoost",
        y,
        xgb_probability,
        xgb_prediction
    ),

    evaluate(
        "AHC",
        y,
        ahc_probability,
        ahc_prediction
    ),

    evaluate(
        "Layered Decision Model",
        y,
        layered_probability,
        layered_prediction
    )
])


# ============================================================
# 16. DISPLAY RESULTS
# ============================================================

print("\n" + "=" * 70)
print("UNSEEN-LOCATION 2025 RESULTS")
print("=" * 70)

display(
    results
    .set_index("Model")
    .round(6)
)


# ============================================================
# 17. CONFUSION MATRICES
# ============================================================

print("\n" + "=" * 70)
print("XGBOOST CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y,
        xgb_prediction
    )
)

print("\n" + "=" * 70)
print("AHC CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y,
        ahc_prediction
    )
)

print("\n" + "=" * 70)
print("LAYERED CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y,
        layered_prediction
    )
)


# ============================================================
# 18. LAYERED CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 70)
print("LAYERED CLASSIFICATION REPORT")
print("=" * 70)

print(
    classification_report(
        y,
        layered_prediction,
        zero_division=0
    )
)


# ============================================================
# 19. SAVE ROBUSTNESS RESULTS
# ============================================================

unseen_eval[
    "layered_probability"
] = layered_probability

unseen_eval[
    "layered_prediction"
] = layered_prediction

OUTPUT = (
    "results/"
    "unseen_location_2025_test_results.csv"
)

unseen_eval.to_csv(
    OUTPUT,
    index=False
)

results.to_csv(
    "results/"
    "unseen_location_2025_model_comparison.csv",
    index=False
)

print("\n" + "=" * 70)
print("ROBUSTNESS RESULTS SAVED")
print("=" * 70)

print(
    "Row-level results:",
    OUTPUT
)

print(
    "Model comparison:",
    "results/unseen_location_2025_model_comparison.csv"
)

print("\n" + "=" * 70)
print("STEP 22B COMPLETE")
print("=" * 70)

======================================================================
STRICT UNSEEN-LOCATION 2025 TEST
======================================================================
Total 2025 rows: 1026
Strictly unseen-location rows: 955
Unique unseen locations: 353

Target distribution:
landslide_occurred
0    591
1    364
Name: count, dtype: int64

======================================================================
MODEL OUTPUT CHECK
======================================================================
xgb_probability       0
xgb_prediction        0
ahc_cluster           0
ahc_susceptibility    0
ahc_category          0
dtype: int64

✅ Layered Decision Model loaded.

======================================================================
UNSEEN-LOCATION 2025 RESULTS
======================================================================

,ROC-AUC,PR-AUC,Accuracy,Precision,Recall,F1
Model,,,,,,
XGBoost,0.993966,0.987686,0.967539,0.958678,0.956044,0.957359
AHC,0.939918,0.881170,0.897382,0.952381,0.769231,0.851064
Layered Decision Model,0.998429,0.997877,0.982199,0.965147,0.989011,0.976934

======================================================================
XGBOOST CONFUSION MATRIX
======================================================================
[[576  15]
 [ 16 348]]

======================================================================
AHC CONFUSION MATRIX
======================================================================
[[577  14]
 [ 84 280]]

======================================================================
LAYERED CONFUSION MATRIX
======================================================================
[[578  13]
 [  4 360]]

======================================================================
LAYERED CLASSIFICATION REPORT
======================================================================
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       591
           1       0.97      0.99      0.98       364

    accuracy                           0.98       955
   macro avg       0.98      0.98      0.98       955
weighted avg       0.98      0.98      0.98       955


======================================================================
ROBUSTNESS RESULTS SAVED
======================================================================
Row-level results: results/unseen_location_2025_test_results.csv
Model comparison: results/unseen_location_2025_model_comparison.csv

======================================================================
STEP 22B COMPLETE
======================================================================

In [34]:
# ============================================================
# STEP 23 — CALIBRATION / WARNING THRESHOLD ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    accuracy_score,
    confusion_matrix,
    roc_auc_score,
    average_precision_score
)

# ============================================================
# 1. LOAD EXISTING 2025 RESULTS
# ============================================================

RESULT_PATH = (
    "results/layered_model_2025_test_results.csv"
)

df = pd.read_csv(RESULT_PATH)

print("=" * 70)
print("STEP 23 — WARNING THRESHOLD ANALYSIS")
print("=" * 70)

print("Rows:", len(df))


# ============================================================
# 2. CHECK REQUIRED COLUMNS
# ============================================================

required = [
    "landslide_occurred",
    "layered_probability"
]

missing = [
    col for col in required
    if col not in df.columns
]

if missing:

    raise ValueError(
        f"Missing required columns: {missing}"
    )


y = (
    df["landslide_occurred"]
    .astype(int)
)

probability = (
    df["layered_probability"]
    .astype(float)
)


# ============================================================
# 3. PROBABILITY SANITY CHECK
# ============================================================

print("\n" + "=" * 70)
print("PROBABILITY CHECK")
print("=" * 70)

print(
    "Minimum:",
    probability.min()
)

print(
    "Maximum:",
    probability.max()
)

print(
    "Missing:",
    probability.isna().sum()
)

if probability.isna().any():

    raise ValueError(
        "Missing layered probabilities."
    )


# ============================================================
# 4. THRESHOLD ANALYSIS
# ============================================================

thresholds = [
    0.20,
    0.30,
    0.40,
    0.50,
    0.60,
    0.70,
    0.80,
    0.90
]

threshold_results = []

for threshold in thresholds:

    prediction = (
        probability >= threshold
    ).astype(int)

    tn, fp, fn, tp = (
        confusion_matrix(
            y,
            prediction
        ).ravel()
    )

    threshold_results.append({

        "Threshold":
            threshold,

        "Accuracy":
            accuracy_score(
                y,
                prediction
            ),

        "Precision":
            precision_score(
                y,
                prediction,
                zero_division=0
            ),

        "Recall":
            recall_score(
                y,
                prediction,
                zero_division=0
            ),

        "F1":
            f1_score(
                y,
                prediction,
                zero_division=0
            ),

        "True_Negatives":
            tn,

        "False_Positives":
            fp,

        "False_Negatives":
            fn,

        "True_Positives":
            tp,

        "Warnings":
            int(prediction.sum())
    })


threshold_df = pd.DataFrame(
    threshold_results
)


# ============================================================
# 5. DISPLAY
# ============================================================

print("\n" + "=" * 70)
print("THRESHOLD PERFORMANCE")
print("=" * 70)

display(
    threshold_df.round(4)
)


# ============================================================
# 6. FIND BEST THRESHOLD BY F1
# ============================================================

best_f1_row = threshold_df.loc[
    threshold_df["F1"].idxmax()
]

print("\n" + "=" * 70)
print("BEST THRESHOLD BY F1")
print("=" * 70)

print(
    "Threshold:",
    best_f1_row["Threshold"]
)

print(
    "F1:",
    round(
        best_f1_row["F1"],
        6
    )
)

print(
    "Recall:",
    round(
        best_f1_row["Recall"],
        6
    )
)

print(
    "Precision:",
    round(
        best_f1_row["Precision"],
        6
    )
)


# ============================================================
# 7. FIND LOWEST THRESHOLD WITH >=98% RECALL
# ============================================================

high_recall = threshold_df[
    threshold_df["Recall"] >= 0.98
]

print("\n" + "=" * 70)
print("HIGH-RECALL OPERATING POINTS")
print("=" * 70)

if len(high_recall) == 0:

    print(
        "No tested threshold achieved >=98% recall."
    )

else:

    display(
        high_recall.round(4)
    )

    lowest_high_recall = (
        high_recall
        .sort_values("Threshold")
        .iloc[0]
    )

    print(
        "\nLowest tested threshold with "
        ">=98% recall:",
        lowest_high_recall["Threshold"]
    )


# ============================================================
# 8. WARNING-LEVEL DISTRIBUTION
#
# These are descriptive bands only.
# We are NOT claiming they are scientifically validated
# thresholds yet.
# ============================================================

def warning_level(p):

    if p < 0.20:
        return "LOW"

    elif p < 0.40:
        return "MODERATE"

    elif p < 0.60:
        return "HIGH"

    elif p < 0.80:
        return "VERY HIGH"

    else:
        return "EXTREME"


df["warning_level"] = (
    probability.apply(
        warning_level
    )
)


# ============================================================
# 9. WARNING DISTRIBUTION
# ============================================================

print("\n" + "=" * 70)
print("DESCRIPTIVE WARNING-LEVEL DISTRIBUTION")
print("=" * 70)

warning_counts = (
    df["warning_level"]
    .value_counts()
    .reindex(
        [
            "LOW",
            "MODERATE",
            "HIGH",
            "VERY HIGH",
            "EXTREME"
        ],
        fill_value=0
    )
)

print(warning_counts)

print("\nPercentages:")

print(
    (
        warning_counts /
        len(df) *
        100
    ).round(2)
)


# ============================================================
# 10. ACTUAL LANDSLIDES BY WARNING LEVEL
# ============================================================

warning_target = (
    df.groupby(
        "warning_level"
    )["landslide_occurred"]
    .agg(
        observations="count",
        landslides="sum",
        occurrence_rate="mean"
    )
)

warning_target[
    "occurrence_rate"
] *= 100

warning_target = (
    warning_target
    .reindex(
        [
            "LOW",
            "MODERATE",
            "HIGH",
            "VERY HIGH",
            "EXTREME"
        ]
    )
)

print("\n" + "=" * 70)
print("LANDSLIDE OCCURRENCE BY WARNING LEVEL")
print("=" * 70)

display(
    warning_target.round(2)
)


# ============================================================
# 11. SAVE THRESHOLD ANALYSIS
# ============================================================

threshold_output = (
    "results/"
    "layered_warning_threshold_analysis_2025.csv"
)

threshold_df.to_csv(
    threshold_output,
    index=False
)

warning_output = (
    "results/"
    "layered_warning_levels_2025.csv"
)

df.to_csv(
    warning_output,
    index=False
)

print("\n" + "=" * 70)
print("FILES SAVED")
print("=" * 70)

print(
    threshold_output
)

print(
    warning_output
)


# ============================================================
# 12. IMPORTANT METHODOLOGICAL STATUS
# ============================================================

print("\n" + "=" * 70)
print("METHODOLOGICAL STATUS")
print("=" * 70)

print(
    "2025 remains the independent evaluation dataset."
)

print(
    "Threshold analysis is operational/descriptive."
)

print(
    "2026 remains untouched:"
    " 137 rows."
)

print("\nSTEP 23 COMPLETE")

======================================================================
STEP 23 — WARNING THRESHOLD ANALYSIS
======================================================================
Rows: 1026

======================================================================
PROBABILITY CHECK
======================================================================
Minimum: 0.0033903173947077
Maximum: 0.997122394407767
Missing: 0

======================================================================
THRESHOLD PERFORMANCE
======================================================================

,Threshold,Accuracy,Precision,Recall,F1,True_Negatives,False_Positives,False_Negatives,True_Positives,Warnings
0,0.2,0.9600,0.9027,0.9945,0.9464,623,39,2,362,401
1,0.3,0.9630,0.9137,0.9890,0.9499,628,34,4,360,394
2,0.4,0.9678,0.9254,0.9890,0.9562,633,29,4,360,389
3,0.5,0.9795,0.9549,0.9890,0.9717,645,17,4,360,377
4,0.6,0.9854,0.9834,0.9753,0.9793,656,6,9,355,361
5,0.7,0.9844,0.9860,0.9698,0.9778,657,5,11,353,358
6,0.8,0.9649,0.9910,0.9093,0.9484,659,3,33,331,334
7,0.9,0.9542,0.9907,0.8791,0.9316,659,3,44,320,323

======================================================================
BEST THRESHOLD BY F1
======================================================================
Threshold: 0.6
F1: 0.97931
Recall: 0.975275
Precision: 0.98338

======================================================================
HIGH-RECALL OPERATING POINTS
======================================================================

,Threshold,Accuracy,Precision,Recall,F1,True_Negatives,False_Positives,False_Negatives,True_Positives,Warnings
0,0.2,0.9600,0.9027,0.9945,0.9464,623,39,2,362,401
1,0.3,0.9630,0.9137,0.9890,0.9499,628,34,4,360,394
2,0.4,0.9678,0.9254,0.9890,0.9562,633,29,4,360,389
3,0.5,0.9795,0.9549,0.9890,0.9717,645,17,4,360,377

Lowest tested threshold with >=98% recall: 0.2

======================================================================
DESCRIPTIVE WARNING-LEVEL DISTRIBUTION
======================================================================
warning_level
LOW          625
MODERATE      12
HIGH          28
VERY HIGH     27
EXTREME      334
Name: count, dtype: int64

Percentages:
warning_level
LOW          60.92
MODERATE      1.17
HIGH          2.73
VERY HIGH     2.63
EXTREME      32.55
Name: count, dtype: float64

======================================================================
LANDSLIDE OCCURRENCE BY WARNING LEVEL
======================================================================

               observations  landslides  occurrence_rate
warning_level
LOW                     625           2             0.32
MODERATE                 12           2            16.67
HIGH                     28           5            17.86
VERY HIGH                27          24            88.89
EXTREME                 334         331            99.10

======================================================================
FILES SAVED
======================================================================
results/layered_warning_threshold_analysis_2025.csv
results/layered_warning_levels_2025.csv

======================================================================
METHODOLOGICAL STATUS
======================================================================
2025 remains the independent evaluation dataset.
Threshold analysis is operational/descriptive.
2026 remains untouched: 137 rows.

STEP 23 COMPLETE

In [35]:
# ============================================================
# STEP 24 — FINAL 2026 UNTOUCHED HOLDOUT
# ============================================================

import pandas as pd
import numpy as np
import joblib
import os

# ============================================================
# 1. LOAD 2026 DATA
# ============================================================

MASTER_PATH = (
    "data/Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv"
)

master = pd.read_csv(MASTER_PATH)

master["event_date"] = pd.to_datetime(
    master["event_date"]
)

master["year"] = master["event_date"].dt.year

df_2026 = master[
    master["year"] == 2026
].copy()

df_2026 = df_2026.reset_index(
    drop=True
)

print("=" * 70)
print("STEP 24 — FINAL 2026 HOLDOUT")
print("=" * 70)

print(
    "2026 rows:",
    len(df_2026)
)

print(
    "Date range:",
    df_2026["event_date"].min(),
    "to",
    df_2026["event_date"].max()
)

print("\nTarget distribution:")

print(
    df_2026[
        "landslide_occurred"
    ].value_counts()
)


# ============================================================
# 2. VERIFY 2026 WAS NOT USED IN DEVELOPMENT
# ============================================================

development_years = set(
    master.loc[
        master["year"].isin([2023, 2024]),
        "year"
    ]
)

if 2026 in development_years:

    raise ValueError(
        "2026 contamination detected."
    )

print("\n✅ 2026 is outside development period.")


# ============================================================
# 3. LOAD FROZEN LAYERING OUTPUTS
# ============================================================

LAYERING_PATH = (
    "data/layering_dataset.csv"
)

layering = pd.read_csv(
    LAYERING_PATH
)

required_columns = [
    "master_row_id",
    "xgb_probability",
    "xgb_prediction",
    "ahc_cluster",
    "ahc_susceptibility",
    "ahc_category"
]

missing = [
    c for c in required_columns
    if c not in layering.columns
]

if missing:

    raise ValueError(
        f"Missing layering columns: {missing}"
    )

layering_subset = layering[
    required_columns
].copy()


# ============================================================
# 4. MERGE FROZEN MODEL OUTPUTS
# ============================================================

if "master_row_id" not in df_2026.columns:

    raise ValueError(
        "master_row_id missing from master dataset."
    )

eval_2026 = df_2026.merge(
    layering_subset,
    on="master_row_id",
    how="left",
    validate="one_to_one"
)

model_columns = [
    "xgb_probability",
    "xgb_prediction",
    "ahc_cluster",
    "ahc_susceptibility",
    "ahc_category"
]

missing_outputs = (
    eval_2026[
        model_columns
    ]
    .isna()
    .sum()
)

print("\n" + "=" * 70)
print("FROZEN MODEL OUTPUT CHECK")
print("=" * 70)

print(missing_outputs)

if missing_outputs.sum() != 0:

    raise ValueError(
        "Missing frozen model outputs."
    )

print(
    "\n✅ All frozen model outputs available."
)


# ============================================================
# 5. LOAD FROZEN DECISION MODEL
# ============================================================

MODEL_PATH = (
    "models/layered_decision_model.pkl"
)

if not os.path.exists(MODEL_PATH):

    raise FileNotFoundError(
        MODEL_PATH
    )

decision_model = joblib.load(
    MODEL_PATH
)

print(
    "✅ Frozen Decision Model loaded."
)


# ============================================================
# 6. PREPARE DECISION-LAYER INPUT
# ============================================================

X_2026 = pd.DataFrame({

    "xgb_oof_probability":
        eval_2026[
            "xgb_probability"
        ],

    "ahc_susceptibility":
        eval_2026[
            "ahc_susceptibility"
        ],

    "ahc_cluster":
        eval_2026[
            "ahc_cluster"
        ],

    "ahc_category":
        eval_2026[
            "ahc_category"
        ]
})


# ============================================================
# 7. FINAL LAYERED PREDICTION
# ============================================================

layered_probability = (
    decision_model
    .predict_proba(
        X_2026
    )[:, 1]
)

eval_2026[
    "layered_probability"
] = layered_probability


# ============================================================
# 8. DESCRIPTIVE WARNING LEVELS
#
# These are the same bands analyzed in STEP 23.
# They are NOT retuned using 2026.
# ============================================================

def warning_level(p):

    if p < 0.20:
        return "LOW"

    elif p < 0.40:
        return "MODERATE"

    elif p < 0.60:
        return "HIGH"

    elif p < 0.80:
        return "VERY HIGH"

    else:
        return "EXTREME"


eval_2026[
    "warning_level"
] = (
    eval_2026[
        "layered_probability"
    ]
    .apply(warning_level)
)


# ============================================================
# 9. BINARY DECISION AT PREDEFINED 0.50
#
# This threshold was established before 2026.
# ============================================================

eval_2026[
    "layered_prediction_0_50"
] = (
    eval_2026[
        "layered_probability"
    ] >= 0.50
).astype(int)


# ============================================================
# 10. 2026 PROBABILITY SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("2026 LAYERED PROBABILITY DISTRIBUTION")
print("=" * 70)

print(
    eval_2026[
        "layered_probability"
    ].describe()
)


# ============================================================
# 11. EXTREME PROBABILITIES
# ============================================================

print("\n" + "=" * 70)
print("2026 PROBABILITY EXTREMES")
print("=" * 70)

print(
    "Minimum:",
    eval_2026[
        "layered_probability"
    ].min()
)

print(
    "Maximum:",
    eval_2026[
        "layered_probability"
    ].max()
)

print(
    "Mean:",
    eval_2026[
        "layered_probability"
    ].mean()
)

print(
    "Median:",
    eval_2026[
        "layered_probability"
    ].median()
)


# ============================================================
# 12. WARNING LEVEL DISTRIBUTION
# ============================================================

warning_order = [
    "LOW",
    "MODERATE",
    "HIGH",
    "VERY HIGH",
    "EXTREME"
]

warning_counts = (
    eval_2026[
        "warning_level"
    ]
    .value_counts()
    .reindex(
        warning_order,
        fill_value=0
    )
)

warning_percent = (
    warning_counts /
    len(eval_2026) *
    100
)

warning_summary = pd.DataFrame({

    "observations":
        warning_counts,

    "percentage":
        warning_percent
})


print("\n" + "=" * 70)
print("2026 WARNING-LEVEL DISTRIBUTION")
print("=" * 70)

display(
    warning_summary.round(2)
)


# ============================================================
# 13. PREDEFINED 0.50 DECISION
# ============================================================

n_positive_predictions = int(
    eval_2026[
        "layered_prediction_0_50"
    ].sum()
)

print("\n" + "=" * 70)
print("2026 PREDEFINED 0.50 DECISION")
print("=" * 70)

print(
    "Predicted landslide:",
    n_positive_predictions
)

print(
    "Predicted no landslide:",
    len(eval_2026)
    -
    n_positive_predictions
)

print(
    "Prediction rate:",
    round(
        100 *
        n_positive_predictions /
        len(eval_2026),
        2
    ),
    "%"
)


# ============================================================
# 14. HIGH-RISK COUNTS
# ============================================================

high_risk_levels = [
    "VERY HIGH",
    "EXTREME"
]

high_risk_count = (
    eval_2026[
        "warning_level"
    ]
    .isin(high_risk_levels)
    .sum()
)

print("\n" + "=" * 70)
print("2026 HIGH-RISK FLAGS")
print("=" * 70)

print(
    "VERY HIGH + EXTREME:",
    high_risk_count
)

print(
    "Percentage:",
    round(
        100 *
        high_risk_count /
        len(eval_2026),
        2
    ),
    "%"
)


# ============================================================
# 15. TARGET INFORMATION
#
# IMPORTANT:
# There are no positive 2026 observations according to
# the current dataset, so classification metrics such as
# ROC-AUC/recall are not meaningful.
# ============================================================

positive_2026 = int(
    eval_2026[
        "landslide_occurred"
    ].sum()
)

print("\n" + "=" * 70)
print("2026 TARGET STATUS")
print("=" * 70)

print(
    "Actual landslide observations:",
    positive_2026
)

if positive_2026 == 0:

    print(
        "\n⚠️ No positive cases exist in the "
        "2026 dataset."
    )

    print(
        "ROC-AUC, PR-AUC and recall are therefore "
        "not reported as conventional test metrics."
    )


# ============================================================
# 16. HIGHEST-RISK 2026 OBSERVATIONS
# ============================================================

print("\n" + "=" * 70)
print("TOP 20 2026 HIGHEST-RISK OBSERVATIONS")
print("=" * 70)

top_20 = (
    eval_2026[
        [
            "master_row_id",
            "event_date",
            "state",
            "district",
            "latitude",
            "longitude",
            "xgb_probability",
            "ahc_susceptibility",
            "ahc_category",
            "layered_probability",
            "warning_level"
        ]
    ]
    .sort_values(
        "layered_probability",
        ascending=False
    )
    .head(20)
)

display(
    top_20.round(6)
)


# ============================================================
# 17. SAVE FINAL HOLDOUT OUTPUT
# ============================================================

OUTPUT_PATH = (
    "results/"
    "final_2026_holdout_predictions.csv"
)

eval_2026.to_csv(
    OUTPUT_PATH,
    index=False
)

SUMMARY_PATH = (
    "results/"
    "final_2026_holdout_summary.csv"
)

warning_summary.to_csv(
    SUMMARY_PATH
)

print("\n" + "=" * 70)
print("FINAL 2026 HOLDOUT FILES SAVED")
print("=" * 70)

print(
    OUTPUT_PATH
)

print(
    SUMMARY_PATH
)


# ============================================================
# 18. FINAL FREEZE STATUS
# ============================================================

print("\n" + "=" * 70)
print("STEP 24 COMPLETE")
print("=" * 70)

print(
    "2026 rows evaluated:",
    len(eval_2026)
)

print(
    "2026 rows used for training: 0"
)

print(
    "Decision model modified: NO"
)

print(
    "Threshold modified: NO"
)

print(
    "2026 holdout remains untouched for training."
)

======================================================================
STEP 24 — FINAL 2026 HOLDOUT
======================================================================
2026 rows: 137
Date range: 2026-01-01 00:00:00 to 2026-04-10 00:00:00

Target distribution:
landslide_occurred
0    137
Name: count, dtype: int64

✅ 2026 is outside development period.

======================================================================
FROZEN MODEL OUTPUT CHECK
======================================================================
xgb_probability       0
xgb_prediction        0
ahc_cluster           0
ahc_susceptibility    0
ahc_category          0
dtype: int64

✅ All frozen model outputs available.
✅ Frozen Decision Model loaded.

======================================================================
2026 LAYERED PROBABILITY DISTRIBUTION
======================================================================
count    137.000000
mean       0.115036
std        0.204138
min        0.004254
25%        0.013687
50%        0.021270
75%        0.100874
max        0.965117
Name: layered_probability, dtype: float64

======================================================================
2026 PROBABILITY EXTREMES
======================================================================
Minimum: 0.004253836849389968
Maximum: 0.9651165064924074
Mean: 0.11503579005625403
Median: 0.021270412279085184

======================================================================
2026 WARNING-LEVEL DISTRIBUTION
======================================================================

               observations  percentage
warning_level
LOW                     113       82.48
MODERATE                 12        8.76
HIGH                      5        3.65
VERY HIGH                 3        2.19
EXTREME                   4        2.92

======================================================================
2026 PREDEFINED 0.50 DECISION
======================================================================
Predicted landslide: 8
Predicted no landslide: 129
Prediction rate: 5.84 %

======================================================================
2026 HIGH-RISK FLAGS
======================================================================
VERY HIGH + EXTREME: 7
Percentage: 5.11 %

======================================================================
2026 TARGET STATUS
======================================================================
Actual landslide observations: 0

⚠️ No positive cases exist in the 2026 dataset.
ROC-AUC, PR-AUC and recall are therefore not reported as conventional test metrics.

======================================================================
TOP 20 2026 HIGHEST-RISK OBSERVATIONS
======================================================================

C:\Users\bubub\AppData\Local\Temp\ipykernel_22892\765928878.py:528: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  top_20.round(6)

,master_row_id,event_date,state,district,latitude,longitude,xgb_probability,ahc_susceptibility,ahc_category,layered_probability,warning_level
82,1962,2026-03-01,Sikkim,Mangan,27.505709,88.528110,0.982176,32.638889,HIGH,0.965117,EXTREME
47,1927,2026-01-24,Sikkim,Gyalshing,27.313698,88.189950,0.908655,32.638889,HIGH,0.947158,EXTREME
20,1900,2026-01-05,Sikkim,Soreng,27.132313,88.118675,0.888469,32.638889,HIGH,0.940865,EXTREME
18,1898,2026-01-05,Sikkim,Mangan,27.439848,88.524060,0.789954,32.638889,HIGH,0.898926,EXTREME
133,2013,2026-03-18,Arunachal Pradesh,Kra Daadi,27.728561,93.636790,0.585052,32.638889,HIGH,0.726234,VERY HIGH
120,2000,2026-03-13,Assam,Kamrup Metro,26.157864,91.756220,0.905106,9.813084,LOW,0.690984,VERY HIGH
121,2001,2026-03-13,Nagaland,Mokokchung,26.326025,94.511050,0.829475,5.000000,LOW,0.668026,VERY HIGH
122,2002,2026-03-13,Sikkim,Mangan,27.508540,88.526886,0.964564,0.000000,LOW,0.500115,HIGH
135,2015,2026-03-30,Arunachal Pradesh,Tirap,26.994652,95.486694,0.960129,0.000000,LOW,0.493570,HIGH
119,1999,2026-03-13,Sikkim,Gyalshing,27.284554,88.195550,0.394242,32.638889,HIGH,0.462332,HIGH
129,2009,2026-03-16,Nagaland,Kohima,25.924599,94.214970,0.657939,5.000000,LOW,0.422264,HIGH
123,2003,2026-03-13,Assam,Sribhumi,24.842453,92.554120,0.712043,9.813084,LOW,0.416993,HIGH
113,1993,2026-03-12,Nagaland,Dimapur,25.784058,93.800804,0.339147,32.638889,HIGH,0.383141,MODERATE
136,2016,2026-04-10,Assam,Cachar,24.795984,93.045490,0.686928,9.813084,LOW,0.381447,MODERATE
107,1987,2026-03-11,Nagaland,Dimapur,25.785057,93.802500,0.321792,32.638889,HIGH,0.359231,MODERATE
109,1989,2026-03-11,Nagaland,Dimapur,25.796894,93.803250,0.321792,32.638889,HIGH,0.359231,MODERATE
108,1988,2026-03-11,Nagaland,Dimapur,25.796880,93.804170,0.321792,32.638889,HIGH,0.359231,MODERATE
1,1881,2026-01-01,Nagaland,Mokokchung,26.424910,94.386950,0.255096,32.638889,HIGH,0.274386,MODERATE
2,1882,2026-01-01,Nagaland,Mokokchung,26.424053,94.392200,0.255096,32.638889,HIGH,0.274386,MODERATE
73,1953,2026-02-03,Nagaland,Mokokchung,26.389270,94.632614,0.244948,32.638889,HIGH,0.262620,MODERATE

======================================================================
FINAL 2026 HOLDOUT FILES SAVED
======================================================================
results/final_2026_holdout_predictions.csv
results/final_2026_holdout_summary.csv

======================================================================
STEP 24 COMPLETE
======================================================================
2026 rows evaluated: 137
2026 rows used for training: 0
Decision model modified: NO
Threshold modified: NO
2026 holdout remains untouched for training.

In [36]:
# ============================================================
# STEP 25A — XGBOOST OVERFITTING / UNDERFITTING CHECK
# ============================================================

import pandas as pd
import numpy as np
import xgboost as xgb
import json
import os

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    log_loss,
    confusion_matrix
)

# ============================================================
# 1. PATHS
# ============================================================

MODEL_PATH = (
    "models/STEP73_FROZEN_XGBOOST.json"
)

TRAIN_PATH = (
    "data/Landslide_NER_XGBOOST_TRAIN_1278.csv"
)

OOF_PATH = (
    "data/decision_model_training_oof.csv"
)

TEST_PATH = (
    "data/decision_model_test_2025.csv"
)

# ============================================================
# 2. LOAD MODEL
# ============================================================

booster = xgb.Booster()

booster.load_model(
    MODEL_PATH
)

print("=" * 70)
print("XGBOOST OVERFITTING / UNDERFITTING CHECK")
print("=" * 70)

print(
    "Model loaded:",
    MODEL_PATH
)

# ============================================================
# 3. FEATURE ORDER
# ============================================================

XGB_FEATURES = [
    "rzsm_1",
    "rzsm_2",
    "rzsm_3",
    "cumulative_rainfall_3d_mm",
    "_rzsm_mean_",
    "_rzsm_range_",
    "_rzsm_surface_deep_diff_",
    "_rain_rzsm_interaction_",
    "_previous_rzsm_",
    "_previous_rzsm_2_",
    "_previous_rzsm_3_",
    "_previous_rainfall_"
]

TARGET = "landslide_occurred"


# ============================================================
# 4. HELPER
# ============================================================

def evaluate_predictions(
    y_true,
    probability
):

    prediction = (
        probability >= 0.50
    ).astype(int)

    return {

        "ROC_AUC":
            roc_auc_score(
                y_true,
                probability
            ),

        "PR_AUC":
            average_precision_score(
                y_true,
                probability
            ),

        "Accuracy":
            accuracy_score(
                y_true,
                prediction
            ),

        "Precision":
            precision_score(
                y_true,
                prediction,
                zero_division=0
            ),

        "Recall":
            recall_score(
                y_true,
                prediction,
                zero_division=0
            ),

        "F1":
            f1_score(
                y_true,
                prediction,
                zero_division=0
            ),

        "LogLoss":
            log_loss(
                y_true,
                probability
            )
    }


# ============================================================
# 5. LOAD XGBOOST TRAINING DATA
# ============================================================

train_df = pd.read_csv(
    TRAIN_PATH
)

print("\nXGBoost training rows:")
print(len(train_df))

missing_features = [
    c for c in XGB_FEATURES
    if c not in train_df.columns
]

if missing_features:

    raise ValueError(
        f"Missing XGBoost features: {missing_features}"
    )


# ============================================================
# 6. TRAINING PREDICTIONS
# ============================================================

X_train = (
    train_df[
        XGB_FEATURES
    ]
    .astype(float)
)

y_train = (
    train_df[
        TARGET
    ]
    .astype(int)
)

dtrain = xgb.DMatrix(
    X_train,
    feature_names=XGB_FEATURES
)

train_probability = (
    booster.predict(
        dtrain
    )
)

train_metrics = evaluate_predictions(
    y_train,
    train_probability
)


# ============================================================
# 7. LOAD OOF DATA
#
# The OOF file contains XGBoost predictions for 2023–2024.
# ============================================================

oof_df = pd.read_csv(
    OOF_PATH
)

print(
    "\nOOF rows:",
    len(oof_df)
)

if "xgb_oof_probability" not in oof_df.columns:

    raise ValueError(
        "xgb_oof_probability missing from OOF dataset."
    )

y_oof = (
    oof_df[
        TARGET
    ]
    .astype(int)
)

oof_probability = (
    oof_df[
        "xgb_oof_probability"
    ]
    .astype(float)
)

oof_metrics = evaluate_predictions(
    y_oof,
    oof_probability
)


# ============================================================
# 8. LOAD 2025 TEST
# ============================================================

test_df = pd.read_csv(
    TEST_PATH
)

print(
    "2025 test rows:",
    len(test_df)
)

# The test file already contains the frozen
# XGBoost probability from the previous evaluation.

if "xgb_probability" not in test_df.columns:

    raise ValueError(
        "xgb_probability missing from 2025 test."
    )

y_test = (
    test_df[
        TARGET
    ]
    .astype(int)
)

test_probability = (
    test_df[
        "xgb_probability"
    ]
    .astype(float)
)

test_metrics = evaluate_predictions(
    y_test,
    test_probability
)


# ============================================================
# 9. COMPARISON
# ============================================================

comparison = pd.DataFrame({

    "Training":
        train_metrics,

    "OOF_2023_2024":
        oof_metrics,

    "Independent_2025":
        test_metrics

}).T

print("\n" + "=" * 70)
print("XGBOOST TRAIN / OOF / TEST COMPARISON")
print("=" * 70)

display(
    comparison.round(6)
)


# ============================================================
# 10. GENERALIZATION GAPS
# ============================================================

print("\n" + "=" * 70)
print("GENERALIZATION GAPS")
print("=" * 70)

for metric in [
    "ROC_AUC",
    "PR_AUC",
    "Accuracy",
    "Precision",
    "Recall",
    "F1",
    "LogLoss"
]:

    train_value = train_metrics[metric]
    oof_value = oof_metrics[metric]
    test_value = test_metrics[metric]

    print(
        f"{metric:10s} | "
        f"Train→OOF: "
        f"{train_value - oof_value:+.6f} | "
        f"OOF→2025: "
        f"{oof_value - test_value:+.6f} | "
        f"Train→2025: "
        f"{train_value - test_value:+.6f}"
    )


# ============================================================
# 11. TRAINING AUC — DIRECT OVERFITTING WARNING
# ============================================================

train_auc = train_metrics["ROC_AUC"]
oof_auc = oof_metrics["ROC_AUC"]
test_auc = test_metrics["ROC_AUC"]

print("\n" + "=" * 70)
print("OVERFITTING DIAGNOSTIC")
print("=" * 70)

if (
    train_auc - oof_auc > 0.05
    and
    train_auc - test_auc > 0.05
):

    print(
        "⚠️ POSSIBLE XGBOOST OVERFITTING"
    )

elif (
    train_auc < 0.80
    and
    oof_auc < 0.80
    and
    test_auc < 0.80
):

    print(
        "⚠️ POSSIBLE XGBOOST UNDERFITTING"
    )

else:

    print(
        "✅ No obvious overfitting/underfitting "
        "signal from ROC-AUC."
    )


# ============================================================
# 12. TREE COUNT
# ============================================================

try:

    dump = booster.get_dump()

    print("\n" + "=" * 70)
    print("MODEL COMPLEXITY")
    print("=" * 70)

    print(
        "Number of trees:",
        len(dump)
    )

except Exception as e:

    print(
        "Could not inspect tree count:",
        e
    )


# ============================================================
# 13. SAVE DIAGNOSTIC
# ============================================================

OUTPUT = (
    "results/"
    "xgboost_overfitting_underfitting_check.csv"
)

comparison.to_csv(
    OUTPUT
)

print("\nSaved:")
print(OUTPUT)

print("\n" + "=" * 70)
print("STEP 25A COMPLETE")
print("=" * 70)

======================================================================
XGBOOST OVERFITTING / UNDERFITTING CHECK
======================================================================
Model loaded: models/STEP73_FROZEN_XGBOOST.json

XGBoost training rows:
1278

OOF rows: 853
2025 test rows: 1026

======================================================================
XGBOOST TRAIN / OOF / TEST COMPARISON
======================================================================

,ROC_AUC,PR_AUC,Accuracy,Precision,Recall,F1,LogLoss
Training,0.995617,0.988894,0.972613,0.950431,0.973510,0.961832,0.087094
OOF_2023_2024,0.984332,0.954979,0.949590,0.928803,0.931818,0.930308,0.199103
Independent_2025,0.993937,0.986574,0.966862,0.950820,0.956044,0.953425,0.095180

======================================================================
GENERALIZATION GAPS
======================================================================
ROC_AUC    | Train→OOF: +0.011285 | OOF→2025: -0.009605 | Train→2025: +0.001680
PR_AUC     | Train→OOF: +0.033915 | OOF→2025: -0.031596 | Train→2025: +0.002320
Accuracy   | Train→OOF: +0.023024 | OOF→2025: -0.017272 | Train→2025: +0.005752
Precision  | Train→OOF: +0.021628 | OOF→2025: -0.022017 | Train→2025: -0.000389
Recall     | Train→OOF: +0.041692 | OOF→2025: -0.024226 | Train→2025: +0.017466
F1         | Train→OOF: +0.031524 | OOF→2025: -0.023117 | Train→2025: +0.008407
LogLoss    | Train→OOF: -0.112009 | OOF→2025: +0.103923 | Train→2025: -0.008086

======================================================================
OVERFITTING DIAGNOSTIC
======================================================================
✅ No obvious overfitting/underfitting signal from ROC-AUC.

======================================================================
MODEL COMPLEXITY
======================================================================
Number of trees: 300

Saved:
results/xgboost_overfitting_underfitting_check.csv

======================================================================
STEP 25A COMPLETE
======================================================================

In [37]:
# ============================================================
# STEP 25B — DECISION LAYER OVERFITTING / UNDERFITTING CHECK
# ============================================================

import pandas as pd
import numpy as np
import joblib

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    log_loss
)

# ============================================================
# 1. LOAD FINAL DECISION MODEL
# ============================================================

MODEL_PATH = (
    "models/layered_decision_model.pkl"
)

decision_model = joblib.load(
    MODEL_PATH
)

print("=" * 70)
print("DECISION LAYER OVERFITTING / UNDERFITTING CHECK")
print("=" * 70)

print(
    "Model loaded:",
    MODEL_PATH
)


# ============================================================
# 2. LOAD META DEVELOPMENT DATA
# ============================================================

META_PATH = (
    "data/decision_model_training_oof.csv"
)

meta = pd.read_csv(
    META_PATH
)

print(
    "\nMeta-development rows:",
    len(meta)
)


# ============================================================
# 3. FEATURES
# ============================================================

FEATURES = [
    "xgb_oof_probability",
    "ahc_susceptibility",
    "ahc_cluster",
    "ahc_category"
]

TARGET = "landslide_occurred"

X_meta = meta[
    FEATURES
].copy()

y_meta = meta[
    TARGET
].astype(int)


# ============================================================
# 4. FINAL MODEL TRAINING PERFORMANCE
# ============================================================

train_probability = (
    decision_model
    .predict_proba(
        X_meta
    )[:, 1]
)

train_prediction = (
    train_probability >= 0.50
).astype(int)


def calculate_metrics(
    y,
    probability,
    prediction
):

    return {

        "ROC_AUC":
            roc_auc_score(
                y,
                probability
            ),

        "PR_AUC":
            average_precision_score(
                y,
                probability
            ),

        "Accuracy":
            accuracy_score(
                y,
                prediction
            ),

        "Precision":
            precision_score(
                y,
                prediction,
                zero_division=0
            ),

        "Recall":
            recall_score(
                y,
                prediction,
                zero_division=0
            ),

        "F1":
            f1_score(
                y,
                prediction,
                zero_division=0
            ),

        "LogLoss":
            log_loss(
                y,
                probability
            )
    }


train_metrics = calculate_metrics(
    y_meta,
    train_probability,
    train_prediction
)


# ============================================================
# 5. LOAD TRUE DECISION OOF PREDICTIONS
#
# These were generated during STEP 19 where the Decision
# Model was trained separately on each fold.
# ============================================================

RESULT_PATH = (
    "results/decision_model_oof_results.csv"
)

oof = pd.read_csv(
    RESULT_PATH
)

if "decision_oof_probability" not in oof.columns:

    raise ValueError(
        "decision_oof_probability not found."
    )

y_oof = (
    oof[
        TARGET
    ]
    .astype(int)
)

oof_probability = (
    oof[
        "decision_oof_probability"
    ]
    .astype(float)
)

oof_prediction = (
    oof_probability >= 0.50
).astype(int)

oof_metrics = calculate_metrics(
    y_oof,
    oof_probability,
    oof_prediction
)


# ============================================================
# 6. LOAD INDEPENDENT 2025 RESULTS
# ============================================================

TEST_PATH = (
    "results/layered_model_2025_test_results.csv"
)

test = pd.read_csv(
    TEST_PATH
)

print(
    "Independent 2025 rows:",
    len(test)
)

# Locate final layered probability column

possible_probability_columns = [
    "layered_probability",
    "decision_probability",
    "final_probability"
]

probability_column = None

for column in possible_probability_columns:

    if column in test.columns:

        probability_column = column
        break

if probability_column is None:

    raise ValueError(
        "Could not find layered probability column "
        "in 2025 results."
    )

test_probability = (
    test[
        probability_column
    ]
    .astype(float)
)

y_test = (
    test[
        TARGET
    ]
    .astype(int)
)

test_prediction = (
    test_probability >= 0.50
).astype(int)

test_metrics = calculate_metrics(
    y_test,
    test_probability,
    test_prediction
)


# ============================================================
# 7. COMPARISON
# ============================================================

comparison = pd.DataFrame({

    "Meta_Training":
        train_metrics,

    "Decision_OOF":
        oof_metrics,

    "Independent_2025":
        test_metrics

}).T

print("\n" + "=" * 70)
print("DECISION LAYER TRAIN / OOF / TEST")
print("=" * 70)

display(
    comparison.round(6)
)


# ============================================================
# 8. GENERALIZATION GAPS
# ============================================================

print("\n" + "=" * 70)
print("DECISION LAYER GENERALIZATION GAPS")
print("=" * 70)

for metric in [
    "ROC_AUC",
    "PR_AUC",
    "Accuracy",
    "Precision",
    "Recall",
    "F1",
    "LogLoss"
]:

    train_value = train_metrics[metric]
    oof_value = oof_metrics[metric]
    test_value = test_metrics[metric]

    print(
        f"{metric:10s} | "
        f"Train→OOF: "
        f"{train_value - oof_value:+.6f} | "
        f"OOF→2025: "
        f"{oof_value - test_value:+.6f} | "
        f"Train→2025: "
        f"{train_value - test_value:+.6f}"
    )


# ============================================================
# 9. DIAGNOSTIC
# ============================================================

train_auc = train_metrics[
    "ROC_AUC"
]

oof_auc = oof_metrics[
    "ROC_AUC"
]

test_auc = test_metrics[
    "ROC_AUC"
]

print("\n" + "=" * 70)
print("DECISION LAYER DIAGNOSTIC")
print("=" * 70)

if (
    train_auc - oof_auc > 0.05
    and
    train_auc - test_auc > 0.05
):

    print(
        "⚠️ POSSIBLE DECISION-LAYER OVERFITTING"
    )

elif (
    train_auc < 0.80
    and
    oof_auc < 0.80
    and
    test_auc < 0.80
):

    print(
        "⚠️ POSSIBLE DECISION-LAYER UNDERFITTING"
    )

else:

    print(
        "✅ No obvious overfitting/underfitting "
        "signal from ROC-AUC."
    )


# ============================================================
# 10. MODEL COMPLEXITY
# ============================================================

classifier = (
    decision_model
    .named_steps[
        "classifier"
    ]
)

print("\n" + "=" * 70)
print("DECISION MODEL COMPLEXITY")
print("=" * 70)

print(
    "Classifier:",
    type(classifier).__name__
)

print(
    "Regularization:",
    classifier.get_params()[
        "C"
    ]
)

print(
    "Class weighting:",
    classifier.get_params()[
        "class_weight"
    ]
)


# ============================================================
# 11. SAVE RESULTS
# ============================================================

OUTPUT = (
    "results/"
    "decision_layer_overfitting_underfitting_check.csv"
)

comparison.to_csv(
    OUTPUT
)

print("\nSaved:")
print(OUTPUT)

print("\n" + "=" * 70)
print("STEP 25B COMPLETE")
print("=" * 70)

======================================================================
DECISION LAYER OVERFITTING / UNDERFITTING CHECK
======================================================================
Model loaded: models/layered_decision_model.pkl

Meta-development rows: 853
Independent 2025 rows: 1026

======================================================================
DECISION LAYER TRAIN / OOF / TEST
======================================================================

,ROC_AUC,PR_AUC,Accuracy,Precision,Recall,F1,LogLoss
Meta_Training,0.994001,0.990871,0.963658,0.942492,0.957792,0.950081,0.103841
Decision_OOF,0.991803,0.987829,0.946073,0.904321,0.951299,0.927215,0.112013
Independent_2025,0.998012,0.996952,0.979532,0.954907,0.989011,0.971660,0.069904

======================================================================
DECISION LAYER GENERALIZATION GAPS
======================================================================
ROC_AUC    | Train→OOF: +0.002198 | OOF→2025: -0.006209 | Train→2025: -0.004011
PR_AUC     | Train→OOF: +0.003042 | OOF→2025: -0.009122 | Train→2025: -0.006081
Accuracy   | Train→OOF: +0.017585 | OOF→2025: -0.033459 | Train→2025: -0.015874
Precision  | Train→OOF: +0.038171 | OOF→2025: -0.050586 | Train→2025: -0.012415
Recall     | Train→OOF: +0.006494 | OOF→2025: -0.037712 | Train→2025: -0.031219
F1         | Train→OOF: +0.022865 | OOF→2025: -0.044445 | Train→2025: -0.021579
LogLoss    | Train→OOF: -0.008172 | OOF→2025: +0.042109 | Train→2025: +0.033937

======================================================================
DECISION LAYER DIAGNOSTIC
======================================================================
✅ No obvious overfitting/underfitting signal from ROC-AUC.

======================================================================
DECISION MODEL COMPLEXITY
======================================================================
Classifier: LogisticRegression
Regularization: 1.0
Class weighting: balanced

Saved:
results/decision_layer_overfitting_underfitting_check.csv

======================================================================
STEP 25B COMPLETE
======================================================================

In [38]:
# ============================================================
# STEP 25C — FINAL PROBABILITY CALIBRATION & RELIABILITY CHECK
# ============================================================

import pandas as pd
import numpy as np
import joblib
import os

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    brier_score_loss,
    log_loss
)

from sklearn.calibration import calibration_curve

# ============================================================
# 1. LOAD DECISION MODEL
# ============================================================

MODEL_PATH = "models/layered_decision_model.pkl"

decision_model = joblib.load(MODEL_PATH)

print("=" * 70)
print("STEP 25C — FINAL CALIBRATION & RELIABILITY CHECK")
print("=" * 70)

print("Decision model loaded.")


# ============================================================
# 2. LOAD DECISION-LAYER OOF RESULTS
# ============================================================

OOF_PATH = "results/decision_model_oof_results.csv"

oof = pd.read_csv(OOF_PATH)

TARGET = "landslide_occurred"

PROBABILITY_COLUMN = (
    "decision_oof_probability"
)

if TARGET not in oof.columns:
    raise ValueError("Target column missing.")

if PROBABILITY_COLUMN not in oof.columns:
    raise ValueError(
        "Decision OOF probability missing."
    )

y_oof = (
    oof[TARGET]
    .astype(int)
)

p_oof = (
    oof[PROBABILITY_COLUMN]
    .astype(float)
)

print("\n" + "=" * 70)
print("OOF DATA")
print("=" * 70)

print("Rows:", len(oof))
print("Missing probabilities:", p_oof.isna().sum())
print("Probability minimum:", p_oof.min())
print("Probability maximum:", p_oof.max())


# ============================================================
# 3. BASIC PROBABILITY VALIDATION
# ============================================================

if p_oof.isna().any():
    raise ValueError(
        "Missing probability values."
    )

if ((p_oof < 0) | (p_oof > 1)).any():
    raise ValueError(
        "Invalid probabilities outside [0,1]."
    )

print(
    "✅ All probabilities valid."
)


# ============================================================
# 4. OOF CALIBRATION METRICS
# ============================================================

oof_brier = brier_score_loss(
    y_oof,
    p_oof
)

oof_logloss = log_loss(
    y_oof,
    p_oof
)

oof_auc = roc_auc_score(
    y_oof,
    p_oof
)

oof_pr_auc = average_precision_score(
    y_oof,
    p_oof
)

print("\n" + "=" * 70)
print("OOF PROBABILITY QUALITY")
print("=" * 70)

print(
    f"ROC-AUC   : {oof_auc:.6f}"
)

print(
    f"PR-AUC    : {oof_pr_auc:.6f}"
)

print(
    f"Brier     : {oof_brier:.6f}"
)

print(
    f"LogLoss   : {oof_logloss:.6f}"
)


# ============================================================
# 5. RELIABILITY / CALIBRATION TABLE
# ============================================================

# Fixed bins make the result easy to explain.

bins = [
    0.0,
    0.1,
    0.2,
    0.3,
    0.4,
    0.5,
    0.6,
    0.7,
    0.8,
    0.9,
    1.0
]

labels = [
    "0.0–0.1",
    "0.1–0.2",
    "0.2–0.3",
    "0.3–0.4",
    "0.4–0.5",
    "0.5–0.6",
    "0.6–0.7",
    "0.7–0.8",
    "0.8–0.9",
    "0.9–1.0"
]

calibration_df = pd.DataFrame({
    "probability": p_oof,
    "actual": y_oof
})

calibration_df["bin"] = pd.cut(
    calibration_df["probability"],
    bins=bins,
    labels=labels,
    include_lowest=True,
    right=False
)

reliability_rows = []

for label in labels:

    subset = calibration_df[
        calibration_df["bin"] == label
    ]

    if len(subset) == 0:
        continue

    mean_predicted = (
        subset["probability"].mean()
    )

    observed_rate = (
        subset["actual"].mean()
    )

    reliability_rows.append({

        "probability_bin":
            label,

        "observations":
            len(subset),

        "mean_predicted_probability":
            mean_predicted,

        "observed_landslide_rate":
            observed_rate,

        "absolute_calibration_error":
            abs(
                mean_predicted -
                observed_rate
            )
    })

reliability = pd.DataFrame(
    reliability_rows
)

print("\n" + "=" * 70)
print("OOF RELIABILITY TABLE")
print("=" * 70)

display(
    reliability.round(4)
)


# ============================================================
# 6. HIGH-RISK PROBABILITY CHECK
# ============================================================

print("\n" + "=" * 70)
print("HIGH-RISK PROBABILITY RELIABILITY")
print("=" * 70)

high_risk_thresholds = [
    0.20,
    0.40,
    0.50,
    0.60,
    0.80,
    0.90
]

high_risk_rows = []

for threshold in high_risk_thresholds:

    subset = calibration_df[
        calibration_df["probability"] >= threshold
    ]

    if len(subset) == 0:
        continue

    high_risk_rows.append({

        "threshold":
            threshold,

        "observations":
            len(subset),

        "mean_predicted_probability":
            subset["probability"].mean(),

        "observed_landslide_rate":
            subset["actual"].mean(),

        "calibration_gap":
            (
                subset["probability"].mean()
                -
                subset["actual"].mean()
            )
    })

high_risk_df = pd.DataFrame(
    high_risk_rows
)

display(
    high_risk_df.round(4)
)


# ============================================================
# 7. INDEPENDENT 2025 CHECK
# ============================================================

TEST_PATH = (
    "results/layered_model_2025_test_results.csv"
)

test = pd.read_csv(
    TEST_PATH
)

possible_columns = [
    "layered_probability",
    "decision_probability",
    "final_probability"
]

test_probability_column = None

for col in possible_columns:

    if col in test.columns:

        test_probability_column = col
        break

if test_probability_column is None:

    raise ValueError(
        "2025 layered probability column not found."
    )

y_2025 = (
    test[TARGET]
    .astype(int)
)

p_2025 = (
    test[
        test_probability_column
    ]
    .astype(float)
)

brier_2025 = brier_score_loss(
    y_2025,
    p_2025
)

logloss_2025 = log_loss(
    y_2025,
    p_2025
)

auc_2025 = roc_auc_score(
    y_2025,
    p_2025
)

pr_auc_2025 = average_precision_score(
    y_2025,
    p_2025
)

print("\n" + "=" * 70)
print("INDEPENDENT 2025 PROBABILITY QUALITY")
print("=" * 70)

print(
    f"ROC-AUC   : {auc_2025:.6f}"
)

print(
    f"PR-AUC    : {pr_auc_2025:.6f}"
)

print(
    f"Brier     : {brier_2025:.6f}"
)

print(
    f"LogLoss   : {logloss_2025:.6f}"
)


# ============================================================
# 8. PROBABILITY DISTRIBUTION
# ============================================================

print("\n" + "=" * 70)
print("2025 PROBABILITY DISTRIBUTION")
print("=" * 70)

print(
    p_2025.describe()
)


# ============================================================
# 9. FINAL CALIBRATION INTERPRETATION
# ============================================================

print("\n" + "=" * 70)
print("CALIBRATION DIAGNOSTIC")
print("=" * 70)

print(
    "OOF Brier Score:",
    round(oof_brier, 6)
)

print(
    "2025 Brier Score:",
    round(brier_2025, 6)
)

if (
    oof_brier < 0.20
    and
    brier_2025 < 0.20
):

    print(
        "✅ Probability predictions show "
        "acceptable Brier-score behavior."
    )

else:

    print(
        "⚠️ Probability calibration requires "
        "additional investigation."
    )


# ============================================================
# 10. FINAL MODEL STATUS
# ============================================================

print("\n" + "=" * 70)
print("FINAL MODEL CALIBRATION STATUS")
print("=" * 70)

print(
    "2026 data used:",
    "NO"
)

print(
    "Model retrained:",
    "NO"
)

print(
    "Decision threshold changed:",
    "NO"
)

print(
    "Architecture changed:",
    "NO"
)


# ============================================================
# 11. SAVE RESULTS
# ============================================================

os.makedirs(
    "results",
    exist_ok=True
)

reliability.to_csv(
    "results/"
    "decision_layer_reliability_oof.csv",
    index=False
)

high_risk_df.to_csv(
    "results/"
    "decision_layer_high_risk_reliability.csv",
    index=False
)

summary = pd.DataFrame({

    "dataset": [
        "OOF_2023_2024",
        "Independent_2025"
    ],

    "ROC_AUC": [
        oof_auc,
        auc_2025
    ],

    "PR_AUC": [
        oof_pr_auc,
        pr_auc_2025
    ],

    "Brier": [
        oof_brier,
        brier_2025
    ],

    "LogLoss": [
        oof_logloss,
        logloss_2025
    ]
})

summary.to_csv(
    "results/"
    "final_probability_calibration_summary.csv",
    index=False
)

print("\n" + "=" * 70)
print("FILES SAVED")
print("=" * 70)

print(
    "results/decision_layer_reliability_oof.csv"
)

print(
    "results/decision_layer_high_risk_reliability.csv"
)

print(
    "results/final_probability_calibration_summary.csv"
)

print("\n" + "=" * 70)
print("STEP 25C COMPLETE")
print("=" * 70)

======================================================================
STEP 25C — FINAL CALIBRATION & RELIABILITY CHECK
======================================================================
Decision model loaded.

======================================================================
OOF DATA
======================================================================
Rows: 853
Missing probabilities: 0
Probability minimum: 0.0034578886857259
Probability maximum: 0.997835387023731
✅ All probabilities valid.

======================================================================
OOF PROBABILITY QUALITY
======================================================================
ROC-AUC   : 0.991803
PR-AUC    : 0.987829
Brier     : 0.032460
LogLoss   : 0.112013

======================================================================
OOF RELIABILITY TABLE
======================================================================

,probability_bin,observations,mean_predicted_probability,observed_landslide_rate,absolute_calibration_error
0,0.0–0.1,499,0.0219,0.0120,0.0099
1,0.1–0.2,15,0.1496,0.1333,0.0163
2,0.2–0.3,4,0.2444,0.5000,0.2556
3,0.3–0.4,3,0.3804,0.6667,0.2862
4,0.4–0.5,8,0.4407,0.3750,0.0657
5,0.5–0.6,18,0.5523,0.0556,0.4967
6,0.6–0.7,8,0.6388,0.5000,0.1388
7,0.7–0.8,17,0.7718,0.7647,0.0071
8,0.8–0.9,15,0.8379,0.8000,0.0379
9,0.9–1.0,266,0.9906,0.9887,0.0018

======================================================================
HIGH-RISK PROBABILITY RELIABILITY
======================================================================

,threshold,observations,mean_predicted_probability,observed_landslide_rate,calibration_gap
0,0.2,339,0.9141,0.8850,0.0291
1,0.4,332,0.9270,0.8916,0.0354
2,0.5,324,0.9390,0.9043,0.0347
3,0.6,306,0.9617,0.9542,0.0075
4,0.8,281,0.9824,0.9786,0.0038
5,0.9,266,0.9906,0.9887,0.0018

======================================================================
INDEPENDENT 2025 PROBABILITY QUALITY
======================================================================
ROC-AUC   : 0.998012
PR-AUC    : 0.996952
Brier     : 0.016739
LogLoss   : 0.069904

======================================================================
2025 PROBABILITY DISTRIBUTION
======================================================================
count    1026.000000
mean        0.374520
std         0.446918
min         0.003390
25%         0.011474
50%         0.077892
75%         0.988754
max         0.997122
Name: layered_probability, dtype: float64

======================================================================
CALIBRATION DIAGNOSTIC
======================================================================
OOF Brier Score: 0.03246
2025 Brier Score: 0.016739
✅ Probability predictions show acceptable Brier-score behavior.

======================================================================
FINAL MODEL CALIBRATION STATUS
======================================================================
2026 data used: NO
Model retrained: NO
Decision threshold changed: NO
Architecture changed: NO

======================================================================
FILES SAVED
======================================================================
results/decision_layer_reliability_oof.csv
results/decision_layer_high_risk_reliability.csv
results/final_probability_calibration_summary.csv

======================================================================
STEP 25C COMPLETE
======================================================================

In [1]:
# ============================================================
# STEP 26 — STRICT GROUPED SPATIAL VALIDATION
# ============================================================

import pandas as pd
import numpy as np
import joblib
import os

from sklearn.model_selection import GroupKFold
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

from xgboost import XGBClassifier

# ============================================================
# 1. LOAD DATA
# ============================================================

DATA_PATH = (
    "data/"
    "Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv"
)

df = pd.read_csv(DATA_PATH)

df["event_date"] = pd.to_datetime(
    df["event_date"]
)

print("=" * 70)
print("STEP 26 — STRICT GROUPED SPATIAL VALIDATION")
print("=" * 70)

print("Rows:", len(df))

# ============================================================
# 2. REMOVE 2026
# ============================================================

development = df[
    df["event_date"].dt.year <= 2024
].copy()

test_2025 = df[
    df["event_date"].dt.year == 2025
].copy()

print("\nDevelopment rows:", len(development))
print("2025 rows:", len(test_2025))

# ============================================================
# 3. CREATE LOCATION GROUP
# ============================================================

def make_location_group(data):

    return (
        data["latitude"].round(5).astype(str)
        + "_"
        + data["longitude"].round(5).astype(str)
    )

development["location_group"] = (
    make_location_group(development)
)

print(
    "\nUnique development locations:",
    development["location_group"].nunique()
)

# ============================================================
# 4. XGBOOST FEATURES
# ============================================================

FEATURES = [
    "rzsm_1",
    "rzsm_2",
    "rzsm_3",
    "cumulative_rainfall_3d_mm",
    "_rzsm_mean_",
    "_rzsm_range_",
    "_rzsm_surface_deep_diff_",
    "_rain_rzsm_interaction_",
    "_previous_rzsm_",
    "_previous_rzsm_2_",
    "_previous_rzsm_3_",
    "_previous_rainfall_"
]

TARGET = "landslide_occurred"

# ============================================================
# 5. HANDLE MISSING VALUES
# ============================================================

X = development[FEATURES].copy()
y = development[TARGET].astype(int)
groups = development["location_group"]

# XGBoost accepts NaN directly.
# No imputation is introduced here.
# This preserves the frozen model's missing-value behavior.

# ============================================================
# 6. GROUP K-FOLD
# ============================================================

gkf = GroupKFold(
    n_splits=5
)

spatial_oof_probability = np.zeros(
    len(development)
)

spatial_oof_prediction = np.zeros(
    len(development),
    dtype=int
)

# ============================================================
# 7. TRAIN GROUPED MODELS
# ============================================================

for fold, (train_idx, valid_idx) in enumerate(
    gkf.split(X, y, groups),
    start=1
):

    print(
        f"\nSpatial fold {fold}/5"
    )

    X_train = X.iloc[train_idx]
    y_train = y.iloc[train_idx]

    X_valid = X.iloc[valid_idx]

    model = XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.3,
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=0,
        n_jobs=1
    )

    model.fit(
        X_train,
        y_train
    )

    probabilities = (
        model.predict_proba(
            X_valid
        )[:, 1]
    )

    predictions = (
        probabilities >= 0.50
    ).astype(int)

    spatial_oof_probability[
        valid_idx
    ] = probabilities

    spatial_oof_prediction[
        valid_idx
    ] = predictions

    print(
        "Validation locations:",
        groups.iloc[
            valid_idx
        ].nunique()
    )

# ============================================================
# 8. CHECK COMPLETENESS
# ============================================================

print("\n" + "=" * 70)
print("SPATIAL OOF COMPLETENESS")
print("=" * 70)

print(
    "Missing predictions:",
    np.isnan(
        spatial_oof_probability
    ).sum()
)

# ============================================================
# 9. METRICS
# ============================================================

spatial_auc = roc_auc_score(
    y,
    spatial_oof_probability
)

spatial_pr_auc = average_precision_score(
    y,
    spatial_oof_probability
)

spatial_accuracy = accuracy_score(
    y,
    spatial_oof_prediction
)

spatial_precision = precision_score(
    y,
    spatial_oof_prediction,
    zero_division=0
)

spatial_recall = recall_score(
    y,
    spatial_oof_prediction,
    zero_division=0
)

spatial_f1 = f1_score(
    y,
    spatial_oof_prediction,
    zero_division=0
)

cm = confusion_matrix(
    y,
    spatial_oof_prediction
)

# ============================================================
# 10. RESULTS
# ============================================================

print("\n" + "=" * 70)
print("STRICT SPATIAL OOF RESULTS")
print("=" * 70)

print(
    f"ROC-AUC   : {spatial_auc:.6f}"
)

print(
    f"PR-AUC    : {spatial_pr_auc:.6f}"
)

print(
    f"Accuracy  : {spatial_accuracy:.6f}"
)

print(
    f"Precision : {spatial_precision:.6f}"
)

print(
    f"Recall    : {spatial_recall:.6f}"
)

print(
    f"F1        : {spatial_f1:.6f}"
)

print("\nConfusion Matrix:")
print(cm)

# ============================================================
# 11. SAVE SPATIAL OOF RESULTS
# ============================================================

development[
    "spatial_oof_probability"
] = spatial_oof_probability

development[
    "spatial_oof_prediction"
] = spatial_oof_prediction

os.makedirs(
    "results",
    exist_ok=True
)

development.to_csv(
    "results/"
    "strict_spatial_xgboost_oof.csv",
    index=False
)

summary = pd.DataFrame({

    "metric": [
        "ROC-AUC",
        "PR-AUC",
        "Accuracy",
        "Precision",
        "Recall",
        "F1"
    ],

    "spatial_oof": [
        spatial_auc,
        spatial_pr_auc,
        spatial_accuracy,
        spatial_precision,
        spatial_recall,
        spatial_f1
    ]
})

summary.to_csv(
    "results/"
    "strict_spatial_xgboost_summary.csv",
    index=False
)

print("\n" + "=" * 70)
print("STEP 26 COMPLETE")
print("=" * 70)

print(
    "Saved:"
)

print(
    "results/strict_spatial_xgboost_oof.csv"
)

print(
    "results/strict_spatial_xgboost_summary.csv"
)

======================================================================
STEP 26 — STRICT GROUPED SPATIAL VALIDATION
======================================================================
Rows: 2016

Development rows: 853
2025 rows: 1026

Unique development locations: 303

Spatial fold 1/5
Validation locations: 59

Spatial fold 2/5
Validation locations: 60

Spatial fold 3/5
Validation locations: 61

Spatial fold 4/5
Validation locations: 61

Spatial fold 5/5
Validation locations: 62

======================================================================
SPATIAL OOF COMPLETENESS
======================================================================
Missing predictions: 0

======================================================================
STRICT SPATIAL OOF RESULTS
======================================================================
ROC-AUC   : 0.986179
PR-AUC    : 0.964658
Accuracy  : 0.953107
Precision : 0.932258
Recall    : 0.938312
F1        : 0.935275

Confusion Matrix:
[[524  21]
 [ 19 289]]

======================================================================
STEP 26 COMPLETE
======================================================================
Saved:
results/strict_spatial_xgboost_oof.csv
results/strict_spatial_xgboost_summary.csv

In [2]:
# ============================================================
# STEP 27A — BUILD SPATIALLY VALID META DATASET
# ============================================================

import pandas as pd
import numpy as np
import os

from sklearn.model_selection import GroupKFold
from xgboost import XGBClassifier

# ============================================================
# 1. LOAD DEVELOPMENT DATA
# ============================================================

DATA_PATH = (
    "data/"
    "Landslide_NER_MASTER_2016_ROWS_WITH_XGBOOST_FEATURES.csv"
)

df = pd.read_csv(DATA_PATH)

df["event_date"] = pd.to_datetime(
    df["event_date"]
)

development = df[
    df["event_date"].dt.year <= 2024
].copy()

print("=" * 70)
print("STEP 27A — SPATIALLY VALID META DATASET")
print("=" * 70)

print("Development rows:", len(development))

# ============================================================
# 2. LOCATION GROUP
# ============================================================

development["location_group"] = (
    development["latitude"].round(5).astype(str)
    + "_"
    + development["longitude"].round(5).astype(str)
)

print(
    "Unique locations:",
    development["location_group"].nunique()
)

# ============================================================
# 3. XGBOOST FEATURES
# ============================================================

XGB_FEATURES = [
    "rzsm_1",
    "rzsm_2",
    "rzsm_3",
    "cumulative_rainfall_3d_mm",
    "_rzsm_mean_",
    "_rzsm_range_",
    "_rzsm_surface_deep_diff_",
    "_rain_rzsm_interaction_",
    "_previous_rzsm_",
    "_previous_rzsm_2_",
    "_previous_rzsm_3_",
    "_previous_rainfall_"
]

TARGET = "landslide_occurred"

X = development[
    XGB_FEATURES
].copy()

y = development[
    TARGET
].astype(int)

groups = development[
    "location_group"
]

# ============================================================
# 4. SPATIAL OOF PREDICTIONS
# ============================================================

gkf = GroupKFold(
    n_splits=5
)

spatial_oof_probability = np.zeros(
    len(development)
)

spatial_oof_prediction = np.zeros(
    len(development),
    dtype=int
)

for fold, (train_idx, valid_idx) in enumerate(
    gkf.split(X, y, groups),
    start=1
):

    print(
        f"\nTraining spatial OOF fold "
        f"{fold}/5..."
    )

    model = XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.3,
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=0,
        n_jobs=1
    )

    model.fit(
        X.iloc[train_idx],
        y.iloc[train_idx]
    )

    prob = model.predict_proba(
        X.iloc[valid_idx]
    )[:, 1]

    spatial_oof_probability[
        valid_idx
    ] = prob

    spatial_oof_prediction[
        valid_idx
    ] = (
        prob >= 0.50
    ).astype(int)

# ============================================================
# 5. CHECK COMPLETENESS
# ============================================================

print("\n" + "=" * 70)
print("SPATIAL META PREDICTION CHECK")
print("=" * 70)

print(
    "Missing:",
    np.isnan(
        spatial_oof_probability
    ).sum()
)

print(
    "Minimum:",
    spatial_oof_probability.min()
)

print(
    "Maximum:",
    spatial_oof_probability.max()
)

# ============================================================
# 6. LOAD ORIGINAL AHC OUTPUTS
# ============================================================

LAYERING_PATH = (
    "data/"
    "layering_dataset.csv"
)

if not os.path.exists(
    LAYERING_PATH
):

    # Try common alternative filename
    alternatives = [
        "data/layering_dataset.csv",
        "data/layering_data.csv",
        "data/decision_model_preliminary_dataset.csv"
    ]

    found = None

    for path in alternatives:

        if os.path.exists(path):

            found = path
            break

    if found is None:

        raise FileNotFoundError(
            "Could not find layering dataset. "
            "Please locate the CSV containing "
            "ahc_cluster, ahc_susceptibility, "
            "ahc_category and master_row_id."
        )

    LAYERING_PATH = found

layering = pd.read_csv(
    LAYERING_PATH
)

print(
    "\nAHC source:",
    LAYERING_PATH
)

# ============================================================
# 7. REQUIRED AHC COLUMNS
# ============================================================

AHC_COLUMNS = [
    "master_row_id",
    "ahc_cluster",
    "ahc_susceptibility",
    "ahc_category"
]

missing = [
    c for c in AHC_COLUMNS
    if c not in layering.columns
]

if missing:

    raise ValueError(
        f"Missing AHC columns: {missing}"
    )

# ============================================================
# 8. MERGE USING MASTER ROW ID
# ============================================================

development_meta = development[
    [
        "master_row_id",
        "event_date",
        "state",
        "district",
        "latitude",
        "longitude",
        TARGET
    ]
].copy()

development_meta[
    "xgb_spatial_oof_probability"
] = spatial_oof_probability

development_meta[
    "xgb_spatial_oof_prediction"
] = spatial_oof_prediction

development_meta = development_meta.merge(
    layering[
        AHC_COLUMNS
    ],
    on="master_row_id",
    how="left",
    validate="one_to_one"
)

# ============================================================
# 9. VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("META DATA VALIDATION")
print("=" * 70)

print(
    "Rows:",
    len(development_meta)
)

print(
    "\nMissing values:"
)

print(
    development_meta[
        [
            "xgb_spatial_oof_probability",
            "xgb_spatial_oof_prediction",
            "ahc_cluster",
            "ahc_susceptibility",
            "ahc_category"
        ]
    ].isna().sum()
)

if development_meta[
    [
        "xgb_spatial_oof_probability",
        "ahc_cluster",
        "ahc_susceptibility",
        "ahc_category"
    ]
].isna().any().any():

    raise ValueError(
        "Missing meta-model inputs detected."
    )

# ============================================================
# 10. SAVE
# ============================================================

OUTPUT = (
    "data/"
    "decision_model_spatial_oof_training.csv"
)

development_meta.to_csv(
    OUTPUT,
    index=False
)

print("\n" + "=" * 70)
print("SAVED")
print("=" * 70)

print(OUTPUT)

print("\n" + "=" * 70)
print("STEP 27A COMPLETE")
print("=" * 70)

======================================================================
STEP 27A — SPATIALLY VALID META DATASET
======================================================================
Development rows: 853
Unique locations: 303

Training spatial OOF fold 1/5...

Training spatial OOF fold 2/5...

Training spatial OOF fold 3/5...

Training spatial OOF fold 4/5...

Training spatial OOF fold 5/5...

======================================================================
SPATIAL META PREDICTION CHECK
======================================================================
Missing: 0
Minimum: 1.3745953992838622e-06
Maximum: 0.9999805688858032

AHC source: data/layering_dataset.csv

======================================================================
META DATA VALIDATION
======================================================================
Rows: 853

Missing values:
xgb_spatial_oof_probability    0
xgb_spatial_oof_prediction     0
ahc_cluster                    0
ahc_susceptibility             0
ahc_category                   0
dtype: int64

======================================================================
SAVED
======================================================================
data/decision_model_spatial_oof_training.csv

======================================================================
STEP 27A COMPLETE
======================================================================

In [3]:
# ============================================================
# STEP 27B — SPATIALLY VALIDATED DECISION LAYER
# ============================================================

import pandas as pd
import numpy as np
import joblib
import os

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    log_loss,
    brier_score_loss
)

# ============================================================
# 1. LOAD SPATIAL META DATA
# ============================================================

DATA_PATH = (
    "data/"
    "decision_model_spatial_oof_training.csv"
)

df = pd.read_csv(DATA_PATH)

print("=" * 70)
print("STEP 27B — SPATIALLY VALIDATED DECISION LAYER")
print("=" * 70)

print("Rows:", len(df))

# ============================================================
# 2. FEATURES
# ============================================================

NUMERIC_FEATURES = [
    "xgb_spatial_oof_probability",
    "ahc_susceptibility",
    "ahc_cluster"
]

CATEGORICAL_FEATURES = [
    "ahc_category"
]

FEATURES = (
    NUMERIC_FEATURES
    + CATEGORICAL_FEATURES
)

TARGET = "landslide_occurred"

X = df[FEATURES].copy()
y = df[TARGET].astype(int)

# ============================================================
# 3. VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("INPUT VALIDATION")
print("=" * 70)

print("\nMissing values:")
print(X.isna().sum())

if X.isna().any().any():
    raise ValueError(
        "Missing Decision Layer inputs detected."
    )

print("\nTarget:")
print(y.value_counts())

# ============================================================
# 4. CREATE PREPROCESSOR
# ============================================================

def create_model():

    preprocessor = ColumnTransformer(
        transformers=[
            (
                "numeric",
                StandardScaler(),
                NUMERIC_FEATURES
            ),
            (
                "categorical",
                OneHotEncoder(
                    handle_unknown="ignore"
                ),
                CATEGORICAL_FEATURES
            )
        ]
    )

    return Pipeline(
        steps=[
            (
                "preprocessor",
                preprocessor
            ),
            (
                "classifier",
                LogisticRegression(
                    max_iter=2000,
                    class_weight="balanced",
                    random_state=0
                )
            )
        ]
    )

# ============================================================
# 5. 5-FOLD META VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("SPATIAL META-MODEL 5-FOLD VALIDATION")
print("=" * 70)

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=0
)

meta_oof_probability = np.zeros(
    len(df)
)

for fold, (train_idx, valid_idx) in enumerate(
    skf.split(X, y),
    start=1
):

    print(
        f"Training Decision Layer fold "
        f"{fold}/5..."
    )

    fold_model = create_model()

    fold_model.fit(
        X.iloc[train_idx],
        y.iloc[train_idx]
    )

    meta_oof_probability[
        valid_idx
    ] = (
        fold_model.predict_proba(
            X.iloc[valid_idx]
        )[:, 1]
    )

# ============================================================
# 6. PREDICTIONS
# ============================================================

meta_oof_prediction = (
    meta_oof_probability >= 0.50
).astype(int)

# ============================================================
# 7. METRICS
# ============================================================

roc_auc = roc_auc_score(
    y,
    meta_oof_probability
)

pr_auc = average_precision_score(
    y,
    meta_oof_probability
)

accuracy = accuracy_score(
    y,
    meta_oof_prediction
)

precision = precision_score(
    y,
    meta_oof_prediction,
    zero_division=0
)

recall = recall_score(
    y,
    meta_oof_prediction,
    zero_division=0
)

f1 = f1_score(
    y,
    meta_oof_prediction,
    zero_division=0
)

brier = brier_score_loss(
    y,
    meta_oof_probability
)

logloss = log_loss(
    y,
    meta_oof_probability
)

cm = confusion_matrix(
    y,
    meta_oof_prediction
)

# ============================================================
# 8. RESULTS
# ============================================================

print("\n" + "=" * 70)
print("SPATIALLY VALIDATED DECISION LAYER OOF")
print("=" * 70)

print(f"ROC-AUC   : {roc_auc:.6f}")
print(f"PR-AUC    : {pr_auc:.6f}")
print(f"Accuracy  : {accuracy:.6f}")
print(f"Precision : {precision:.6f}")
print(f"Recall    : {recall:.6f}")
print(f"F1        : {f1:.6f}")
print(f"Brier     : {brier:.6f}")
print(f"LogLoss   : {logloss:.6f}")

print("\nConfusion Matrix:")
print(cm)

# ============================================================
# 9. FIT FINAL SPATIAL DECISION MODEL
# ============================================================

print("\n" + "=" * 70)
print("TRAINING FINAL SPATIAL DECISION MODEL")
print("=" * 70)

spatial_decision_model = create_model()

spatial_decision_model.fit(
    X,
    y
)

print(
    "✅ Spatial Decision Layer trained."
)

# ============================================================
# 10. SAVE MODEL
# ============================================================

MODEL_OUTPUT = (
    "models/"
    "spatial_layered_decision_model.pkl"
)

os.makedirs(
    "models",
    exist_ok=True
)

joblib.dump(
    spatial_decision_model,
    MODEL_OUTPUT
)

print(
    "\n✅ Saved:"
)

print(
    MODEL_OUTPUT
)

# ============================================================
# 11. SAVE OOF RESULTS
# ============================================================

df[
    "decision_spatial_oof_probability"
] = meta_oof_probability

df[
    "decision_spatial_oof_prediction"
] = meta_oof_prediction

RESULT_OUTPUT = (
    "results/"
    "spatial_decision_layer_oof_results.csv"
)

os.makedirs(
    "results",
    exist_ok=True
)

df.to_csv(
    RESULT_OUTPUT,
    index=False
)

# ============================================================
# 12. SAVE SUMMARY
# ============================================================

SUMMARY_OUTPUT = (
    "results/"
    "spatial_decision_layer_summary.csv"
)

summary = pd.DataFrame({
    "metric": [
        "ROC-AUC",
        "PR-AUC",
        "Accuracy",
        "Precision",
        "Recall",
        "F1",
        "Brier",
        "LogLoss"
    ],
    "value": [
        roc_auc,
        pr_auc,
        accuracy,
        precision,
        recall,
        f1,
        brier,
        logloss
    ]
})

summary.to_csv(
    SUMMARY_OUTPUT,
    index=False
)

# ============================================================
# 13. FINAL CHECK
# ============================================================

print("\n" + "=" * 70)
print("FILE VERIFICATION")
print("=" * 70)

print(
    "Model exists:",
    os.path.exists(MODEL_OUTPUT)
)

print(
    "OOF results exist:",
    os.path.exists(RESULT_OUTPUT)
)

print(
    "Summary exists:",
    os.path.exists(SUMMARY_OUTPUT)
)

print("\n" + "=" * 70)
print("STEP 27B COMPLETE")
print("=" * 70)

======================================================================
STEP 27B — SPATIALLY VALIDATED DECISION LAYER
======================================================================
Rows: 853

======================================================================
INPUT VALIDATION
======================================================================

Missing values:
xgb_spatial_oof_probability    0
ahc_susceptibility             0
ahc_cluster                    0
ahc_category                   0
dtype: int64

Target:
landslide_occurred
0    545
1    308
Name: count, dtype: int64

======================================================================
SPATIAL META-MODEL 5-FOLD VALIDATION
======================================================================
Training Decision Layer fold 1/5...
Training Decision Layer fold 2/5...
Training Decision Layer fold 3/5...
Training Decision Layer fold 4/5...
Training Decision Layer fold 5/5...

======================================================================
SPATIALLY VALIDATED DECISION LAYER OOF
======================================================================
ROC-AUC   : 0.992762
PR-AUC    : 0.989186
Accuracy  : 0.951934
Precision : 0.908257
Recall    : 0.964286
F1        : 0.935433
Brier     : 0.030670
LogLoss   : 0.108047

Confusion Matrix:
[[515  30]
 [ 11 297]]

======================================================================
TRAINING FINAL SPATIAL DECISION MODEL
======================================================================
✅ Spatial Decision Layer trained.

✅ Saved:
models/spatial_layered_decision_model.pkl

======================================================================
FILE VERIFICATION
======================================================================
Model exists: True
OOF results exist: True
Summary exists: True

======================================================================
STEP 27B COMPLETE
======================================================================

In [4]:
# ============================================================
# STEP 27C — HEAD-TO-HEAD 2025 EVALUATION
# OLD vs SPATIALLY VALIDATED LAYERED MODEL
# ============================================================

import pandas as pd
import numpy as np
import joblib
import os

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    brier_score_loss,
    log_loss,
    confusion_matrix
)

# ============================================================
# 1. LOAD 2025 TEST DATA
# ============================================================

TEST_PATH = "data/decision_model_test_2025.csv"

test = pd.read_csv(TEST_PATH)

print("=" * 70)
print("STEP 27C — INDEPENDENT 2025 HEAD-TO-HEAD TEST")
print("=" * 70)

print("2025 rows:", len(test))

test["event_date"] = pd.to_datetime(
    test["event_date"]
)

print(
    "Date range:",
    test["event_date"].min(),
    "to",
    test["event_date"].max()
)

y = test["landslide_occurred"].astype(int)

print("\nTarget distribution:")
print(y.value_counts())

# ============================================================
# 2. LOAD OLD AND NEW DECISION MODELS
# ============================================================

OLD_MODEL_PATH = (
    "models/layered_decision_model.pkl"
)

NEW_MODEL_PATH = (
    "models/spatial_layered_decision_model.pkl"
)

old_model = joblib.load(
    OLD_MODEL_PATH
)

new_model = joblib.load(
    NEW_MODEL_PATH
)

print("\nOld model loaded:", os.path.exists(OLD_MODEL_PATH))
print("New model loaded:", os.path.exists(NEW_MODEL_PATH))

# ============================================================
# 3. REQUIRED INPUT COLUMNS
# ============================================================

required = [
    "xgb_probability",
    "ahc_susceptibility",
    "ahc_cluster",
    "ahc_category"
]

missing = [
    c for c in required
    if c not in test.columns
]

if missing:
    raise ValueError(
        f"Missing required 2025 columns: {missing}"
    )

# ============================================================
# 4. OLD MODEL INPUT
# ============================================================

X_old = test[
    [
        "xgb_probability",
        "ahc_susceptibility",
        "ahc_cluster",
        "ahc_category"
    ]
].copy()

# ============================================================
# 5. NEW MODEL INPUT
#
# IMPORTANT:
# The new model expects the spatial-OFF XGBoost
# probability column.
#
# For the independent 2025 test, the frozen XGBoost
# probability is used because 2025 was never used
# during XGBoost development.
# ============================================================

X_new = pd.DataFrame({

    "xgb_spatial_oof_probability":
        test["xgb_probability"],

    "ahc_susceptibility":
        test["ahc_susceptibility"],

    "ahc_cluster":
        test["ahc_cluster"],

    "ahc_category":
        test["ahc_category"]

})

# ============================================================
# 6. INPUT VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("MODEL INPUT CHECK")
print("=" * 70)

print("\nOld model missing:")
print(X_old.isna().sum())

print("\nNew model missing:")
print(X_new.isna().sum())

if X_old.isna().any().any():
    raise ValueError(
        "Missing values in old model inputs."
    )

if X_new.isna().any().any():
    raise ValueError(
        "Missing values in new model inputs."
    )

# ============================================================
# 7. GENERATE PREDICTIONS
# ============================================================

old_probability = (
    old_model
    .predict_proba(X_old)[:, 1]
)

new_probability = (
    new_model
    .predict_proba(X_new)[:, 1]
)

old_prediction = (
    old_probability >= 0.50
).astype(int)

new_prediction = (
    new_probability >= 0.50
).astype(int)

# ============================================================
# 8. METRIC FUNCTION
# ============================================================

def evaluate_model(
    name,
    probability,
    prediction
):

    return {

        "Model": name,

        "ROC-AUC":
            roc_auc_score(
                y,
                probability
            ),

        "PR-AUC":
            average_precision_score(
                y,
                probability
            ),

        "Accuracy":
            accuracy_score(
                y,
                prediction
            ),

        "Precision":
            precision_score(
                y,
                prediction,
                zero_division=0
            ),

        "Recall":
            recall_score(
                y,
                prediction,
                zero_division=0
            ),

        "F1":
            f1_score(
                y,
                prediction,
                zero_division=0
            ),

        "Brier":
            brier_score_loss(
                y,
                probability
            ),

        "LogLoss":
            log_loss(
                y,
                probability
            )
    }

# ============================================================
# 9. EVALUATE BOTH
# ============================================================

old_results = evaluate_model(
    "OLD_LAYERED_MODEL",
    old_probability,
    old_prediction
)

new_results = evaluate_model(
    "SPATIAL_LAYERED_MODEL",
    new_probability,
    new_prediction
)

comparison = pd.DataFrame([
    old_results,
    new_results
])

print("\n" + "=" * 70)
print("2025 HEAD-TO-HEAD RESULTS")
print("=" * 70)

print(
    comparison.to_string(
        index=False,
        float_format=lambda x: f"{x:.6f}"
    )
)

# ============================================================
# 10. CONFUSION MATRICES
# ============================================================

print("\n" + "=" * 70)
print("OLD MODEL CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y,
        old_prediction
    )
)

print("\n" + "=" * 70)
print("NEW SPATIAL MODEL CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y,
        new_prediction
    )
)

# ============================================================
# 11. IMPROVEMENT / DEGRADATION
# ============================================================

print("\n" + "=" * 70)
print("NEW MODEL − OLD MODEL")
print("=" * 70)

metrics = [
    "ROC-AUC",
    "PR-AUC",
    "Accuracy",
    "Precision",
    "Recall",
    "F1",
    "Brier",
    "LogLoss"
]

for metric in metrics:

    old_value = old_results[metric]
    new_value = new_results[metric]

    difference = (
        new_value - old_value
    )

    print(
        f"{metric:<10}: "
        f"{difference:+.6f}"
    )

# ============================================================
# 12. PREDICTION AGREEMENT
# ============================================================

agreement = (
    old_prediction ==
    new_prediction
)

print("\n" + "=" * 70)
print("MODEL PREDICTION AGREEMENT")
print("=" * 70)

print(
    "Same predictions:",
    agreement.sum()
)

print(
    "Different predictions:",
    (~agreement).sum()
)

print(
    "Agreement:",
    f"{agreement.mean() * 100:.2f}%"
)

# ============================================================
# 13. SAVE PREDICTIONS
# ============================================================

output = test[
    [
        "master_row_id",
        "event_date",
        "state",
        "district",
        "latitude",
        "longitude",
        "landslide_occurred"
    ]
].copy()

output[
    "old_layered_probability"
] = old_probability

output[
    "old_layered_prediction"
] = old_prediction

output[
    "spatial_layered_probability"
] = new_probability

output[
    "spatial_layered_prediction"
] = new_prediction

OUTPUT_PATH = (
    "results/"
    "step27c_2025_old_vs_spatial_predictions.csv"
)

os.makedirs(
    "results",
    exist_ok=True
)

output.to_csv(
    OUTPUT_PATH,
    index=False
)

# ============================================================
# 14. SAVE COMPARISON
# ============================================================

COMPARISON_PATH = (
    "results/"
    "step27c_2025_old_vs_spatial_comparison.csv"
)

comparison.to_csv(
    COMPARISON_PATH,
    index=False
)

print("\n" + "=" * 70)
print("FILES SAVED")
print("=" * 70)

print(OUTPUT_PATH)
print(COMPARISON_PATH)

print("\n" + "=" * 70)
print("STEP 27C COMPLETE")
print("=" * 70)

======================================================================
STEP 27C — INDEPENDENT 2025 HEAD-TO-HEAD TEST
======================================================================
2025 rows: 1026
Date range: 2025-01-01 00:00:00 to 2025-12-30 00:00:00

Target distribution:
landslide_occurred
0    662
1    364
Name: count, dtype: int64

Old model loaded: True
New model loaded: True

======================================================================
MODEL INPUT CHECK
======================================================================

Old model missing:
xgb_probability       0
ahc_susceptibility    0
ahc_cluster           0
ahc_category          0
dtype: int64

New model missing:
xgb_spatial_oof_probability    0
ahc_susceptibility             0
ahc_cluster                    0
ahc_category                   0
dtype: int64

ValueError: columns are missing: {'xgb_oof_probability'}

In [5]:
# ============================================================
# STEP 27C — CORRECTED 2025 HEAD-TO-HEAD EVALUATION
# ============================================================

import pandas as pd
import numpy as np
import joblib
import os

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    brier_score_loss,
    log_loss,
    confusion_matrix
)

# ============================================================
# 1. LOAD 2025 TEST
# ============================================================

TEST_PATH = "data/decision_model_test_2025.csv"

test = pd.read_csv(TEST_PATH)

test["event_date"] = pd.to_datetime(
    test["event_date"]
)

print("=" * 70)
print("STEP 27C — CORRECTED 2025 HEAD-TO-HEAD TEST")
print("=" * 70)

print("Rows:", len(test))

y = test[
    "landslide_occurred"
].astype(int)

print("\nTarget:")
print(y.value_counts())

# ============================================================
# 2. LOAD MODELS
# ============================================================

OLD_MODEL = joblib.load(
    "models/layered_decision_model.pkl"
)

NEW_MODEL = joblib.load(
    "models/spatial_layered_decision_model.pkl"
)

print("\n✅ Old Decision Model loaded.")
print("✅ Spatial Decision Model loaded.")

# ============================================================
# 3. CHECK REQUIRED 2025 INPUTS
# ============================================================

required = [
    "xgb_probability",
    "ahc_susceptibility",
    "ahc_cluster",
    "ahc_category"
]

missing = [
    c for c in required
    if c not in test.columns
]

if missing:
    raise ValueError(
        f"Missing required columns: {missing}"
    )

# ============================================================
# 4. IMPORTANT MODEL-SCHEMA CHECK
# ============================================================

print("\n" + "=" * 70)
print("MODEL FEATURE SCHEMAS")
print("=" * 70)

print(
    "\nOld model expects:"
)

print(
    OLD_MODEL
    .named_steps["preprocessor"]
    .transformers
)

print(
    "\nNew model expects:"
)

print(
    NEW_MODEL
    .named_steps["preprocessor"]
    .transformers
)

# ============================================================
# 5. OLD MODEL — 2025 INPUT
#
# The old model was trained on:
# xgb_oof_probability
#
# Therefore we must construct the same feature NAME.
#
# The VALUE is the frozen XGBoost probability generated
# for the independent 2025 test.
# ============================================================

X_old = pd.DataFrame({

    "xgb_oof_probability":
        test["xgb_probability"],

    "ahc_susceptibility":
        test["ahc_susceptibility"],

    "ahc_cluster":
        test["ahc_cluster"],

    "ahc_category":
        test["ahc_category"]

})

# ============================================================
# 6. NEW SPATIAL MODEL INPUT
# ============================================================

X_new = pd.DataFrame({

    "xgb_spatial_oof_probability":
        test["xgb_probability"],

    "ahc_susceptibility":
        test["ahc_susceptibility"],

    "ahc_cluster":
        test["ahc_cluster"],

    "ahc_category":
        test["ahc_category"]

})

# ============================================================
# 7. INPUT CHECK
# ============================================================

print("\n" + "=" * 70)
print("INPUT VALIDATION")
print("=" * 70)

print("\nOld model:")
print(X_old.isna().sum())

print("\nNew model:")
print(X_new.isna().sum())

if X_old.isna().any().any():
    raise ValueError(
        "Missing values in old model input."
    )

if X_new.isna().any().any():
    raise ValueError(
        "Missing values in new model input."
    )

# ============================================================
# 8. PREDICT
# ============================================================

old_probability = (
    OLD_MODEL
    .predict_proba(X_old)[:, 1]
)

new_probability = (
    NEW_MODEL
    .predict_proba(X_new)[:, 1]
)

old_prediction = (
    old_probability >= 0.50
).astype(int)

new_prediction = (
    new_probability >= 0.50
).astype(int)

print(
    "\n✅ Both models generated predictions."
)

# ============================================================
# 9. METRIC FUNCTION
# ============================================================

def evaluate(
    name,
    probability,
    prediction
):

    return {

        "Model": name,

        "ROC-AUC":
            roc_auc_score(
                y,
                probability
            ),

        "PR-AUC":
            average_precision_score(
                y,
                probability
            ),

        "Accuracy":
            accuracy_score(
                y,
                prediction
            ),

        "Precision":
            precision_score(
                y,
                prediction,
                zero_division=0
            ),

        "Recall":
            recall_score(
                y,
                prediction,
                zero_division=0
            ),

        "F1":
            f1_score(
                y,
                prediction,
                zero_division=0
            ),

        "Brier":
            brier_score_loss(
                y,
                probability
            ),

        "LogLoss":
            log_loss(
                y,
                probability
            )
    }

# ============================================================
# 10. RESULTS
# ============================================================

old_result = evaluate(
    "OLD_LAYERED_MODEL",
    old_probability,
    old_prediction
)

new_result = evaluate(
    "SPATIAL_LAYERED_MODEL",
    new_probability,
    new_prediction
)

comparison = pd.DataFrame([
    old_result,
    new_result
])

print("\n" + "=" * 70)
print("2025 HEAD-TO-HEAD RESULTS")
print("=" * 70)

print(
    comparison.to_string(
        index=False,
        float_format=lambda x:
        f"{x:.6f}"
    )
)

# ============================================================
# 11. CONFUSION MATRICES
# ============================================================

print("\n" + "=" * 70)
print("OLD MODEL CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y,
        old_prediction
    )
)

print("\n" + "=" * 70)
print("NEW SPATIAL MODEL CONFUSION MATRIX")
print("=" * 70)

print(
    confusion_matrix(
        y,
        new_prediction
    )
)

# ============================================================
# 12. DIFFERENCE
# ============================================================

print("\n" + "=" * 70)
print("NEW MODEL − OLD MODEL")
print("=" * 70)

metrics = [
    "ROC-AUC",
    "PR-AUC",
    "Accuracy",
    "Precision",
    "Recall",
    "F1",
    "Brier",
    "LogLoss"
]

for metric in metrics:

    difference = (
        new_result[metric]
        - old_result[metric]
    )

    print(
        f"{metric:<10}: "
        f"{difference:+.6f}"
    )

# ============================================================
# 13. PREDICTION AGREEMENT
# ============================================================

same = (
    old_prediction ==
    new_prediction
)

print("\n" + "=" * 70)
print("PREDICTION AGREEMENT")
print("=" * 70)

print(
    "Same:",
    same.sum()
)

print(
    "Different:",
    (~same).sum()
)

print(
    "Agreement:",
    f"{same.mean()*100:.2f}%"
)

# ============================================================
# 14. SAVE PREDICTIONS
# ============================================================

output = test[
    [
        "master_row_id",
        "event_date",
        "state",
        "district",
        "latitude",
        "longitude",
        "landslide_occurred"
    ]
].copy()

output[
    "old_layered_probability"
] = old_probability

output[
    "old_layered_prediction"
] = old_prediction

output[
    "spatial_layered_probability"
] = new_probability

output[
    "spatial_layered_prediction"
] = new_prediction

os.makedirs(
    "results",
    exist_ok=True
)

PRED_PATH = (
    "results/"
    "step27c_2025_old_vs_spatial_predictions.csv"
)

COMP_PATH = (
    "results/"
    "step27c_2025_old_vs_spatial_comparison.csv"
)

output.to_csv(
    PRED_PATH,
    index=False
)

comparison.to_csv(
    COMP_PATH,
    index=False
)

print("\n" + "=" * 70)
print("FILES SAVED")
print("=" * 70)

print(PRED_PATH)
print(COMP_PATH)

print("\n" + "=" * 70)
print("STEP 27C COMPLETE")
print("=" * 70)

======================================================================
STEP 27C — CORRECTED 2025 HEAD-TO-HEAD TEST
======================================================================
Rows: 1026

Target:
landslide_occurred
0    662
1    364
Name: count, dtype: int64

✅ Old Decision Model loaded.
✅ Spatial Decision Model loaded.

======================================================================
MODEL FEATURE SCHEMAS
======================================================================

Old model expects:
[('numeric', StandardScaler(), ['xgb_oof_probability', 'ahc_susceptibility', 'ahc_cluster']), ('categorical', OneHotEncoder(handle_unknown='ignore'), ['ahc_category'])]

New model expects:
[('numeric', StandardScaler(), ['xgb_spatial_oof_probability', 'ahc_susceptibility', 'ahc_cluster']), ('categorical', OneHotEncoder(handle_unknown='ignore'), ['ahc_category'])]

======================================================================
INPUT VALIDATION
======================================================================

Old model:
xgb_oof_probability    0
ahc_susceptibility     0
ahc_cluster            0
ahc_category           0
dtype: int64

New model:
xgb_spatial_oof_probability    0
ahc_susceptibility             0
ahc_cluster                    0
ahc_category                   0
dtype: int64

✅ Both models generated predictions.

======================================================================
2025 HEAD-TO-HEAD RESULTS
======================================================================
                Model  ROC-AUC   PR-AUC  Accuracy  Precision   Recall       F1    Brier  LogLoss
    OLD_LAYERED_MODEL 0.998012 0.996952  0.979532   0.954907 0.989011 0.971660 0.016739 0.069904
SPATIAL_LAYERED_MODEL 0.998025 0.996979  0.985380   0.970350 0.989011 0.979592 0.016261 0.067609

======================================================================
OLD MODEL CONFUSION MATRIX
======================================================================
[[645  17]
 [  4 360]]

======================================================================
NEW SPATIAL MODEL CONFUSION MATRIX
======================================================================
[[651  11]
 [  4 360]]

======================================================================
NEW MODEL − OLD MODEL
======================================================================
ROC-AUC   : +0.000012
PR-AUC    : +0.000028
Accuracy  : +0.005848
Precision : +0.015443
Recall    : +0.000000
F1        : +0.007932
Brier     : -0.000478
LogLoss   : -0.002295

======================================================================
PREDICTION AGREEMENT
======================================================================
Same: 1020
Different: 6
Agreement: 99.42%

======================================================================
FILES SAVED
======================================================================
results/step27c_2025_old_vs_spatial_predictions.csv
results/step27c_2025_old_vs_spatial_comparison.csv

======================================================================
STEP 27C COMPLETE
======================================================================